[package]
name = "creditcoin3-cli-opt"
authors = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
license = "GPL-3.0-only"

[dependencies]
clap = { workspace = true, features = ["derive"] }
