[package]
name = "creditcoin3-cli-opt"
authors = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
license = "GPL-3.0-only"

[dependencies]
bip32 = { workspace = true, features = ["bip39"] }
clap = { workspace = true, features = ["derive"] }
libsecp256k1 = { workspace = true, features = ["std"] }
primitive-types = { workspace = true }
sha3 = { workspace = true }
tiny-bip39 = { workspace = true }
url = { workspace = true }

# Substrate
sp-runtime = { workspace = true, features = ["std"] }
