[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "eth"
publish.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
alloy = { workspace = true, features = ["full"] }

anyhow = { workspace = true }
async-trait = { workspace = true }
futures = "0.3.30"
futures-util = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
sp-core = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["signal", "time", "macros"] }
tracing = { workspace = true }
url = { workspace = true }
usc-abi-encoding = { workspace = true }

# Local dependencies
attestor-primitives = { workspace = true, features = ["std"] }
merkle = { workspace = true }
user = { workspace = true }
utils = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
