
//! Autogenerated weights for `crate`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.1.0
//! DATE: 2026-06-24, STEPS: `2`, REPEAT: `2`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `localhost`, CPU: `AMD EPYC 7713 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/creditcoin3-node
// benchmark
// pallet
// --chain
// dev
// --steps=2
// --repeat=2
// --pallet
// crate
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=10000
// --output
// ./pallets/attestation/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `crate`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
	/// Storage: `SupportedChains::SupportedChains` (r:1 w:0)
	/// Proof: `SupportedChains::SupportedChains` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::PendingAttestationInterval` (r:0 w:1)
	/// Proof: `Attestation::PendingAttestationInterval` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_chain_attestation_interval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `369`
		//  Estimated: `3834`
		// Minimum execution time: 27_340_000 picoseconds.
		Weight::from_parts(28_840_000, 0)
			.saturating_add(Weight::from_parts(0, 3834))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `SupportedChains::SupportedChains` (r:1 w:0)
	/// Proof: `SupportedChains::SupportedChains` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::AttestationCheckpointInterval` (r:0 w:1)
	/// Proof: `Attestation::AttestationCheckpointInterval` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_attestations_per_checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `369`
		//  Estimated: `3834`
		// Minimum execution time: 27_110_000 picoseconds.
		Weight::from_parts(29_970_000, 0)
			.saturating_add(Weight::from_parts(0, 3834))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `SupportedChains::SupportedChains` (r:1 w:0)
	/// Proof: `SupportedChains::SupportedChains` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::PendingMaxCatchup` (r:0 w:1)
	/// Proof: `Attestation::PendingMaxCatchup` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_max_catchup() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `369`
		//  Estimated: `3834`
		// Minimum execution time: 27_330_000 picoseconds.
		Weight::from_parts(28_020_000, 0)
			.saturating_add(Weight::from_parts(0, 3834))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `SupportedChains::SupportedChains` (r:1 w:0)
	/// Proof: `SupportedChains::SupportedChains` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::PendingTargetSampleSize` (r:0 w:1)
	/// Proof: `Attestation::PendingTargetSampleSize` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_target_sample_size() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `369`
		//  Estimated: `3834`
		// Minimum execution time: 26_409_000 picoseconds.
		Weight::from_parts(28_480_000, 0)
			.saturating_add(Weight::from_parts(0, 3834))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `SupportedChains::SupportedChains` (r:1 w:0)
	/// Proof: `SupportedChains::SupportedChains` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::ChainElectionPolicy` (r:1 w:0)
	/// Proof: `Attestation::ChainElectionPolicy` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::Attestors` (r:1 w:1)
	/// Proof: `Attestation::Attestors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::RetiredAttestorBlsKeys` (r:1 w:1)
	/// Proof: `Attestation::RetiredAttestorBlsKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::RetiredAttestorKeysByStash` (r:1 w:1)
	/// Proof: `Attestation::RetiredAttestorKeysByStash` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::BlsKeyOwner` (r:1 w:1)
	/// Proof: `Attestation::BlsKeyOwner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::AttestorsCount` (r:1 w:1)
	/// Proof: `Attestation::AttestorsCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::MaxAttestors` (r:1 w:0)
	/// Proof: `Attestation::MaxAttestors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Attestation::MinBondRequirement` (r:1 w:0)
	/// Proof: `Attestation::MinBondRequirement` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::TotalIssuance` (r:1 w:0)
	/// Proof: `Balances::TotalIssuance` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::Ledger` (r:1 w:1)
	/// Proof: `Attestation::Ledger` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	fn register_attestor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2111`
		//  Estimated: `6196`
		// Minimum execution time: 246_457_000 picoseconds.
		Weight::from_parts(261_299_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(19))
			.saturating_add(T::DbWeight::get().writes(11))
	}
	/// Storage: `Attestation::Attestors` (r:1 w:1)
	/// Proof: `Attestation::Attestors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::MinBondRequirement` (r:1 w:0)
	/// Proof: `Attestation::MinBondRequirement` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::Ledger` (r:1 w:1)
	/// Proof: `Attestation::Ledger` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Staking::CurrentEra` (r:1 w:0)
	/// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::RetiredAttestorKeysByStash` (r:1 w:1)
	/// Proof: `Attestation::RetiredAttestorKeysByStash` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::ActiveAttestors` (r:1 w:1)
	/// Proof: `Attestation::ActiveAttestors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::AttestorsCount` (r:1 w:1)
	/// Proof: `Attestation::AttestorsCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::RetiredAttestorBlsKeys` (r:0 w:1)
	/// Proof: `Attestation::RetiredAttestorBlsKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn unregister_attestor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1581`
		//  Estimated: `5046`
		// Minimum execution time: 125_139_000 picoseconds.
		Weight::from_parts(140_048_000, 0)
			.saturating_add(Weight::from_parts(0, 5046))
			.saturating_add(T::DbWeight::get().reads(14))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `SupportedChains::SupportedChains` (r:1 w:0)
	/// Proof: `SupportedChains::SupportedChains` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::MaxAttestors` (r:0 w:1)
	/// Proof: `Attestation::MaxAttestors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_max_attestors() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `369`
		//  Estimated: `3834`
		// Minimum execution time: 27_490_000 picoseconds.
		Weight::from_parts(29_820_000, 0)
			.saturating_add(Weight::from_parts(0, 3834))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Attestation::Invulnerables` (r:1 w:1)
	/// Proof: `Attestation::Invulnerables` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::MaxInvulnerables` (r:1 w:0)
	/// Proof: `Attestation::MaxInvulnerables` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn register_invulnerable() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `308`
		//  Estimated: `3773`
		// Minimum execution time: 34_269_000 picoseconds.
		Weight::from_parts(36_380_000, 0)
			.saturating_add(Weight::from_parts(0, 3773))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Attestation::Invulnerables` (r:1 w:1)
	/// Proof: `Attestation::Invulnerables` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn unregister_invulnerable() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `249`
		//  Estimated: `3714`
		// Minimum execution time: 25_990_000 picoseconds.
		Weight::from_parts(29_150_000, 0)
			.saturating_add(Weight::from_parts(0, 3714))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Attestation::Invulnerables` (r:1 w:0)
	/// Proof: `Attestation::Invulnerables` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::MaxInvulnerables` (r:0 w:1)
	/// Proof: `Attestation::MaxInvulnerables` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_max_invulnerables() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `288`
		//  Estimated: `3753`
		// Minimum execution time: 14_159_000 picoseconds.
		Weight::from_parts(15_780_000, 0)
			.saturating_add(Weight::from_parts(0, 3753))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Attestation::ActiveAttestors` (r:1 w:0)
	/// Proof: `Attestation::ActiveAttestors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SupportedChains::SupportedChains` (r:1 w:0)
	/// Proof: `SupportedChains::SupportedChains` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::Attestations` (r:2 w:1)
	/// Proof: `Attestation::Attestations` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::LastCheckpoint` (r:1 w:1)
	/// Proof: `Attestation::LastCheckpoint` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::TargetSampleSize` (r:1 w:0)
	/// Proof: `Attestation::TargetSampleSize` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::Attestors` (r:100 w:0)
	/// Proof: `Attestation::Attestors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::RetiredAttestorBlsKeys` (r:100 w:0)
	/// Proof: `Attestation::RetiredAttestorBlsKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::AttestationChainGenesisBlockNumber` (r:1 w:0)
	/// Proof: `Attestation::AttestationChainGenesisBlockNumber` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::LastDigest` (r:1 w:1)
	/// Proof: `Attestation::LastDigest` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::Checkpoints` (r:2 w:5)
	/// Proof: `Attestation::Checkpoints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::ChainAttestationInterval` (r:1 w:0)
	/// Proof: `Attestation::ChainAttestationInterval` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::AttestationCheckpointInterval` (r:1 w:0)
	/// Proof: `Attestation::AttestationCheckpointInterval` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::CheckpointingQueues` (r:1 w:1)
	/// Proof: `Attestation::CheckpointingQueues` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::AttestationRemovalQueues` (r:1 w:1)
	/// Proof: `Attestation::AttestationRemovalQueues` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::AttestationRetentionDuration` (r:1 w:0)
	/// Proof: `Attestation::AttestationRetentionDuration` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::CheckpointBuckets` (r:0 w:5)
	/// Proof: `Attestation::CheckpointBuckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `s` is `[10, 500]`.
	/// The range of component `m` is `[1, 99]`.
	/// The range of component `s` is `[10, 500]`.
	/// The range of component `m` is `[1, 99]`.
	fn commit_attestation(s: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1972 + m * (202 ±0)`
		//  Estimated: `7912 + m * (2678 ±0) + s * (11 ±0)`
		// Minimum execution time: 47_685_094_000 picoseconds.
		Weight::from_parts(42_150_459_099, 0)
			.saturating_add(Weight::from_parts(0, 7912))
			// Standard Error: 3_089_900
			.saturating_add(Weight::from_parts(6_932_858, 0).saturating_mul(s.into()))
			// Standard Error: 15_449_502
			.saturating_add(Weight::from_parts(2_309_881_813, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(19))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().writes(5))
			.saturating_add(Weight::from_parts(0, 2678).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 11).saturating_mul(s.into()))
	}
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::MinBondRequirement` (r:0 w:1)
	/// Proof: `Attestation::MinBondRequirement` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_min_bond_requirement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `20`
		//  Estimated: `1505`
		// Minimum execution time: 17_450_000 picoseconds.
		Weight::from_parts(20_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1505))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Attestation::Attestors` (r:1 w:1)
	/// Proof: `Attestation::Attestors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::BlsKeyOwner` (r:1 w:1)
	/// Proof: `Attestation::BlsKeyOwner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn attest() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `334`
		//  Estimated: `3799`
		// Minimum execution time: 43_899_826_000 picoseconds.
		Weight::from_parts(43_977_166_000, 0)
			.saturating_add(Weight::from_parts(0, 3799))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Attestation::Attestors` (r:1 w:1)
	/// Proof: `Attestation::Attestors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::ActiveAttestors` (r:1 w:1)
	/// Proof: `Attestation::ActiveAttestors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn chill() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `416`
		//  Estimated: `3881`
		// Minimum execution time: 37_360_000 picoseconds.
		Weight::from_parts(44_680_000, 0)
			.saturating_add(Weight::from_parts(0, 3881))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Attestation::Ledger` (r:1 w:1)
	/// Proof: `Attestation::Ledger` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Staking::CurrentEra` (r:1 w:0)
	/// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Attestation::RetiredAttestorKeysByStash` (r:1 w:1)
	/// Proof: `Attestation::RetiredAttestorKeysByStash` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::RetiredAttestorBlsKeys` (r:1 w:0)
	/// Proof: `Attestation::RetiredAttestorBlsKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn withdraw_unbonded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1612`
		//  Estimated: `5077`
		// Minimum execution time: 84_990_000 picoseconds.
		Weight::from_parts(96_850_000, 0)
			.saturating_add(Weight::from_parts(0, 5077))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `SupportedChains::SupportedChains` (r:1 w:0)
	/// Proof: `SupportedChains::SupportedChains` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::LastDigest` (r:1 w:0)
	/// Proof: `Attestation::LastDigest` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::LastCheckpoint` (r:1 w:1)
	/// Proof: `Attestation::LastCheckpoint` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::Checkpoints` (r:100 w:100)
	/// Proof: `Attestation::Checkpoints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::CheckpointBuckets` (r:0 w:100)
	/// Proof: `Attestation::CheckpointBuckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn import_checkpoints() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `249147`
		// Minimum execution time: 1_413_764_000 picoseconds.
		Weight::from_parts(1_442_957_000, 0)
			.saturating_add(Weight::from_parts(0, 249147))
			.saturating_add(T::DbWeight::get().reads(107))
			.saturating_add(T::DbWeight::get().writes(203))
	}
	/// Storage: `SupportedChains::SupportedChains` (r:1 w:0)
	/// Proof: `SupportedChains::SupportedChains` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::CheckpointPruningStates` (r:1 w:0)
	/// Proof: `Attestation::CheckpointPruningStates` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::CheckpointClearingCursors` (r:1 w:0)
	/// Proof: `Attestation::CheckpointClearingCursors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::BucketClearingCursors` (r:1 w:0)
	/// Proof: `Attestation::BucketClearingCursors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::LastCheckpoint` (r:1 w:1)
	/// Proof: `Attestation::LastCheckpoint` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::Checkpoints` (r:0 w:100)
	/// Proof: `Attestation::Checkpoints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::AttestationRemovalQueues` (r:0 w:1)
	/// Proof: `Attestation::AttestationRemovalQueues` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::CheckpointBuckets` (r:0 w:100)
	/// Proof: `Attestation::CheckpointBuckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::LastDigest` (r:0 w:1)
	/// Proof: `Attestation::LastDigest` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::CheckpointingQueues` (r:0 w:1)
	/// Proof: `Attestation::CheckpointingQueues` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn forward_patch_checkpoints() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `4122`
		// Minimum execution time: 1_216_904_000 picoseconds.
		Weight::from_parts(1_233_427_000, 0)
			.saturating_add(Weight::from_parts(0, 4122))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(206))
	}
	/// Storage: `SupportedChains::SupportedChains` (r:1 w:0)
	/// Proof: `SupportedChains::SupportedChains` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::Attestations` (r:1 w:0)
	/// Proof: `Attestation::Attestations` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::Checkpoints` (r:1 w:0)
	/// Proof: `Attestation::Checkpoints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::AttestationChainGenesisBlockNumber` (r:0 w:1)
	/// Proof: `Attestation::AttestationChainGenesisBlockNumber` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_attestation_chain_genesis_block_number() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `830`
		//  Estimated: `4295`
		// Minimum execution time: 41_290_000 picoseconds.
		Weight::from_parts(43_210_000, 0)
			.saturating_add(Weight::from_parts(0, 4295))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `SupportedChains::SupportedChains` (r:1 w:0)
	/// Proof: `SupportedChains::SupportedChains` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::ChainElectionPolicy` (r:0 w:1)
	/// Proof: `Attestation::ChainElectionPolicy` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_election_policy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `369`
		//  Estimated: `3834`
		// Minimum execution time: 26_950_000 picoseconds.
		Weight::from_parts(27_890_000, 0)
			.saturating_add(Weight::from_parts(0, 3834))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `SupportedChains::SupportedChains` (r:1 w:0)
	/// Proof: `SupportedChains::SupportedChains` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::AuthorizedAttestors` (r:1 w:1)
	/// Proof: `Attestation::AuthorizedAttestors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn authorize_attestor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `4122`
		// Minimum execution time: 41_030_000 picoseconds.
		Weight::from_parts(43_160_000, 0)
			.saturating_add(Weight::from_parts(0, 4122))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Attestation::AuthorizedAttestors` (r:1 w:1)
	/// Proof: `Attestation::AuthorizedAttestors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn remove_authorized_attestor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `305`
		//  Estimated: `3770`
		// Minimum execution time: 30_040_000 picoseconds.
		Weight::from_parts(31_010_000, 0)
			.saturating_add(Weight::from_parts(0, 3770))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Attestation::Attestors` (r:1 w:1)
	/// Proof: `Attestation::Attestors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::ActiveAttestors` (r:1 w:1)
	/// Proof: `Attestation::ActiveAttestors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::MinBondRequirement` (r:1 w:0)
	/// Proof: `Attestation::MinBondRequirement` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::Ledger` (r:1 w:1)
	/// Proof: `Attestation::Ledger` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Staking::CurrentEra` (r:1 w:0)
	/// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Attestation::AttestorsCount` (r:1 w:1)
	/// Proof: `Attestation::AttestorsCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn kick_active_attestor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1450`
		//  Estimated: `4915`
		// Minimum execution time: 123_929_000 picoseconds.
		Weight::from_parts(130_809_000, 0)
			.saturating_add(Weight::from_parts(0, 4915))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `SupportedChains::SupportedChains` (r:7 w:0)
	/// Proof: `SupportedChains::SupportedChains` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::ChainElectionPolicy` (r:6 w:0)
	/// Proof: `Attestation::ChainElectionPolicy` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::Attestors` (r:11 w:5)
	/// Proof: `Attestation::Attestors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::ActiveAttestors` (r:0 w:1)
	/// Proof: `Attestation::ActiveAttestors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_election() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1645`
		//  Estimated: `29860`
		// Minimum execution time: 204_979_000 picoseconds.
		Weight::from_parts(221_069_000, 0)
			.saturating_add(Weight::from_parts(0, 29860))
			.saturating_add(T::DbWeight::get().reads(28))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `Attestation::PendingAttestationInterval` (r:2 w:1)
	/// Proof: `Attestation::PendingAttestationInterval` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::PendingTargetSampleSize` (r:2 w:1)
	/// Proof: `Attestation::PendingTargetSampleSize` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::PendingMaxCatchup` (r:2 w:1)
	/// Proof: `Attestation::PendingMaxCatchup` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::ChainAttestationInterval` (r:0 w:1)
	/// Proof: `Attestation::ChainAttestationInterval` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::MaxCatchup` (r:0 w:1)
	/// Proof: `Attestation::MaxCatchup` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::TargetSampleSize` (r:0 w:1)
	/// Proof: `Attestation::TargetSampleSize` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_apply_updates() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `449`
		//  Estimated: `6389`
		// Minimum execution time: 63_970_000 picoseconds.
		Weight::from_parts(66_550_000, 0)
			.saturating_add(Weight::from_parts(0, 6389))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `SupportedChains::SupportedChains` (r:1 w:0)
	/// Proof: `SupportedChains::SupportedChains` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::CheckpointPruningStates` (r:1 w:1)
	/// Proof: `Attestation::CheckpointPruningStates` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::AttestationRetentionDuration` (r:1 w:0)
	/// Proof: `Attestation::AttestationRetentionDuration` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::AttestationCheckpointInterval` (r:1 w:0)
	/// Proof: `Attestation::AttestationCheckpointInterval` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::Attestations` (r:239 w:239)
	/// Proof: `Attestation::Attestations` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::Checkpoints` (r:1 w:499)
	/// Proof: `Attestation::Checkpoints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::CheckpointBuckets` (r:500 w:499)
	/// Proof: `Attestation::CheckpointBuckets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::LastCheckpoint` (r:1 w:1)
	/// Proof: `Attestation::LastCheckpoint` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::AttestationRemovalQueues` (r:0 w:1)
	/// Proof: `Attestation::AttestationRemovalQueues` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::LastDigest` (r:0 w:1)
	/// Proof: `Attestation::LastDigest` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::CheckpointingQueues` (r:0 w:1)
	/// Proof: `Attestation::CheckpointingQueues` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn revert_to() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `36540`
		//  Estimated: `1275030`
		// Minimum execution time: 5_568_597_000 picoseconds.
		Weight::from_parts(5_602_161_000, 0)
			.saturating_add(Weight::from_parts(0, 1275030))
			.saturating_add(T::DbWeight::get().reads(749))
			.saturating_add(T::DbWeight::get().writes(1244))
	}
}
