---
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"
    groups:
      all-dependencies:
        dependency-type: "production"
        applies-to: version-updates

  # Maintain dependencies for Docker images
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/cc3-indexer"
      - "/cc3-indexer/postgres"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"
    groups:
      all-dependencies:
        dependency-type: "production"
        applies-to: version-updates

  # Maintain dependencies for docker-compose files
  - package-ecosystem: "docker-compose"
    directories:
      - "/"
      - "/cc3-indexer"
      - "/prover"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"
    groups:
      all-dependencies:
        dependency-type: "production"
        applies-to: version-updates

  # Maintain dependencies for Rust
  # Note: Dependabot can't recursively search directories at the moment
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/attestor"
      - "/attestor_zombienet"
      - "/block-cache"
      - "/client/attestor-gossip"
      - "/client/attestor-rpc"
      - "/common/bls-signatures"
      - "/common/cc-client"
      - "/common/eth"
      - "/common/mmr"
      - "/common/utils"
      - "/common/vrf"
      - "/host"
      - "/node"
      - "/node/cli-opt"
      - "/pallets/attestation-poc"
      - "/pallets/prover"
      - "/pallets/randomness"
      - "/pallets/supported-chains"
      - "/precompiles/proof-verifier"
      - "/precompiles/substrate-transfer"
      - "/primitives/account"
      - "/primitives/attestation_chain"
      - "/primitives/attestor"
      - "/primitives/core"
      - "/primitives/pallet-prover"
      - "/primitives/prover"
      - "/primitives/randomness"
      - "/primitives/supported-chains"
      - "/proof"
      - "/prover"
      - "/query-cli"
      - "/runtime"
      - "/runtime/generate-bags"
    groups:
      prod-dependencies:
        dependency-type: "production"
        applies-to: version-updates
      dev-dependencies:
        dependency-type: "development"
        applies-to: version-updates
    schedule:
      interval: "monthly"

  # Maintain dependencies for Node.js
  - package-ecosystem: "npm"
    directories:
      - "/attestor/scripts"
      - "/cc3-indexer"
      - "/cli"
      - "/docs/smart-contract-development/with-hardhat"
      - "/docs/smart-contract-development/with-ethers.js"
      - "/testing"
    groups:
      prod-dependencies:
        dependency-type: "production"
        applies-to: version-updates
      dev-dependencies:
        dependency-type: "development"
        applies-to: version-updates
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Maintain dependencies for Cairo and Python
  - package-ecosystem: "pip"
    directories:
      - "/prover"
    groups:
      prod-dependencies:
        dependency-type: "production"
        applies-to: version-updates
    schedule:
      interval: "monthly"

  # Python dependencies for Linode
  - package-ecosystem: "pip"
    directories:
      - "/.github"
    groups:
      linode-dependencies:
        dependency-type: "production"
        applies-to: version-updates
    schedule:
      interval: "monthly"
