---
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"
    groups:
      all-dependencies:
        dependency-type: "production"
        applies-to: version-updates

  # Maintain dependencies for Docker images
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/cc3-indexer"
      - "/cc3-indexer/postgres"
      - "/proof-gen-api-server"
      - "/scripts/stress-test"
      - "/scripts/traffic-simulator"
      - "/scripts/usc-audit-automation"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"
    groups:
      all-dependencies:
        dependency-type: "production"
        applies-to: version-updates

  # Maintain dependencies for docker-compose files
  - package-ecosystem: "docker-compose"
    directories:
      - "/"
      - "/cc3-indexer"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"
    groups:
      docker-compose:
        dependency-type: "production"
        applies-to: version-updates

  # Maintain dependencies for Rust
  # Note: Dependabot can't recursively search directories at the moment
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/attestor/attestor"
      - "/attestor/attestor_zombienet"
      - "/common/cc-client"
      - "/common/continuity"
      - "/common/eth"
      - "/common/merkle"
      - "/common/utils"
      - "/common/vrf"
      - "/common/prometheus"
      - "/common/indexer-client"
      - "/common/builder"
      - "/common/streams/eth"
      - "/common/streams/attestation"
      - "/common/streams/util"
      - "/common/streams/stream"
      - "/node"
      - "/node/cli-opt"
      - "/pallets/attestation"
      - "/pallets/randomness"
      - "/pallets/supported-chains"
      - "/precompiles/chain-info"
      - "/precompiles/block-prover"
      - "/precompiles/substrate-transfer"
      - "/precompiles/signature-verifier"
      - "/proof-gen-api-server"
      - "/primitives/account"
      - "/primitives/attestor"
      - "/primitives/core"
      - "/primitives/randomness"
      - "/primitives/supported-chains"
      - "/primitives/user"
      - "/query-cli"
      - "/runtime"
      - "/runtime/generate-bags"
      - "/archiver"
    groups:
      prod-dependencies:
        dependency-type: "production"
        applies-to: version-updates
      dev-dependencies:
        dependency-type: "development"
        applies-to: version-updates
    schedule:
      interval: "monthly"

  # Maintain dependencies for Node.js
  - package-ecosystem: "npm"
    directories:
      - "/attestor/scripts"
      - "/cc3-indexer"
      - "/cli"
      - "/common/eth/contracts"
      - "/common/eth/contracts/get-contract-state"
      - "/docs/smart-contract-development/with-hardhat"
      - "/docs/smart-contract-development/with-ethers.js"
      - "/scripts"
      - "/scripts/changelog-warnings"
    groups:
      prod-dependencies:
        dependency-type: "production"
        applies-to: version-updates
      dev-dependencies:
        dependency-type: "development"
        applies-to: version-updates
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Python dependencies for Linode
  - package-ecosystem: "pip"
    directories:
      - "/.github"
    groups:
      linode-dependencies:
        dependency-type: "production"
        applies-to: version-updates
    schedule:
      interval: "monthly"
