#!/usr/bin/env python

#
# WARNING: requires PyGithub>= 2.3.0
#
# pip install PyGithub
#
# API documentation:
# https://pygithub.readthedocs.io

import os
import sys
from collections import Counter
from pprint import pprint

import requests

from datetime import datetime, timedelta
from github import Auth, Github


skip_self_hosted = "--skip-self-hosted".lower() in sys.argv
no_error_logs = "--no-error-logs".lower() in sys.argv
OWNER_REPO=os.environ.get("OWNER_REPO") or input("OWNER_REPO:")
PERIOD_START=datetime(2025, 1, 1, 0, 0, 0)
PERIOD_END=datetime(2025, 1, 31, 23, 59, 59)
DURATION_PER_JOB={}
DURATION_PER_BRANCH={}
JOB_FAILURES={}
FAILED_JOBS_COUNTER=Counter()
ANNOTATIONS_COUNTER=Counter()


def logs_from_step(cookie, repo, job, step, end_line, back_track = 5):
    url = f"{repo.html_url}/commit/{job.head_sha}/checks/{job.id}/logs/{step.number}"
    response = requests.get(url, headers={"Cookie": cookie}, allow_redirects=True)

    logs = []
    for line in response.text.split("\n")[end_line - back_track:end_line]:
        # strip leading timestamps
        line = " ".join(line.split(" ")[1:])
        logs.append(line)
    return "\n".join(logs)


# Provide the GITHUB_TOKEN ENV variable to work around
# API request limits for anonymous users
auth = None
token = os.environ.get("GITHUB_TOKEN") or input("GITHUB_TOKEN:")
BROWSER_COOKIE = input("Browser Cookie for Step Log calls:")
if token:
    auth = Auth.Token(token)

gh = Github(auth=auth, per_page=100)
repo = gh.get_repo(OWNER_REPO)

# WARNING: this API will return at most 1000 records eventhough there are more
# during certain time periods. To workaround this limitation we query the data
# day-by-day iteratively and at the end use the value of total_workflows as a
# sanity check to make sure we've counted everything. See
# https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-repository
start_str = PERIOD_START.strftime("%Y-%m-%d")
end_str = PERIOD_END.strftime("%Y-%m-%d")
# the numner itself is correct, but pagination results are limited to 1000
total_workflows = repo.get_workflow_runs(created=f"{start_str}..{end_str}").totalCount
total_failures = 0

# iterate over all workflow runs
start = PERIOD_START
inspected_workflows = 0
number_of_jobs = 0
overall_duration = timedelta(seconds=0)
while start <= PERIOD_END:
    # only search within the span of a single day, 24 hrs
    start_str = start.strftime("%Y-%m-%dT00:00:00+00:00")
    end_str = start.strftime("%Y-%m-%dT23:59:59+00:00")

    # NOTE: iterating over the results takes care of pagination internally
    for workflow_run in repo.get_workflow_runs(created=f"{start_str}..{end_str}"):
        inspected_workflows += 1

        # GitHub API doesn't support filtering by name so iterate over all jobs in a workflow
        # https://docs.github.com/en/rest/actions/workflow-jobs?apiVersion=2022-11-28#list-jobs-for-a-workflow-run
        for job in workflow_run.jobs():
            if skip_self_hosted and "self-hosted" in job.labels:
                continue
            else:
                # skip jobs which are still running
                if job.completed_at is None:
                    continue

                if job.conclusion in ["failure"]:
                    # note: check run & job IDs appear to match
                    check_run = repo.get_check_run(job.id)
                    annotation = None
                    for annotation in check_run.get_annotations():
                        if annotation.annotation_level != "failure":
                            continue

                        # WARNING: annotation.title is always empty b/c this API needs a GitHub App token
                        # that's why we try to workaround this by using the name of the first failing step
                        for step in job.steps:
                            if step.conclusion == "failure":
                                annotation._title = annotation._makeStringAttribute(step.name)
                                break

                        error_log = None
                        if not no_error_logs:
                            error_log = logs_from_step(BROWSER_COOKIE, repo, job, step, annotation.end_line)

                    total_failures += 1
                    if job.name not in JOB_FAILURES:
                        JOB_FAILURES[job.name] = {}
                    if job.head_branch not in JOB_FAILURES[job.name]:
                        JOB_FAILURES[job.name][job.head_branch] = {}
                    if annotation:
                        if annotation.title not in JOB_FAILURES[job.name][job.head_branch]:
                            JOB_FAILURES[job.name][job.head_branch][annotation.title] = []
                        JOB_FAILURES[job.name][job.head_branch][annotation.title].append((job.html_url, annotation.message, error_log))
                        ANNOTATIONS_COUNTER.update([annotation.title])

                    FAILED_JOBS_COUNTER.update([job.name])

                duration = job.completed_at - job.started_at

                # TODO: should account for minute multipliers on Windows and MacOS
                # mainly for release workflows if we keep these private, see
                # https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#minute-multipliers

                overall_duration += duration
                number_of_jobs += 1

                # skip accumulating jobs which took no time
                if duration == timedelta(seconds=0):
                    continue

                print(
                    gh.rate_limiting,
                    f"W: {workflow_run.id} @ {workflow_run.created_at} "
                    f"J: {job.id} ",
                    job.conclusion,
                    job.name,
                    duration,
                    job.labels,
                    job.head_branch,
                )

                name = job.name.split(" ")[0]
                if name not in DURATION_PER_JOB:
                    DURATION_PER_JOB[name] = timedelta(seconds=0)
                DURATION_PER_JOB[name] += duration

                branch = job.head_branch.split("/")[0]
                if branch not in DURATION_PER_BRANCH:
                    DURATION_PER_BRANCH[branch] = timedelta(seconds=0)
                DURATION_PER_BRANCH[branch] += duration

    start += timedelta(days=1)

print(f"From: {PERIOD_START}")
print(f"To  : {PERIOD_END}")
print(f"Total workflow runs: {inspected_workflows} / {total_workflows}")
print(f"Number of jobs: {number_of_jobs}")
print(f"Overall duration: {overall_duration.total_seconds()} seconds")
print(f"Overall duration: {overall_duration.total_seconds() / 60} minutes")
print(f"Overall duration: {overall_duration.total_seconds() / 3600} hours")

print("================================================================")
print("========== Duration per job (in minutes), Low -> High ==========")
for job_name, duration in sorted(DURATION_PER_JOB.items(), key=lambda x: x[1]):
    print(job_name, duration.total_seconds() / 60)

print("====================================================================")
print("========== Duration per branch prefix (mins), Low -> High ==========")
for branch_name, duration in sorted(DURATION_PER_BRANCH.items(), key=lambda x: x[1]):
    print(branch_name, duration.total_seconds() / 60)

print("====================================================================")
print("========== Failed CI jobs ==========")
print(f"Number of failures: {total_failures} / {number_of_jobs} == {total_failures / number_of_jobs:.2%}")
print("--- Most commonly failing jobs")
print(FAILED_JOBS_COUNTER.most_common())
print("--- Most common annotations")
print(ANNOTATIONS_COUNTER.most_common())
print("--- Failed jobs")
for job_name, _count in FAILED_JOBS_COUNTER.most_common():
    pprint(JOB_FAILURES[job_name])

if inspected_workflows != total_workflows:
    raise RuntimeError("Failed to inspect all workflows")
