[toolchain]
channel    = "1.75.0" # rustc 1.75.0 (82e1608df 2023-12-21)
components = ["cargo", "clippy", "rustc", "rustfmt", "rust-src"]
profile    = "minimal"
targets    = ["wasm32-unknown-unknown"]
