[toolchain]
channel = "1.81.0"                                               # rustc 1.81.0 (eeb90cda1 2024-09-04)
components = ["cargo", "clippy", "rustc", "rustfmt", "rust-src"]
profile = "minimal"
targets = ["wasm32-unknown-unknown"]
