[toolchain]
channel    = "1.73.0" # rust version 1.73.0 (cc66ad468 2023-10-03)
components = ["cargo", "clippy", "rustc", "rustfmt", "rust-src"]
profile    = "minimal"
targets    = ["wasm32-unknown-unknown"]
