[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib", "node_modules"]
solc = "0.8.29"
optimizer = true
optimizer_runs = 200

remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "forge-std/=lib/forge-std/src/",
]

[fmt]
line_length = 100
