{
 "title": "Attestor Metrics Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus data source", "query": "prometheus" },
   { "name": "job", "label": "Select Attestor Job", "query": "label_values(up, job)" },
   { "name": "instance", "label": "Select Attestor Instance", "query": "label_values(up, instance)" },
   {
    "name": "chain_key",
    "query": {
     "query": "label_values(cc_current_epoch, chain_key)"
    }
   },
   {
    "name": "cc3next",
    "label": "Select CC3Next RPC URL",
    "query": {
     "query": "label_values(cc3next_rpc_url,cc3next_rpc_url)"
    }
   },
   {
    "name": "source_chain",
    "label": "Select Source Chain RPC URL",
    "query": {
     "query": "label_values(source_chain_rpc_url,source_chain_rpc_url)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Attestor Chain Connection Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Chain Key",
   "type": "stat",
   "description": "Attestor Chain Key",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cc3next_rpc_url{chain_key=~\"$chain_key\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CC3Next RPC URL",
   "type": "stat",
   "description": "Attestor CC3Next RPC URL",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cc3next_rpc_url{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Source Chain RPC URL",
   "type": "stat",
   "description": "Attestor Sourche Chain RPC URL",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "source_chain_rpc_url{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Attestor Metrics (Gauge)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Current Epoch",
   "type": "gauge",
   "description": "The current epoch of cc3 the attestor has reached.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cc_current_epoch{chain_key=~\"$chain_key\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Source Chain Height",
   "type": "gauge",
   "description": "The height of the source chain.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "source_chain_height{chain_key=~\"$chain_key\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Block Voted For",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_block_voted_for{chain_key=~\"$chain_key\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Finalized Attestation",
   "type": "gauge",
   "description": "The last finalized attestation of the attestor.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_finalized_attestation{chain_key=~\"$chain_key\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Attestor Metrics (Time Series)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Current Epoch",
   "type": "timeseries",
   "description": "Attestor Current Epoch",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "cc_current_epoch{chain_key=~\"$chain_key\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Source Chain Height",
   "type": "timeseries",
   "description": "Attestor Source Chain Height",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "source_chain_height{chain_key=~\"$chain_key\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Block Voted For",
   "type": "timeseries",
   "description": "Attestor Last Block Voted For",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "last_block_voted_for{chain_key=~\"$chain_key\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last FInalized Attestation",
   "type": "timeseries",
   "description": "Attestor Last FInalized Attestation",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "last_finalized_attestation{chain_key=~\"$chain_key\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}