
//! Autogenerated weights for `pallet_attestation_poc`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-07-19, STEPS: `50`, REPEAT: `30`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Bradleys-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/creditcoin3-node
// benchmark
// pallet
// --chain
// dev
// --steps=50
// --repeat=30
// --pallet
// pallet_attestation-poc
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=10000
// --output
// ./pallets/attestation-poc/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_attestation_poc`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
	/// Storage: `Attestation::SupportedChains` (r:1 w:1)
	/// Proof: `Attestation::SupportedChains` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Attestation::ChainAttestationInterval` (r:0 w:1)
	/// Proof: `Attestation::ChainAttestationInterval` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_supported_chain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `218`
		//  Estimated: `1703`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1703))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	fn unregister_attestor() -> Weight {
		Weight::MAX
	}
	fn register_attestor() -> Weight {
		Weight::MAX
	}
    fn set_max_attestors() -> Weight {
		Weight::MAX
	}
    fn register_invulnerable() -> Weight {
		Weight::MAX
	}
    fn unregister_invulnerable() -> Weight {
		Weight::MAX
	}
    fn set_max_invulnerables() -> Weight {
		Weight::MAX
	}
    fn attest_block() -> Weight {
		Weight::MAX
	}
    fn bootstrap_chain() -> Weight {
		Weight::MAX
	}
    fn commit_attestation() -> Weight {
		Weight::MAX
	}
    fn set_comittee_set_size() -> Weight {
		Weight::MAX
	}
    fn remove_supported_chain() -> Weight {
		Weight::MAX
	}
}
