services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    env_file:
      - .env.docker
    restart: always

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 81:8080
    depends_on:
      - postgres
