[[chain]]
rpc_url = "ws://localhost:8545"
chain_id = 31337
price = 100

# [[chain]]
# rpc_url = "https://example2.com"
# chain_id = 2
# price = 2000

# [[chain]]
# rpc_url = "https://example3.com"
# chain_id = 3
# price = 3000
