{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus data source", "query": "prometheus" },
   { "name": "job", "label": "Select Prover Job", "query": "label_values(up, job)" },
   { "name": "instance", "label": "Select Prover Instance", "query": "label_values(up, instance)" },
   {
    "name": "chain_key",
    "query": {
     "query": "label_values(number_of_query_proofs_submitted,chain_key)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Prover Chain Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Chain Key",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prover_chain_key{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Prover Metrics (Gauge)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Attestation Network Height",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "attestation_network_height{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Queries Received",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "number_of_queries_received{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Query Proofs Submitted",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "number_of_query_proofs_submitted{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Query Proofs Failed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "number_of_query_proofs_failed{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Prover Metrics (Time Series)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Attestation Network Height",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "attestation_network_height{chain_key=\"$chain_key\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Queries Received",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "expr": "number_of_queries_received{chain_key=\"$chain_key\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Query Proofs Submitted",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "number_of_query_proofs_submitted{chain_key=\"$chain_key\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Query Proofs Failed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "expr": "number_of_query_proofs_failed{chain_key=\"$chain_key\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}