use crate::{
    attestation_check_result::compute_attestation_check_result,
    attestation_checks::{get_attestor_latest_attestation_data, get_ethereum_current_block_number},
    calculate_merkle_root, calculate_usc_and_source_chain_block_diff,
    create_json_message::create_json_message,
    AttestationCheckpointChainNode, AttestationNode, CheckpointCreatedWithinRangeResult,
    GraphQLAttestationCheckResult, MockEthereumProvider, SupportedChainInfo,
    UniversalSmartContractProvider,
};
use anyhow::Result;
use attestor_primitives::{AttestationCheckpoint, SignedAttestation};
use eth::OrderedBlock;
use ethers::types::U64;
use hex_literal::hex;
use mockall::predicate::*;
use serde_json::json;
use sp_core::H256;
use std::sync::Arc;
use subxt::utils::AccountId32;

pub struct MockUscRpcClientOk;

impl MockUscRpcClientOk {
    pub fn new() -> Self {
        MockUscRpcClientOk
    }
}
impl UniversalSmartContractProvider for MockUscRpcClientOk {
    async fn fetch_last_digest(&self, _chain_key: u64) -> Result<Option<H256>> {
        Ok(Some(H256::from_slice(&[0u8; 32])))
    }

    async fn get_attestation_by_digest(
        &self,
        _chain_key: u64,
        _digest: H256,
    ) -> Result<Option<SignedAttestation<H256, AccountId32>>> {
        Ok(Some(SignedAttestation {
            attestation: attestor_primitives::Attestation {
                chain_key: 2,
                header_number: 123,
                header_hash: H256::from_slice(&[0u8; 32]),
                root: hex!("736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"),
                prev_digest: None,
            },
            signature: [0u8; 96],
            attestors: vec![],
        }))
    }
    async fn get_attestation_interval(&self, _chain_key: u64) -> Result<Option<u64>> {
        Ok(Some(5))
    }
    async fn get_checkpoint_interval(&self, _chain_key: u64) -> Result<Option<u32>> {
        Ok(Some(10))
    }
    async fn get_last_attestation_checkpoint(
        &self,
        _chain_key: u64,
    ) -> Result<Option<AttestationCheckpoint>> {
        Ok(Some(AttestationCheckpoint {
            block_number: 100,
            digest: H256::from_slice(&[0u8; 32]),
        }))
    }
    async fn get_attestation_vote_acceptance_window(&self, _chain_key: u64) -> Result<Option<u64>> {
        Ok(Some(2_u64))
    }
}

struct MockUscRpcClientError;
impl MockUscRpcClientError {
    pub fn new() -> Self {
        MockUscRpcClientError
    }
}

impl UniversalSmartContractProvider for MockUscRpcClientError {
    async fn fetch_last_digest(&self, _chain_key: u64) -> Result<Option<H256>> {
        Ok(None)
    }

    async fn get_attestation_by_digest(
        &self,
        _chain_key: u64,
        _digest: H256,
    ) -> Result<Option<SignedAttestation<H256, AccountId32>>> {
        Ok(None)
    }
    async fn get_attestation_interval(&self, _chain_key: u64) -> Result<Option<u64>> {
        Ok(Some(5_u64))
    }
    async fn get_checkpoint_interval(&self, _chain_key: u64) -> Result<Option<u32>> {
        Ok(Some(10_u32))
    }
    async fn get_last_attestation_checkpoint(
        &self,
        _chain_key: u64,
    ) -> Result<Option<AttestationCheckpoint>> {
        Ok(None)
    }
    async fn get_attestation_vote_acceptance_window(&self, _chain_key: u64) -> Result<Option<u64>> {
        Ok(Some(2_u64))
    }
}

#[tokio::test]
async fn get_attestor_best_block_height_fetches_best_block_correctly() -> Result<()> {
    let client = MockUscRpcClientOk::new();
    let chain_key = 2_u64;

    // Call mock get_attestor_best_block_height
    let signed_attestation = get_attestor_latest_attestation_data(&client, chain_key).await?;
    let expected_best_block = 123_u64;

    assert_eq!(
        expected_best_block,
        signed_attestation.attestation.header_number
    );

    Ok(())
}

#[tokio::test]
async fn get_attestor_best_block_height_returns_an_error_when_no_best_block_found() -> Result<()> {
    let client = MockUscRpcClientError::new();
    let chain_key = 2_u64;

    // Call mock get_attestor_best_block_height
    let result = get_attestor_latest_attestation_data(&client, chain_key).await;

    assert!(result.is_err(), "Expected an error but got Ok");

    let err = result.unwrap_err();
    assert!(
        err.to_string()
            .contains("No last digest found for chain key 2"),
        "Unexpected error: {err}"
    );

    Ok(())
}

#[tokio::test]
async fn get_ethereum_current_block_number_correctly_gets_block_number() -> Result<()> {
    let mut mock = MockEthereumProvider::new(); // generated by mock call

    // Mock ethereum trait return value
    mock.expect_fetch_block_number()
        .times(1)
        .returning(|| Ok(Some(42.into())));

    // Call mock get_ethereum_current_block_number
    let eth_block_number = get_ethereum_current_block_number(&mock).await?;
    let expected_block_number = 42_u64;
    assert_eq!(expected_block_number, eth_block_number);

    Ok(())
}

#[tokio::test]
async fn get_ethereum_current_block_number_correctly_handles_an_error() -> Result<()> {
    let mut mock = MockEthereumProvider::new();

    mock.expect_fetch_block_number()
        .returning(|| Err(anyhow::anyhow!("RPC error: connection dropped")));

    let result = get_ethereum_current_block_number(&mock).await;
    assert!(result.is_err());

    let err = result.unwrap_err();
    assert_eq!(err.to_string(), "failed to get ethereum block number");
    let mut chain = err.chain();
    chain.next();

    let original_error = chain.next().unwrap();
    assert_eq!(original_error.to_string(), "RPC error: connection dropped");

    Ok(())
}

#[test]
fn calculate_usc_and_source_chain_block_diff_returns_a_positive_value_when_source_chain_is_ahead_of_usc_chain(
) {
    let attestor_block_height = 900_020_u64;
    let source_chain_block_height = 900_050_u64;
    let expected_result = 30_i128;

    let result =
        calculate_usc_and_source_chain_block_diff(attestor_block_height, source_chain_block_height);
    assert_eq!(expected_result, result);
}

#[test]
fn calculate_usc_and_source_chain_block_diff_returns_a_negative_value_if_source_chain_is_behind_usc_chain(
) {
    let attestor_block_height = 900_010_u64;
    let source_chain_block_height = 900_000_u64;
    let expected_result = -10_i128;

    let result =
        calculate_usc_and_source_chain_block_diff(attestor_block_height, source_chain_block_height);
    assert_eq!(expected_result, result);
}
#[test]
fn create_message_returns_chain_status_and_group_notification_when_slack_group_is_some_and_block_diff_check_fails(
) {
    let supported_chain_info = SupportedChainInfo {
        chain_id: 1,
        chain_name: "TEST".to_string(),
        chain_key: 2,
    };

    let last_signed_attestation = SignedAttestation {
        attestation: attestor_primitives::Attestation {
            chain_key: 2,
            header_number: 100,
            header_hash: H256::from_slice(&[0u8; 32]),
            root: hex!("736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"),
            prev_digest: Some(H256::from_slice(&[0u8; 32])),
        },
        signature: [0u8; 96],
        attestors: vec![],
        continuity_proof: Default::default(),
    };
    let slack_alert_group = Some("S_TEST_GROUP".to_string());
    let calculated_ethereum_block_merkle_root =
        "736f6d6563616c63756c617465646d65726b6c65000000000000000000000000".to_string();

    let fetched_ethereum_block_number_by_hash = Some(U64::from(100u64));
    let latest_ethereum_block_number = 200_u64;

    let last_checkpoint_block_number = 50;
    let maybe_elected_attestors = Some(vec![
        AccountId32::from([0u8; 32]),
        AccountId32::from([1u8; 32]),
    ]);

    let expected_result = (
        json!({
            "username": "usc-audit-automation",
            "icon_emoji": ":shield:",
            "text": "```\
                [TEST - 1] ⬛ TEST\n\
                ❌ Attestation block heights diff: 100 (200|100)\n\
                ✅ Attestation header hash matches correct Ethereum block: (100|100)\n\
                ✅ Calculated merkle root matches attestation root: (736f6d6563616c63756c617465646d65726b6c65000000000000000000000000|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ✅ Last checkpoint creation is within checkpoint range: 150 (200|50)\n\
                ✅ All signed attestors are elected:  (0|2)\n\
                ✅ Last checkpoint number found in GraphQL: (50|50)\n\
                ✅ Last attestation header number found in GraphQL: (100|100)\n\
                ✅ Last attestation root found in GraphQL: (736f6d6563616c63756c617465646d65726b6c65000000000000000000000000|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ✅ Last attestation prev digest found in GraphQL: (0000000000000000000000000000000000000000000000000000000000000000|0000000000000000000000000000000000000000000000000000000000000000)\n\
                ✅ Last attestation digest found in GraphQL: (02311158238ba841f34895c6496db20167b55b0612b2b628a59c665f918307c9|02311158238ba841f34895c6496db20167b55b0612b2b628a59c665f918307c9)\
                ```"
        }),
        Some(json!({
            "username": "usc-audit-automation",
            "icon_emoji": ":rotating_light:",
            "text": "<!subteam^S_TEST_GROUP> The following issues were detected:\nCurrent block difference exceeds threshold!"
        })),
    );
    let attestation_check_result = compute_attestation_check_result(
        &last_signed_attestation,
        latest_ethereum_block_number,
        calculated_ethereum_block_merkle_root.as_str(),
        fetched_ethereum_block_number_by_hash,
        CheckpointCreatedWithinRangeResult {
            last_checkpoint_block_number,
            latest_ethereum_block_number,
            checkpoint_created_within_range: true,
        },
        maybe_elected_attestors,
        Some(GraphQLAttestationCheckResult {
            checkpoint_chain_node: AttestationCheckpointChainNode {
                checkpoint_number: "50".to_string(),
                last_attested_digest:
                    "00f3cf5a4aac855ea618dcc06abbeb1513bab3bfa8910e99d432bd34e6be0dc2".to_string(),
            },
            attestation_node: AttestationNode {
                header_number: "100".to_string(),
                root: "736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"
                    .to_string(),
                prev_digest: "0000000000000000000000000000000000000000000000000000000000000000"
                    .to_string(),
                digest: "02311158238ba841f34895c6496db20167b55b0612b2b628a59c665f918307c9"
                    .to_string(),
            },
        }),
    );

    let result = create_json_message(
        &supported_chain_info,
        attestation_check_result,
        "TEST",
        &slack_alert_group,
    );

    assert_eq!(expected_result, result);
}

#[test]
fn create_message_returns_chain_status_and_group_notification_when_slack_group_is_some_and_header_hash_check_fails(
) {
    let supported_chain_info = SupportedChainInfo {
        chain_id: 1,
        chain_name: "TEST".to_string(),
        chain_key: 2,
    };

    let last_signed_attestation = SignedAttestation {
        attestation: attestor_primitives::Attestation {
            chain_key: 2,
            header_number: 150, // block diff is 50 (passes)
            header_hash: H256::from_slice(&[0u8; 32]),
            root: hex!("736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"),
            prev_digest: Some(H256::from_slice(&[0u8; 32])),
        },
        signature: [0u8; 96],
        attestors: vec![AccountId32::from([0u8; 32]), AccountId32::from([1u8; 32])],
        continuity_proof: Default::default(),
    };
    let slack_alert_group = Some("S_TEST_GROUP".to_string());
    let calculated_ethereum_block_merkle_root =
        "736f6d6563616c63756c617465646d65726b6c65000000000000000000000000".to_string();

    let fetched_ethereum_block_number_by_hash = Some(U64::from(100u64)); // mismatch: 100 != 150
    let latest_ethereum_block_number = 200_u64;
    let last_checkpoint_block_number = 130;
    let maybe_elected_attestors = Some(vec![
        AccountId32::from([0u8; 32]),
        AccountId32::from([1u8; 32]),
    ]);

    let expected_result = (
        json!({
            "username": "usc-audit-automation",
            "icon_emoji": ":shield:",
            "text": "```\
                [TEST - 1] ⬛ TEST\n\
                ✅ Attestation block heights diff: 50 (200|150)\n\
                ❌ Attestation header hash does not match correct Ethereum block: (100|150)\n\
                ✅ Calculated merkle root matches attestation root: (736f6d6563616c63756c617465646d65726b6c65000000000000000000000000|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ✅ Last checkpoint creation is within checkpoint range: 70 (200|130)\n\
                ✅ All signed attestors are elected:  (2|2)\n\
                ✅ Last checkpoint number found in GraphQL: (130|130)\n\
                ✅ Last attestation header number found in GraphQL: (150|150)\n\
                ✅ Last attestation root found in GraphQL: (736f6d6563616c63756c617465646d65726b6c65000000000000000000000000|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ✅ Last attestation prev digest found in GraphQL: (0000000000000000000000000000000000000000000000000000000000000000|0000000000000000000000000000000000000000000000000000000000000000)\n\
                ✅ Last attestation digest found in GraphQL: (033a4fb6eb4d25411d206b84e4434c7ec6db054fdf0f8281b1cbd17f35dbbce1|033a4fb6eb4d25411d206b84e4434c7ec6db054fdf0f8281b1cbd17f35dbbce1)\
                ```"
        }),
        Some(json!({
            "username": "usc-audit-automation",
            "icon_emoji": ":rotating_light:",
            "text": "<!subteam^S_TEST_GROUP> The following issues were detected:\nAttestation header hash does not match correct Ethereum block!"
        })),
    );

    let attestation_checks_result = compute_attestation_check_result(
        &last_signed_attestation,
        latest_ethereum_block_number,
        calculated_ethereum_block_merkle_root.as_str(),
        fetched_ethereum_block_number_by_hash,
        CheckpointCreatedWithinRangeResult {
            last_checkpoint_block_number,
            latest_ethereum_block_number,
            checkpoint_created_within_range: true, // checkpoint check passes
        },
        maybe_elected_attestors,
        Some(crate::GraphQLAttestationCheckResult {
            checkpoint_chain_node: AttestationCheckpointChainNode {
                checkpoint_number: "130".to_string(),
                last_attested_digest: "0x4".to_string(),
            },
            attestation_node: AttestationNode {
                header_number: "150".to_string(),
                root: "736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"
                    .to_string(),
                prev_digest: "0000000000000000000000000000000000000000000000000000000000000000"
                    .to_string(),
                digest: "033a4fb6eb4d25411d206b84e4434c7ec6db054fdf0f8281b1cbd17f35dbbce1"
                    .to_string(),
            },
        }),
    );

    let result = create_json_message(
        &supported_chain_info,
        attestation_checks_result,
        "TEST",
        &slack_alert_group,
    );

    assert_eq!(expected_result, result);
}

#[test]
fn create_message_returns_chain_status_and_group_notification_when_slack_group_is_some_and_merkle_root_check_fails(
) {
    let supported_chain_info = SupportedChainInfo {
        chain_id: 1,
        chain_name: "TEST".to_string(),
        chain_key: 2,
    };
    let last_signed_attestation = SignedAttestation {
        attestation: attestor_primitives::Attestation {
            chain_key: 2,
            header_number: 150, // block diff is 50 (passes)
            header_hash: H256::from_slice(&[0u8; 32]),
            root: hex!("736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"),
            prev_digest: Some(H256::from_slice(&[0u8; 32])),
        },
        signature: [0u8; 96],
        attestors: vec![AccountId32::from([0u8; 32]), AccountId32::from([1u8; 32])],
        continuity_proof: Default::default(),
    };
    let slack_alert_group = Some("S_TEST_GROUP".to_string());
    let calculated_ethereum_block_merkle_root = "somecalculatedmerkle".to_string(); // mismatch
    let fetched_ethereum_block_number_by_hash = Some(U64::from(150u64)); // matches header_number
    let latest_ethereum_block_number = 200_u64;
    let maybe_elected_attestors = Some(vec![
        AccountId32::from([0u8; 32]),
        AccountId32::from([1u8; 32]),
    ]);

    let expected_result = (
        json!({
            "username": "usc-audit-automation",
            "icon_emoji": ":shield:",
            "text": "```\
                [TEST - 1] ⬛ TEST\n\
                ✅ Attestation block heights diff: 50 (200|150)\n\
                ✅ Attestation header hash matches correct Ethereum block: (150|150)\n\
                ❌ Calculated merkle root does not match attestation root: (somecalculatedmerkle|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ✅ Last checkpoint creation is within checkpoint range: 150 (200|50)\n\
                ✅ All signed attestors are elected:  (2|2)\n\
                ✅ Last checkpoint number found in GraphQL: (50|50)\n\
                ✅ Last attestation header number found in GraphQL: (150|150)\n\
                ✅ Last attestation root found in GraphQL: (736f6d6563616c63756c617465646d65726b6c65000000000000000000000000|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ✅ Last attestation prev digest found in GraphQL: (0000000000000000000000000000000000000000000000000000000000000000|0000000000000000000000000000000000000000000000000000000000000000)\n\
                ✅ Last attestation digest found in GraphQL: (033a4fb6eb4d25411d206b84e4434c7ec6db054fdf0f8281b1cbd17f35dbbce1|033a4fb6eb4d25411d206b84e4434c7ec6db054fdf0f8281b1cbd17f35dbbce1)\
                ```"
        }),
        Some(json!({
            "username": "usc-audit-automation",
            "icon_emoji": ":rotating_light:",
            "text": "<!subteam^S_TEST_GROUP> The following issues were detected:\nCalculated merkle root does not match attestation root!"
        })),
    );

    let attestation_check_result = compute_attestation_check_result(
        &last_signed_attestation,
        latest_ethereum_block_number,
        calculated_ethereum_block_merkle_root.as_str(),
        fetched_ethereum_block_number_by_hash,
        CheckpointCreatedWithinRangeResult {
            last_checkpoint_block_number: 50,
            latest_ethereum_block_number,
            checkpoint_created_within_range: true,
        },
        maybe_elected_attestors,
        Some(crate::GraphQLAttestationCheckResult {
            checkpoint_chain_node: AttestationCheckpointChainNode {
                checkpoint_number: "50".to_string(),
                last_attested_digest:
                    "05e2c55e28e608eece12b96332c13fed26ab5d14f4850fe2f2a3041a39386e6f".to_string(),
            },
            attestation_node: AttestationNode {
                header_number: "150".to_string(),
                root: "736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"
                    .to_string(),
                prev_digest: "0000000000000000000000000000000000000000000000000000000000000000"
                    .to_string(),
                digest: "033a4fb6eb4d25411d206b84e4434c7ec6db054fdf0f8281b1cbd17f35dbbce1"
                    .to_string(),
            },
        }),
    );

    let result = create_json_message(
        &supported_chain_info,
        attestation_check_result,
        "TEST",
        &slack_alert_group,
    );

    assert_eq!(expected_result, result);
}

#[test]
fn create_message_returns_chain_status_and_group_notification_with_u_slack_id_when_a_check_fails() {
    let supported_chain_info = SupportedChainInfo {
        chain_id: 1,
        chain_name: "TEST".to_string(),
        chain_key: 2,
    };
    let last_signed_attestation = SignedAttestation {
        attestation: attestor_primitives::Attestation {
            chain_key: 2,
            header_number: 180,
            header_hash: H256::from_slice(&[0u8; 32]),
            root: hex!("736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"),
            prev_digest: Some(H256::from_slice(&[0u8; 32])),
        },
        signature: [0u8; 96],
        attestors: vec![],
    };
    let latest_ethereum_block_number = 200_u64;
    let calculated_ethereum_block_merkle_root =
        "736f6d6563616c63756c617465646d65726b6c65000000000000000000000000".to_string();
    let fetched_ethereum_block_number_by_hash = Some(U64::from(100u64));
    let slack_alert_group = Some("U_TEST_USER".to_string());

    let last_checkpoint_block_number = 180;
    let maybe_elected_attestors = Some(vec![
        AccountId32::from([0u8; 32]),
        AccountId32::from([1u8; 32]),
    ]);

    let expected_result = (
        json!({
            "username": "usc-audit-automation",
            "icon_emoji": ":shield:",
            "text": "```\
                [TEST - 1] ⬛ TEST\n\
                ✅ Attestation block heights diff: 20 (200|180)\n\
                ❌ Attestation header hash does not match correct Ethereum block: (100|180)\n\
                ✅ Calculated merkle root matches attestation root: (736f6d6563616c63756c617465646d65726b6c65000000000000000000000000|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ✅ Last checkpoint creation is within checkpoint range: 20 (200|180)\n\
                ✅ All signed attestors are elected:  (0|2)\n\
                ✅ Last checkpoint number found in GraphQL: (180|180)\n\
                ✅ Last attestation header number found in GraphQL: (180|180)\n\
                ✅ Last attestation root found in GraphQL: (736f6d6563616c63756c617465646d65726b6c65000000000000000000000000|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ✅ Last attestation prev digest found in GraphQL: (0000000000000000000000000000000000000000000000000000000000000000|0000000000000000000000000000000000000000000000000000000000000000)\n\
                ✅ Last attestation digest found in GraphQL: (0450faec12366258ce8385f3dda48d90dc92f4928255b9c0feb2c080482f9416|0450faec12366258ce8385f3dda48d90dc92f4928255b9c0feb2c080482f9416)\
                ```"
        }),
        Some(json!({
            "username": "usc-audit-automation",
            "icon_emoji": ":rotating_light:",
            "text": "<@U_TEST_USER> The following issues were detected:\nAttestation header hash does not match correct Ethereum block!"
        })),
    );
    let attestation_check_result = compute_attestation_check_result(
        &last_signed_attestation,
        latest_ethereum_block_number,
        calculated_ethereum_block_merkle_root.as_str(),
        fetched_ethereum_block_number_by_hash,
        CheckpointCreatedWithinRangeResult {
            last_checkpoint_block_number,
            latest_ethereum_block_number,
            checkpoint_created_within_range: true,
        },
        maybe_elected_attestors,
        Some(crate::GraphQLAttestationCheckResult {
            checkpoint_chain_node: AttestationCheckpointChainNode {
                checkpoint_number: "180".to_string(),
                last_attested_digest: "0x4".to_string(),
            },
            attestation_node: AttestationNode {
                header_number: "180".to_string(),
                root: "736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"
                    .to_string(),
                prev_digest: "0000000000000000000000000000000000000000000000000000000000000000"
                    .to_string(),
                digest: "0450faec12366258ce8385f3dda48d90dc92f4928255b9c0feb2c080482f9416"
                    .to_string(),
            },
        }),
    );

    let result = create_json_message(
        &supported_chain_info,
        attestation_check_result,
        "TEST",
        &slack_alert_group,
    );

    assert_eq!(expected_result, result);
}

#[test]
fn create_message_returns_chain_status_and_no_group_notification_when_slack_group_is_none_and_all_checks_fail(
) {
    let supported_chain_info = SupportedChainInfo {
        chain_id: 1,
        chain_name: "TEST".to_string(),
        chain_key: 2,
    };
    let last_signed_attestation = SignedAttestation {
        attestation: attestor_primitives::Attestation {
            chain_key: 2,
            header_number: 140,
            header_hash: H256::from_slice(&[0u8; 32]),
            root: hex!("736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"),
            prev_digest: None,
        },
        signature: [0u8; 96],
        attestors: vec![AccountId32::from([10u8; 32]), AccountId32::from([11u8; 32])],
        continuity_proof: Default::default(),
    };
    let latest_ethereum_block_number = 200_u64;
    let last_checkpoint_block_number = 50;
    let calculated_ethereum_block_merkle_root = "somecalculatedmerkle".to_string();
    let fetched_ethereum_block_number_by_hash = Some(U64::from(100u64));
    let slack_alert_group = None;
    let maybe_elected_attestors = Some(vec![
        AccountId32::from([0u8; 32]),
        AccountId32::from([1u8; 32]),
    ]);

    let expected_result = (
        json!({
            "username": "usc-audit-automation",
            "icon_emoji": ":shield:",
            "text": "```\
                [TEST - 1] ⬛ TEST\n\
                ❌ Attestation block heights diff: 60 (200|140)\n\
                ❌ Attestation header hash does not match correct Ethereum block: (100|140)\n\
                ❌ Calculated merkle root does not match attestation root: (somecalculatedmerkle|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ❌ Last checkpoint creation is outside checkpoint range: 150 (200|50)\n\
                ❌ Found unelected attestors in signed attestors: 5CHsKQwQDWKMqk3gLCvb2oftFQ7MyVMUDzZhNg9w45t1WCTL, 5CKBfVFwvXyYUArQ4VRSrCczG12ASZwjMYPpEAyAKCfryDeD (2|2)\n\
                ❌ Last checkpoint number not found in GraphQL: (0|50)\n\
                ❌ Last attestation header number not found in GraphQL: (0|140)\n\
                ❌ Last attestation root not found in GraphQL: (N/A|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ❌ Last attestation prev digest not found in GraphQL: (N/A|0000000000000000000000000000000000000000000000000000000000000000)\n\
                ❌ Last attestation digest not found in GraphQL: (N/A|06c0604ab2cd092921328e8975192f938fb23d403ff31eca090e31ee360a001a)\
                ```"
        }),
        None,
    );

    let attestation_checks_result = compute_attestation_check_result(
        &last_signed_attestation,
        latest_ethereum_block_number,
        calculated_ethereum_block_merkle_root.as_str(),
        fetched_ethereum_block_number_by_hash,
        CheckpointCreatedWithinRangeResult {
            last_checkpoint_block_number,
            latest_ethereum_block_number,
            checkpoint_created_within_range: false, // <-- Set to false so checkpoint check fails
        },
        maybe_elected_attestors,
        None,
    );

    let result = create_json_message(
        &supported_chain_info,
        attestation_checks_result,
        "TEST",
        &slack_alert_group,
    );

    assert_eq!(expected_result, result);
}

#[test]
fn create_message_returns_chain_status_and_no_group_notification_when_slack_group_is_none_and_block_diff_check_fails(
) {
    let supported_chain_info = SupportedChainInfo {
        chain_id: 1,
        chain_name: "TEST".to_string(),
        chain_key: 2,
    };
    let last_signed_attestation = SignedAttestation {
        attestation: attestor_primitives::Attestation {
            chain_key: 2,
            header_number: 100, // block diff is 100 (fails)
            header_hash: H256::from_slice(&[0u8; 32]),
            root: hex!("736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"),
            prev_digest: Some(H256::from_slice(&[0u8; 32])),
        },
        signature: [0u8; 96],
        attestors: vec![],
        continuity_proof: Default::default(),
    };
    let latest_ethereum_block_number = 200_u64;
    let calculated_ethereum_block_merkle_root =
        "736f6d6563616c63756c617465646d65726b6c65000000000000000000000000".to_string();
    let fetched_ethereum_block_number_by_hash = Some(U64::from(100u64)); // matches header_number
    let slack_alert_group = None;
    let last_checkpoint_block_number = 50;
    let maybe_elected_attestors = Some(vec![
        AccountId32::from([0u8; 32]),
        AccountId32::from([1u8; 32]),
    ]);

    let expected_result = (
        json!({
            "username": "usc-audit-automation",
            "icon_emoji": ":shield:",
            "text": "```\
                [TEST - 1] ⬛ TEST\n\
                ❌ Attestation block heights diff: 100 (200|100)\n\
                ✅ Attestation header hash matches correct Ethereum block: (100|100)\n\
                ✅ Calculated merkle root matches attestation root: (736f6d6563616c63756c617465646d65726b6c65000000000000000000000000|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ✅ Last checkpoint creation is within checkpoint range: 150 (200|50)\n\
                ✅ All signed attestors are elected:  (0|2)\n\
                ✅ Last checkpoint number found in GraphQL: (50|50)\n\
                ✅ Last attestation header number found in GraphQL: (100|100)\n\
                ✅ Last attestation root found in GraphQL: (736f6d6563616c63756c617465646d65726b6c65000000000000000000000000|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ✅ Last attestation prev digest found in GraphQL: (0000000000000000000000000000000000000000000000000000000000000000|0000000000000000000000000000000000000000000000000000000000000000)\n\
                ✅ Last attestation digest found in GraphQL: (02311158238ba841f34895c6496db20167b55b0612b2b628a59c665f918307c9|02311158238ba841f34895c6496db20167b55b0612b2b628a59c665f918307c9)\
                ```"
        }),
        None,
    );

    let attestation_check_result = compute_attestation_check_result(
        &last_signed_attestation,
        latest_ethereum_block_number,
        calculated_ethereum_block_merkle_root.as_str(),
        fetched_ethereum_block_number_by_hash,
        CheckpointCreatedWithinRangeResult {
            last_checkpoint_block_number,
            latest_ethereum_block_number,
            checkpoint_created_within_range: true,
        },
        maybe_elected_attestors,
        Some(crate::GraphQLAttestationCheckResult {
            checkpoint_chain_node: AttestationCheckpointChainNode {
                checkpoint_number: "50".to_string(),
                last_attested_digest: "0x4".to_string(),
            },
            attestation_node: AttestationNode {
                header_number: "100".to_string(),
                root: "736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"
                    .to_string(),
                prev_digest: "0000000000000000000000000000000000000000000000000000000000000000"
                    .to_string(),
                digest: "02311158238ba841f34895c6496db20167b55b0612b2b628a59c665f918307c9"
                    .to_string(),
            },
        }),
    );

    let result = create_json_message(
        &supported_chain_info,
        attestation_check_result,
        "TEST",
        &slack_alert_group,
    );

    assert_eq!(expected_result, result);
}

#[test]
fn create_message_returns_chain_status_and_no_group_notification_when_slack_group_is_none_and_header_hash_check_fails(
) {
    let supported_chain_info = SupportedChainInfo {
        chain_id: 1,
        chain_name: "TEST".to_string(),
        chain_key: 2,
    };
    let last_signed_attestation = SignedAttestation {
        attestation: attestor_primitives::Attestation {
            chain_key: 2,
            header_number: 150, // block diff is 50 (passes)
            header_hash: H256::from_slice(&[0u8; 32]),
            root: hex!("736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"),
            prev_digest: Some(H256::from_slice(&[0u8; 32])),
        },
        signature: [0u8; 96],
        attestors: vec![],
        continuity_proof: Default::default(),
    };
    let latest_ethereum_block_number = 200_u64;
    let calculated_ethereum_block_merkle_root =
        "736f6d6563616c63756c617465646d65726b6c65000000000000000000000000".to_string();
    let fetched_ethereum_block_number_by_hash = Some(U64::from(100u64)); // mismatch: 100 != 150
    let slack_alert_group = None;

    let maybe_elected_attestors = Some(vec![
        AccountId32::from([0u8; 32]),
        AccountId32::from([1u8; 32]),
    ]);

    let expected_result = (
        json!({
            "username": "usc-audit-automation",
            "icon_emoji": ":shield:",
            "text": "```\
                [TEST - 1] ⬛ TEST\n\
                ✅ Attestation block heights diff: 50 (200|150)\n\
                ❌ Attestation header hash does not match correct Ethereum block: (100|150)\n\
                ✅ Calculated merkle root matches attestation root: (736f6d6563616c63756c617465646d65726b6c65000000000000000000000000|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ✅ Last checkpoint creation is within checkpoint range: 150 (200|50)\n\
                ✅ All signed attestors are elected:  (0|2)\n\
                ✅ Last checkpoint number found in GraphQL: (50|50)\n\
                ✅ Last attestation header number found in GraphQL: (150|150)\n\
                ✅ Last attestation root found in GraphQL: (736f6d6563616c63756c617465646d65726b6c65000000000000000000000000|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ✅ Last attestation prev digest found in GraphQL: (0000000000000000000000000000000000000000000000000000000000000000|0000000000000000000000000000000000000000000000000000000000000000)\n\
                ✅ Last attestation digest found in GraphQL: (033a4fb6eb4d25411d206b84e4434c7ec6db054fdf0f8281b1cbd17f35dbbce1|033a4fb6eb4d25411d206b84e4434c7ec6db054fdf0f8281b1cbd17f35dbbce1)\
                ```"
        }),
        None,
    );

    let attestation_check_result = compute_attestation_check_result(
        &last_signed_attestation,
        latest_ethereum_block_number,
        calculated_ethereum_block_merkle_root.as_str(),
        fetched_ethereum_block_number_by_hash,
        CheckpointCreatedWithinRangeResult {
            last_checkpoint_block_number: 50,
            latest_ethereum_block_number,
            checkpoint_created_within_range: true,
        },
        maybe_elected_attestors,
        Some(crate::GraphQLAttestationCheckResult {
            checkpoint_chain_node: AttestationCheckpointChainNode {
                checkpoint_number: "50".to_string(),
                last_attested_digest:
                    "033a4fb6eb4d25411d206b84e4434c7ec6db054fdf0f8281b1cbd17f35dbbce1".to_string(),
            },
            attestation_node: AttestationNode {
                header_number: "150".to_string(),
                root: "736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"
                    .to_string(),
                prev_digest: "0000000000000000000000000000000000000000000000000000000000000000"
                    .to_string(),
                digest: "033a4fb6eb4d25411d206b84e4434c7ec6db054fdf0f8281b1cbd17f35dbbce1"
                    .to_string(),
            },
        }),
    );

    let result = create_json_message(
        &supported_chain_info,
        attestation_check_result,
        "TEST",
        &slack_alert_group,
    );

    assert_eq!(expected_result, result);
}

#[test]
fn create_message_returns_chain_status_and_no_group_notification_when_slack_group_is_none_and_merkle_root_check_fails(
) {
    let supported_chain_info = SupportedChainInfo {
        chain_id: 1,
        chain_name: "TEST".to_string(),
        chain_key: 2,
    };

    let last_signed_attestation = SignedAttestation {
        attestation: attestor_primitives::Attestation {
            chain_key: 2,
            header_number: 150, // block diff is 50 (passes)
            header_hash: H256::from_slice(&[0u8; 32]),
            root: hex!("736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"),
            prev_digest: Some(H256::from_slice(&[0u8; 32])),
        },
        signature: [0u8; 96],
        attestors: vec![],
        continuity_proof: Default::default(),
    };
    let calculated_ethereum_block_merkle_root = "somecalculatedmerkle".to_string(); // mismatch
    let fetched_ethereum_block_number_by_hash = Some(U64::from(150u64)); // matches header_number
    let slack_alert_group: Option<String> = None;

    let last_checkpoint_block_number = 50;
    let latest_ethereum_block_number = 200_u64;

    let expected_result = (
        json!({
            "username": "usc-audit-automation",
            "icon_emoji": ":shield:",
            "text": "```\
                [TEST - 1] ⬛ TEST\n\
                ✅ Attestation block heights diff: 50 (200|150)\n\
                ✅ Attestation header hash matches correct Ethereum block: (150|150)\n\
                ❌ Calculated merkle root does not match attestation root: (somecalculatedmerkle|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ✅ Last checkpoint creation is within checkpoint range: 150 (200|50)\n\
                ✅ All signed attestors are elected:  (0|2)\n\
                ✅ Last checkpoint number found in GraphQL: (50|50)\n\
                ✅ Last attestation header number found in GraphQL: (150|150)\n\
                ✅ Last attestation root found in GraphQL: (736f6d6563616c63756c617465646d65726b6c65000000000000000000000000|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ✅ Last attestation prev digest found in GraphQL: (0000000000000000000000000000000000000000000000000000000000000000|0000000000000000000000000000000000000000000000000000000000000000)\n\
                ✅ Last attestation digest found in GraphQL: (033a4fb6eb4d25411d206b84e4434c7ec6db054fdf0f8281b1cbd17f35dbbce1|033a4fb6eb4d25411d206b84e4434c7ec6db054fdf0f8281b1cbd17f35dbbce1)\
                ```"
        }),
        None,
    );

    let attestation_check_result = compute_attestation_check_result(
        &last_signed_attestation,
        latest_ethereum_block_number,
        calculated_ethereum_block_merkle_root.as_str(),
        fetched_ethereum_block_number_by_hash,
        CheckpointCreatedWithinRangeResult {
            last_checkpoint_block_number,
            latest_ethereum_block_number,
            checkpoint_created_within_range: true,
        },
        Some(vec![
            AccountId32::from([0u8; 32]),
            AccountId32::from([1u8; 32]),
        ]),
        Some(crate::GraphQLAttestationCheckResult {
            checkpoint_chain_node: AttestationCheckpointChainNode {
                checkpoint_number: "50".to_string(),
                last_attested_digest: "0x4".to_string(),
            },
            attestation_node: AttestationNode {
                header_number: "150".to_string(),
                root: "736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"
                    .to_string(),
                prev_digest: "0000000000000000000000000000000000000000000000000000000000000000"
                    .to_string(),
                digest: "033a4fb6eb4d25411d206b84e4434c7ec6db054fdf0f8281b1cbd17f35dbbce1"
                    .to_string(),
            },
        }),
    );

    let result = create_json_message(
        &supported_chain_info,
        attestation_check_result,
        "TEST",
        &slack_alert_group,
    );

    assert_eq!(expected_result, result);
}

#[test]
fn create_message_returns_a_chain_status_and_no_group_notification_when_slack_group_is_none_and_sanity_check_succeeds(
) {
    let supported_chain_info = SupportedChainInfo {
        chain_id: 1,
        chain_name: "TEST".to_string(),
        chain_key: 2,
    };
    let last_signed_attestation = SignedAttestation {
        attestation: attestor_primitives::Attestation {
            chain_key: 2,
            header_number: 150,
            header_hash: H256::from_slice(&[0u8; 32]),
            root: hex!("736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"),
            prev_digest: Some(H256::from_slice(&[0u8; 32])),
        },
        signature: [0u8; 96],
        attestors: vec![],
        continuity_proof: Default::default(),
    };
    let latest_ethereum_block_number = 200_u64;
    let calculated_ethereum_block_merkle_root =
        "736f6d6563616c63756c617465646d65726b6c65000000000000000000000000".to_string();
    let fetched_ethereum_block_number_by_hash = Some(U64::from(150u64));
    let slack_alert_group = None;

    let last_checkpoint_block_number = 50;
    let maybe_elected_attestors = Some(vec![
        AccountId32::from([0u8; 32]),
        AccountId32::from([1u8; 32]),
    ]);

    let expected_result = (
        json!({
            "username": "usc-audit-automation",
            "icon_emoji": ":shield:",
            "text": "```\
                [TEST - 1] ⬛ TEST\n\
                ✅ Attestation block heights diff: 50 (200|150)\n\
                ✅ Attestation header hash matches correct Ethereum block: (150|150)\n\
                ✅ Calculated merkle root matches attestation root: (736f6d6563616c63756c617465646d65726b6c65000000000000000000000000|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ✅ Last checkpoint creation is within checkpoint range: 150 (200|50)\n\
                ✅ All signed attestors are elected:  (0|2)\n\
                ✅ Last checkpoint number found in GraphQL: (50|50)\n\
                ✅ Last attestation header number found in GraphQL: (150|150)\n\
                ✅ Last attestation root found in GraphQL: (736f6d6563616c63756c617465646d65726b6c65000000000000000000000000|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ✅ Last attestation prev digest found in GraphQL: (0000000000000000000000000000000000000000000000000000000000000000|0000000000000000000000000000000000000000000000000000000000000000)\n\
                ✅ Last attestation digest found in GraphQL: (033a4fb6eb4d25411d206b84e4434c7ec6db054fdf0f8281b1cbd17f35dbbce1|033a4fb6eb4d25411d206b84e4434c7ec6db054fdf0f8281b1cbd17f35dbbce1)\
                ```"
        }),
        None,
    );

    let attestation_check_result = compute_attestation_check_result(
        &last_signed_attestation,
        latest_ethereum_block_number,
        calculated_ethereum_block_merkle_root.as_str(),
        fetched_ethereum_block_number_by_hash,
        CheckpointCreatedWithinRangeResult {
            last_checkpoint_block_number,
            latest_ethereum_block_number,
            checkpoint_created_within_range: true,
        },
        maybe_elected_attestors,
        Some(crate::GraphQLAttestationCheckResult {
            checkpoint_chain_node: AttestationCheckpointChainNode {
                checkpoint_number: "50".to_string(),
                last_attested_digest: "0x4".to_string(),
            },
            attestation_node: AttestationNode {
                header_number: "150".to_string(),
                root: "736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"
                    .to_string(),
                prev_digest: "0000000000000000000000000000000000000000000000000000000000000000"
                    .to_string(),
                digest: "033a4fb6eb4d25411d206b84e4434c7ec6db054fdf0f8281b1cbd17f35dbbce1"
                    .to_string(),
            },
        }),
    );

    let result = create_json_message(
        &supported_chain_info,
        attestation_check_result,
        "TEST",
        &slack_alert_group,
    );

    assert_eq!(expected_result, result);
}

#[test]
fn create_message_returns_chain_status_and_no_group_notification_when_slack_group_is_none_and_only_checkpoint_range_fails(
) {
    let supported_chain_info = SupportedChainInfo {
        chain_id: 1,
        chain_name: "TEST".to_string(),
        chain_key: 2,
    };
    let last_signed_attestation = SignedAttestation {
        attestation: attestor_primitives::Attestation {
            chain_key: 2,
            header_number: 180,
            header_hash: H256::from_slice(&[0u8; 32]),
            root: hex!("736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"),
            prev_digest: Some(H256::from_slice(&[0u8; 32])),
        },
        signature: [0u8; 96],
        attestors: vec![],
    };
    let latest_ethereum_block_number = 200_u64;
    let ethereum_current_block_calculated_merkle_root =
        "736f6d6563616c63756c617465646d65726b6c65000000000000000000000000".to_string();
    let eth_block_by_hash = Some(U64::from(180u64));
    let slack_alert_group: Option<String> = None;
    let maybe_elected_attestors = Some(vec![
        AccountId32::from([0u8; 32]),
        AccountId32::from([1u8; 32]),
    ]);
    let last_checkpoint_block_number = 10;

    let expected_result = (
        json!({
            "username": "usc-audit-automation",
            "icon_emoji": ":shield:",
            "text": "```\
                [TEST - 1] ⬛ TEST\n\
                ✅ Attestation block heights diff: 20 (200|180)\n\
                ✅ Attestation header hash matches correct Ethereum block: (180|180)\n\
                ✅ Calculated merkle root matches attestation root: (736f6d6563616c63756c617465646d65726b6c65000000000000000000000000|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ❌ Last checkpoint creation is outside checkpoint range: 190 (200|10)\n\
                ✅ All signed attestors are elected:  (0|2)\n\
                ✅ Last checkpoint number found in GraphQL: (10|10)\n\
                ✅ Last attestation header number found in GraphQL: (180|180)\n\
                ✅ Last attestation root found in GraphQL: (736f6d6563616c63756c617465646d65726b6c65000000000000000000000000|736f6d6563616c63756c617465646d65726b6c65000000000000000000000000)\n\
                ✅ Last attestation prev digest found in GraphQL: (0000000000000000000000000000000000000000000000000000000000000000|0000000000000000000000000000000000000000000000000000000000000000)\n\
                ✅ Last attestation digest found in GraphQL: (0450faec12366258ce8385f3dda48d90dc92f4928255b9c0feb2c080482f9416|0450faec12366258ce8385f3dda48d90dc92f4928255b9c0feb2c080482f9416)\
                ```"
        }),
        None,
    );

    let attestation_check_result = compute_attestation_check_result(
        &last_signed_attestation,
        latest_ethereum_block_number,
        &ethereum_current_block_calculated_merkle_root,
        eth_block_by_hash,
        CheckpointCreatedWithinRangeResult {
            last_checkpoint_block_number,
            latest_ethereum_block_number,
            checkpoint_created_within_range: false,
        },
        maybe_elected_attestors,
        Some(crate::GraphQLAttestationCheckResult {
            attestation_node: AttestationNode {
                header_number: "180".to_string(),
                root: "736f6d6563616c63756c617465646d65726b6c65000000000000000000000000"
                    .to_string(),
                prev_digest: "0000000000000000000000000000000000000000000000000000000000000000"
                    .to_string(),
                digest: "0450faec12366258ce8385f3dda48d90dc92f4928255b9c0feb2c080482f9416"
                    .to_string(),
            },
            checkpoint_chain_node: AttestationCheckpointChainNode {
                checkpoint_number: "10".to_string(),
                last_attested_digest:
                    "0x736f6d6563616c63756c617465646d65726b6c65000000000000000000000000".to_string(),
            },
        }),
    );

    let result = create_json_message(
        &supported_chain_info,
        attestation_check_result,
        "TEST",
        &slack_alert_group,
    );

    assert_eq!(expected_result, result);
}

#[tokio::test]
async fn test_calculate_merkle_root_returns_expected_bytes() {
    // Prepare a test OrderedBlock and expected root
    let chain_id = 1u64;
    let number = 123u64;
    let hash = &[0u8; 32];
    let transactions = vec![];
    let receipts = vec![];
    let test_ordered_block =
        OrderedBlock::try_create(chain_id, number, hash.into(), transactions, receipts).unwrap();
    let test_ordered_block = Arc::new(test_ordered_block); // Wrap in Arc

    // Set up the mock client
    let mut mock_client = MockEthereumProvider::new();
    let block_clone = Arc::clone(&test_ordered_block);
    mock_client
        .expect_get_block_by_number()
        .with(eq(123u64))
        .returning(move |_| {
            let block = Arc::clone(&block_clone);

            Ok(Some((*block).clone()))
        });

    // Call the function
    let result = calculate_merkle_root(&mock_client, 123).await;

    assert!(result.is_ok());
    assert_eq!(result.unwrap().len(), 32);
}
