use crate::{
    block_height_sanity_check::{self, UniversalSmartContractProvider},
    calculate_usc_and_source_chain_block_diff,
    create_json_message::create_json_message,
    BoxFutureResult,
};
use anyhow::Result;
use attestor_primitives::SignedAttestation;
use futures::future::FutureExt;
use serde_json::json;
use sp_core::H256;
use subxt::utils::AccountId32;

pub struct MockUscRpcClientOk;

impl MockUscRpcClientOk {
    pub fn new() -> Self {
        MockUscRpcClientOk
    }
}

impl UniversalSmartContractProvider for MockUscRpcClientOk {
    fn fetch_last_digest(&self, _chain_key: u64) -> BoxFutureResult<'_, H256> {
        (async move { Ok(Some(H256::from_slice(&[0u8; 32]))) }).boxed()
    }

    fn get_attestation_by_digest(
        &self,
        _chain_key: u64,
        _digest: H256,
    ) -> BoxFutureResult<'_, SignedAttestation<H256, AccountId32>, cc_client::Error> {
        (async move {
            Ok(Some(SignedAttestation {
                attestation: attestor_primitives::Attestation {
                    chain_key: 2,
                    header_number: 123,
                    header_hash: H256::from_slice(&[0u8; 32]),
                    root: [0u8; 32],
                    prev_digest: None,
                },
                signature: [0u8; 96],
                attestors: vec![],
            }))
        })
        .boxed()
    }
}

struct MockUscRpcClientError;
impl MockUscRpcClientError {
    pub fn new() -> Self {
        MockUscRpcClientError
    }
}

impl UniversalSmartContractProvider for MockUscRpcClientError {
    fn fetch_last_digest(&self, _chain_key: u64) -> BoxFutureResult<'_, H256> {
        (async move { Ok(None) }).boxed()
    }

    fn get_attestation_by_digest(
        &self,
        _chain_key: u64,
        _digest: H256,
    ) -> BoxFutureResult<'_, SignedAttestation<H256, AccountId32>, cc_client::Error> {
        (async move { Ok(None) }).boxed()
    }
}

#[tokio::test]
async fn get_attestor_best_block_height_fetches_best_block_correctly() -> Result<()> {
    let client = MockUscRpcClientOk::new();
    let target = &crate::NetworkTarget {
        usc_network_name: "TEST".to_string(),
        usc_rpc_url: "test_url".to_string(),
        usc_account_mnemonic: "".to_string(),
        ethereum_rpc_url: "http://someethrpcurl.com".to_string(),
        chain_key: 2,
    };

    // Call mock get_attestor_best_block_height
    let best_block =
        block_height_sanity_check::get_attestor_best_block_height(&client, target).await?;
    let expected_best_block = 123_u64;

    assert_eq!(expected_best_block, best_block);

    Ok(())
}

#[tokio::test]
async fn get_attestor_best_block_height_returns_an_error_when_no_best_block_found() -> Result<()> {
    let client = MockUscRpcClientError::new();
    let target = &crate::NetworkTarget {
        usc_network_name: "TEST".to_string(),
        usc_rpc_url: "test_url".to_string(),
        usc_account_mnemonic: "".to_string(),
        chain_key: 2,
        ethereum_rpc_url: "http://someethrpcurl.com".to_string(),
    };

    // Call mock get_attestor_best_block_height
    let result = block_height_sanity_check::get_attestor_best_block_height(&client, target).await;

    assert!(result.is_err(), "Expected an error but got Ok");

    let err = result.unwrap_err();
    assert!(
        err.to_string()
            .contains("No last digest found for chain key 2"),
        "Unexpected error: {}",
        err
    );

    Ok(())
}

#[tokio::test]
async fn get_ethereum_current_block_number_correctly_gets_block_number() -> Result<()> {
    let mut mock = block_height_sanity_check::MockEthereumProvider::new(); // generated by mock call

    // Mock ethereum trait return value
    mock.expect_fetch_block_number()
        .times(1)
        .returning(|| (async { Ok(Some(42.into())) }).boxed());

    // Call mock get_ethereum_current_block_number
    let eth_block_number =
        block_height_sanity_check::get_ethereum_current_block_number(&mock).await?;
    let expected_block_number = 42_u64;
    assert_eq!(expected_block_number, eth_block_number);

    Ok(())
}

#[tokio::test]
async fn get_ethereum_current_block_number_correctly_handles_an_error() -> Result<()> {
    let mut mock = block_height_sanity_check::MockEthereumProvider::new();

    mock.expect_fetch_block_number()
        .returning(|| (async { Err(anyhow::anyhow!("RPC error: connection dropped")) }).boxed());

    let result = block_height_sanity_check::get_ethereum_current_block_number(&mock).await;
    assert!(result.is_err());

    let err = result.unwrap_err();
    assert_eq!(err.to_string(), "failed to get ethereum block number");
    let mut chain = err.chain();
    chain.next();

    let original_error = chain.next().unwrap();
    assert_eq!(original_error.to_string(), "RPC error: connection dropped");

    Ok(())
}

#[test]
fn calculate_usc_and_source_chain_block_diff_returns_a_positive_value_when_source_chain_is_ahead_of_usc_chain(
) {
    let attestor_block_height = 900_020_u64;
    let source_chain_block_height = 900_050_u64;
    let expected_result = 30_i128;

    let result =
        calculate_usc_and_source_chain_block_diff(attestor_block_height, source_chain_block_height);
    assert_eq!(expected_result, result);
}

#[test]
fn calculate_usc_and_source_chain_block_diff_returns_a_negative_value_if_source_chain_is_behind_usc_chain(
) {
    let attestor_block_height = 900_010_u64;
    let source_chain_block_height = 900_000_u64;
    let expected_result = -10_i128;

    let result =
        calculate_usc_and_source_chain_block_diff(attestor_block_height, source_chain_block_height);
    assert_eq!(expected_result, result);
}

#[test]
fn create_message_returns_a_chain_status_and_group_notification_when_slack_group_is_some_and_sanity_check_fails(
) {
    let target = &crate::NetworkTarget {
        usc_network_name: "TEST".to_string(),
        usc_rpc_url: "http://someuscmetricsurl.com/metrics".to_string(),
        usc_account_mnemonic: "".to_string(),
        chain_key: 2,
        ethereum_rpc_url: "http://someethrpcurl.com".to_string(),
    };
    let attestor_block_number = 100_u64;
    let source_chain_block_number = 200_u64;
    let slack_alert_group = Some("TEST_GROUP".to_string());

    let expected_result = (
        json!({
            "username": "usc-audit-automation",
            "icon_emoji": ":shield:",
            "text": "```⬛ TEST\n❌ Attestation block heights diff: 100 (200|100)```"
        }),
        Some(json!({
            "username": "usc-audit-automation",
            "icon_emoji": ":rotating_light:",
            "text": format!("{} Current block difference exceeds threshold!", "<!subteam^TEST_GROUP>".to_string())
        })),
    );

    let result = create_json_message(
        target.clone(),
        attestor_block_number,
        source_chain_block_number,
        slack_alert_group,
    );

    println!("{:?}", result);

    assert_eq!(expected_result, result);
}

#[test]
fn create_message_returns_a_chain_status_and_no_group_notification_when_slack_group_is_some_and_sanity_check_succeeds(
) {
    let target = &crate::NetworkTarget {
        usc_network_name: "TEST".to_string(),
        usc_rpc_url: "http://someuscmetricsurl.com/metrics".to_string(),
        usc_account_mnemonic: "".to_string(),
        chain_key: 2,
        ethereum_rpc_url: "http://someethrpcurl.com".to_string(),
    };
    let attestor_block_number = 170_u64;
    let source_chain_block_number = 200_u64;
    let slack_alert_group = Some("TEST_GROUP".to_string());

    let expected_result = (
        json!({
            "username": "usc-audit-automation",
            "icon_emoji": ":shield:",
            "text": "```⬛ TEST\n✅ Attestation block heights diff: 30 (200|170)```"
        }),
        None,
    );

    let result = create_json_message(
        target.clone(),
        attestor_block_number,
        source_chain_block_number,
        slack_alert_group,
    );

    println!("{:?}", result);

    assert_eq!(expected_result, result);
}

#[test]
fn create_message_returns_a_chain_status_and_no_group_notification_when_slack_group_is_none_and_sanity_check_fails(
) {
    let target = &crate::NetworkTarget {
        usc_network_name: "TEST".to_string(),
        usc_rpc_url: "http://someuscmetricsurl.com/metrics".to_string(),
        usc_account_mnemonic: "".to_string(),
        chain_key: 2,
        ethereum_rpc_url: "http://someethrpcurl.com".to_string(),
    };
    let attestor_block_number = 140_u64;
    let source_chain_block_number = 200_u64;
    let slack_alert_group = None;

    let expected_result = (
        json!({
            "username": "usc-audit-automation",
            "icon_emoji": ":shield:",
            "text": "```⬛ TEST\n❌ Attestation block heights diff: 60 (200|140)```"
        }),
        None,
    );

    let result = create_json_message(
        target.clone(),
        attestor_block_number,
        source_chain_block_number,
        slack_alert_group,
    );

    println!("{:?}", result);

    assert_eq!(expected_result, result);
}

#[test]
fn create_message_returns_a_chain_status_and_no_group_notification_when_slack_group_is_none_and_sanity_check_succeeds(
) {
    let target = &crate::NetworkTarget {
        usc_network_name: "TEST".to_string(),
        usc_rpc_url: "http://someuscmetricsurl.com/metrics".to_string(),
        usc_account_mnemonic: "".to_string(),
        chain_key: 2,
        ethereum_rpc_url: "http://someethrpcurl.com".to_string(),
    };
    let attestor_block_number = 150_u64;
    let source_chain_block_number = 200_u64;
    let slack_alert_group = None;

    let expected_result = (
        json!({
            "username": "usc-audit-automation",
            "icon_emoji": ":shield:",
            "text": "```⬛ TEST\n✅ Attestation block heights diff: 50 (200|150)```"
        }),
        None,
    );

    let result = create_json_message(
        target.clone(),
        attestor_block_number,
        source_chain_block_number,
        slack_alert_group,
    );

    println!("{:?}", result);

    assert_eq!(expected_result, result);
}
