use chrono::NaiveDateTime;
use diesel::prelude::{ExpressionMethods, Identifiable, Insertable, Queryable};
use diesel::query_dsl::methods::{FilterDsl, LimitDsl};
use diesel::{dsl::now, upsert::excluded};
use diesel_async::RunQueryDsl;

use anyhow::{bail, Result};
use serde_json::Value;
use tracing::error;

use crate::db::{
    schema::continuity_proofs::{self as cp, dsl::continuity_proofs as continuity_proofs_table},
    type_conversions::to_storage_int,
    DbManager,
};
use attestor_primitives::block::ContinuityProof;

// Continuity proof object. This is what we will enter in the DB and perhaps
// also what we return from api calls
#[derive(Debug, Clone)]
pub struct ContinuityProofItem {
    pub chain_key: u64,
    pub header_number: u64,
    pub continuity_proof: ContinuityProof,
    pub ends_in_attestation: bool,
}

/// This is the struct you insert into continuity_proofs
/// It doesn't contain auto-generated entries such as `created_at`
#[derive(Debug, Insertable)]
#[diesel(table_name = cp)]
pub struct ContinuityProofInsertable {
    pub chain_key: i64,
    pub header_number: i64,
    pub continuity_proof: Value,
    pub ends_in_attestation: bool,
}

/// You get this struct back when selecting from continuity_proofs
/// Contains fields such as `created_at`, which are automatically generated by postgres
#[derive(Debug, Queryable, Identifiable)]
#[diesel(table_name = cp)]
pub struct ContinuityProofRecord {
    pub id: i32,
    pub chain_key: i64,
    pub header_number: i64,
    pub continuity_proof: Value,
    pub ends_in_attestation: bool,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
}

impl DbManager {
    pub fn insert_continuity_proof(&self, proof: ContinuityProofItem) {
        let pool = self.pool.clone();

        tokio::spawn(async move {
            let proof_chain_key = proof.chain_key;
            let proof_header = proof.header_number;
            // Convert to insertable row struct
            let insertable = match ContinuityProofInsertable::try_from(proof) {
                Ok(v) => v,
                Err(e) => {
                    error!(
                        "Failed to convert ContinuityProofItem into ContinuityProofInsertable: {e}; proof_chain_key={proof_chain_key}; proof_header_number ={proof_header}"
                    );
                    return;
                }
            };

            // Get an async Diesel connection
            let mut conn = match pool.get().await {
                Ok(c) => c,
                Err(e) => {
                    error!(
                        "DB connection unavailable; not caching continuity proof. Error: {e}; proof_chain_key={proof_chain_key}; proof_header_number={proof_header}"
                    );
                    return;
                }
            };

            if let Err(e) = diesel::insert_into(continuity_proofs_table)
                .values(&insertable)
                .on_conflict((cp::chain_key, cp::header_number))
                .do_update()
                .set((
                    cp::continuity_proof.eq(excluded(cp::continuity_proof)),
                    cp::ends_in_attestation.eq(excluded(cp::ends_in_attestation)),
                    cp::updated_at.eq(now),
                ))
                .execute(&mut conn)
                .await
            {
                error!("Failed to insert Merkle proof {insertable:?}: {e}");
            }
        });
    }

    pub async fn get_continuity_proof_for_block(
        &self,
        chain_key: u64,
        header_number: u64,
    ) -> Result<Option<ContinuityProofRecord>> {
        let mut conn = self.pool.get().await?;

        let rows: Vec<ContinuityProofRecord> = continuity_proofs_table
            .filter(cp::chain_key.eq(to_storage_int(chain_key)))
            .filter(cp::header_number.eq(to_storage_int(header_number)))
            .limit(2)
            .load(&mut conn)
            .await?;

        if rows.len() > 1 {
            bail!(
                "Expected at most one continuity proof, but found {} for chain_key={}, header_number={}",
                rows.len(),
                chain_key,
                header_number
            );
        }

        Ok(rows.into_iter().next())
    }
}
