use chrono::NaiveDateTime;
use diesel::prelude::{ExpressionMethods, Identifiable, Insertable, Queryable};
use diesel::query_dsl::methods::{FilterDsl, LimitDsl};
use diesel::{dsl::now, upsert::excluded};
use diesel_async::RunQueryDsl;

use serde_json::Value;
use sp_core::H256;
use tracing::error;

use crate::db::{
    schema::merkle_proofs::{self as mp, dsl::merkle_proofs as merkle_proofs_table},
    type_conversions::{to_storage_hash, to_storage_int},
    DbManager,
};
use merkle::proof::TransactionMerkleProof;

use anyhow::{bail, Result};

// Merkle proof object. This is what we will enter in the DB and perhaps
// also what we return from api calls
#[derive(Debug, Clone)]
pub struct MerkleProofItem {
    pub chain_key: u64,
    pub header_number: u64,
    pub tx_index: Option<u64>, // Maybe should make this non-null if we remove intended support for full block merkle proofs
    pub tx_hash: Option<H256>,
    pub tx_bytes: Option<Vec<u8>>, // Cached transaction bytes (includes BlockItem identifier prefix)
    // Use concrete types for downstream consumers; we'll serialize only at DB boundary.
    pub merkle_proof: TransactionMerkleProof,
    pub merkle_root: H256,
}

/// This is the struct you insert into merkle_proofs
/// It doesn't contain auto-generated entries such as `created_at`
#[derive(Debug, Insertable)]
#[diesel(table_name = mp)]
pub struct MerkleProofInsertable {
    pub chain_key: i64,
    pub header_number: i64,
    pub tx_index: Option<i64>,
    pub tx_hash: Option<String>,
    pub tx_bytes: Option<Vec<u8>>,
    pub merkle_proof: Value,
    pub merkle_root: String,
}

/// You get this struct back when selecting from merkle_proofs
/// Contains fields such as `created_at`, which are automatically generated by postgres
#[derive(Debug, Queryable, Identifiable)]
#[diesel(table_name = mp)]
pub struct MerkleProofRecord {
    pub id: i32,
    pub chain_key: i64,
    pub header_number: i64,
    pub tx_index: Option<i64>,
    pub tx_hash: Option<String>,
    pub tx_bytes: Option<Vec<u8>>,
    pub merkle_proof: Value,
    pub merkle_root: String,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
}

impl DbManager {
    /// Fire-and-forget insert of a Merkle proof into `merkle_proofs`.
    pub fn insert_merkle_proof(&self, proof: MerkleProofItem) {
        let pool = self.pool.clone();

        tokio::spawn(async move {
            // Convert to insertable row struct
            let insertable = match MerkleProofInsertable::try_from(proof.clone()) {
                Ok(v) => v,
                Err(e) => {
                    error!(
                        "Failed to convert MerkleProofItem into MerkleProofInsertable: {e}; proof={proof:?}"
                    );
                    return;
                }
            };

            // Get an async Diesel connection
            let mut conn = match pool.get().await {
                Ok(c) => c,
                Err(e) => {
                    error!(
                        "DB connection unavailable; not caching Merkle proof. Error: {e}; proof={proof:?}"
                    );
                    return;
                }
            };

            // Update on conflict of (chain_key, header_number) if tx index is null
            // This allows for full block proofs where there is no tx index
            if insertable.tx_index.is_none() {
                if let Err(e) = diesel::insert_into(merkle_proofs_table)
                    .values(&insertable)
                    .on_conflict((mp::chain_key, mp::header_number))
                    .do_update()
                    .set((
                        mp::tx_hash.eq(excluded(mp::tx_hash)),
                        mp::tx_bytes.eq(excluded(mp::tx_bytes)),
                        mp::merkle_proof.eq(excluded(mp::merkle_proof)),
                        mp::merkle_root.eq(excluded(mp::merkle_root)),
                        mp::updated_at.eq(now),
                    ))
                    .execute(&mut conn)
                    .await
                {
                    error!("Failed to insert Merkle proof {insertable:?}: {e}");
                }
            } else if let Err(e) = diesel::insert_into(merkle_proofs_table)
                .values(&insertable)
                .on_conflict((mp::chain_key, mp::header_number, mp::tx_index))
                .do_update()
                .set((
                    mp::tx_hash.eq(excluded(mp::tx_hash)),
                    mp::tx_bytes.eq(excluded(mp::tx_bytes)),
                    mp::merkle_proof.eq(excluded(mp::merkle_proof)),
                    mp::merkle_root.eq(excluded(mp::merkle_root)),
                    mp::updated_at.eq(now),
                ))
                .execute(&mut conn)
                .await
            {
                error!("Failed to insert Merkle proof {insertable:?}: {e}");
            }
        });
    }

    pub async fn get_merkle_proof_for_block(
        &self,
        chain_key: u64,
        header_number: u64,
    ) -> Result<Option<MerkleProofRecord>> {
        let mut conn = self.pool.get().await?;

        let rows: Vec<MerkleProofRecord> = merkle_proofs_table
            .filter(mp::chain_key.eq(to_storage_int(chain_key)))
            .filter(mp::header_number.eq(to_storage_int(header_number)))
            .filter(mp::tx_index.is_null())
            .limit(2)
            .load(&mut conn)
            .await?;

        if rows.len() > 1 {
            bail!(
                "Expected at most one merkle proof, but found {} for chain_key={} header_number={} with tx_index IS NULL",
                rows.len(),
                chain_key,
                header_number
            );
        }

        Ok(rows.into_iter().next())
    }

    pub async fn get_merkle_proof_for_tx(
        &self,
        chain_key: u64,
        header_number: u64,
        tx_index: u64,
    ) -> Result<Option<MerkleProofRecord>> {
        let mut conn = self.pool.get().await?;

        let rows: Vec<MerkleProofRecord> = merkle_proofs_table
            .filter(mp::chain_key.eq(to_storage_int(chain_key)))
            .filter(mp::header_number.eq(to_storage_int(header_number)))
            .filter(mp::tx_index.eq(to_storage_int(tx_index)))
            .limit(2)
            .load(&mut conn)
            .await?;

        if rows.len() > 1 {
            bail!(
                "Expected at most one merkle proof, but found {} for chain_key={}, header_number={}, tx_index={}",
                rows.len(),
                chain_key,
                header_number,
                tx_index
            );
        }

        Ok(rows.into_iter().next())
    }

    pub async fn get_merkle_proof_by_tx_hash(
        &self,
        chain_key: u64,
        tx_hash: H256,
    ) -> Result<Option<MerkleProofRecord>> {
        let mut conn = self.pool.get().await?;

        let rows: Vec<MerkleProofRecord> = merkle_proofs_table
            .filter(mp::chain_key.eq(to_storage_int(chain_key)))
            .filter(mp::tx_hash.eq(to_storage_hash(tx_hash)))
            .limit(2)
            .load(&mut conn)
            .await?;

        if rows.len() > 1 {
            bail!(
                "Expected at most one merkle proof, but found {} for chain_key={}, tx_hash={}",
                rows.len(),
                chain_key,
                tx_hash
            );
        }

        Ok(rows.into_iter().next())
    }
}
