use anyhow::{bail, Result};
use chrono::NaiveDateTime;
use deadpool_postgres::{Config, ManagerConfig, Pool, RecyclingMethod};
use serde_json::Value;
use sp_core::H256;
use tokio_postgres::NoTls;
use tracing::{debug, info};

use attestor_primitives::block::ContinuityProof;
use mmr::query_proof::QueryMerkleProof;
use type_conversions::{to_storage_hash, to_storage_int};

mod type_conversions;

const V1_DOWN_SQL: &str = include_str!("../../migrations/v1/down.sql");
const V1_UP_SQL: &str = include_str!("../../migrations/v1/up.sql");

// Query proofs object. This is what we will enter in the DB and perhaps
// also what we return from api calls
#[derive(Debug, Clone)]
pub struct QueryProofs {
    pub chain_key: u64,
    pub header_number: u64,
    pub tx_index: Option<u64>,
    pub tx_hash: Option<H256>,
    // Use concrete types for downstream consumers; we'll serialize only at DB boundary.
    pub continuity_proof: Option<ContinuityProof>,
    pub merkle_proof: Option<QueryMerkleProof>,
    pub merkle_root: Option<H256>,
}

// Db entry with all rust types converted into postgres compatible types.
// Also adds several autogenerated db entry fields.
#[derive(Debug, Clone)]
pub struct ProofsDbEntry {
    pub id: i32,
    pub chain_key: i64,
    pub header_number: i64,
    pub tx_index: Option<i64>,
    pub tx_hash: Option<String>,
    pub continuity_proof: Option<Value>,
    pub merkle_proof: Option<Value>,
    pub merkle_root: Option<String>,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
}

#[derive(Clone)]
pub struct DbManager {
    pool: Pool,
}

/// Creates a new db manager with a pool of DB connections
impl DbManager {
    pub fn new() -> Result<Self> {
        // Get db connection details from env variables
        let postgres_host = std::env::var("POSTGRES_HOST").expect("POSTGRES_HOST must be set");
        let postgres_port = std::env::var("POSTGRES_PORT").expect("POSTGRES_PORT must be set");
        let postgres_user = std::env::var("POSTGRES_USER").expect("POSTGRES_USER must be set");
        let postgres_password =
            std::env::var("POSTGRES_PASSWORD").expect("POSTGRES_PASSWORD must be set");
        let postgres_db = std::env::var("POSTGRES_DB").expect("POSTGRES_DB must be set");

        // Set up DB connection pool
        let mut cfg = Config::new();
        cfg.host = Some(postgres_host);
        cfg.port = Some(postgres_port.parse::<u16>()?);
        cfg.user = Some(postgres_user);
        cfg.password = Some(postgres_password);
        cfg.dbname = Some(postgres_db);
        cfg.manager = Some(ManagerConfig {
            recycling_method: RecyclingMethod::Fast,
        });

        let pool = cfg.create_pool(Some(deadpool_postgres::Runtime::Tokio1), NoTls)?;

        Ok(DbManager { pool })
    }

    pub async fn run_migrations(&self) -> Result<()> {
        let client = self.pool.get().await?;
        info!("Running all UP migrations to establish tables.");
        client.batch_execute(V1_UP_SQL).await?;

        Ok(())
    }

    // Because we don't need to wait on the insert result, we spawn a task to insert in the background
    pub fn insert_proofs_entry(&self, proofs: QueryProofs) {
        let pool = self.pool.clone();
        tokio::spawn(async move {
            // Convert first so we can potentially store in memory if pool unavailable
            let converted = match ProofsDbEntry::try_from(proofs.clone()) {
                Ok(entry) => entry,
                Err(e) => {
                    tracing::error!("Failed to convert QueryProofs into ProofsDbEntry, error: {e}");
                    return;
                }
            };
            match pool.get().await {
                Ok(client) => {
                    let entry = converted.clone();
                    let result = if entry.tx_index.is_some() {
                        // Non-null tx_index → use (chain_key, header_number, tx_index)
                        client.execute(
                            r#"
                            INSERT INTO proofs (
                                chain_key,
                                header_number,
                                tx_index,
                                tx_hash,
                                continuity_proof,
                                merkle_proof,
                                merkle_root
                            )
                            VALUES ($1, $2, $3, $4, $5, $6, $7)
                            ON CONFLICT (chain_key, header_number, tx_index) WHERE tx_index IS NOT NULL
                            DO UPDATE SET
                                tx_hash = EXCLUDED.tx_hash,
                                continuity_proof = EXCLUDED.continuity_proof,
                                merkle_proof = EXCLUDED.merkle_proof,
                                merkle_root = EXCLUDED.merkle_root,
                                updated_at = now()
                            "#,
                            &[
                                &entry.chain_key,
                                &entry.header_number,
                                &entry.tx_index,
                                &entry.tx_hash,
                                &entry.continuity_proof,
                                &entry.merkle_proof,
                                &entry.merkle_root,
                            ],
                        ).await
                    } else {
                        // NULL tx_index → use (chain_key, header_number)
                        client
                            .execute(
                                r#"
                            INSERT INTO proofs (
                                chain_key,
                                header_number,
                                tx_index,
                                tx_hash,
                                continuity_proof,
                                merkle_proof,
                                merkle_root
                            )
                            VALUES ($1, $2, NULL, $3, $4, $5, $6)
                            ON CONFLICT (chain_key, header_number) WHERE tx_index IS NULL
                            DO UPDATE SET
                                tx_hash = EXCLUDED.tx_hash,
                                continuity_proof = EXCLUDED.continuity_proof,
                                merkle_proof = EXCLUDED.merkle_proof,
                                merkle_root = EXCLUDED.merkle_root,
                                updated_at = now()
                            "#,
                                &[
                                    &entry.chain_key,
                                    &entry.header_number,
                                    &entry.tx_hash,
                                    &entry.continuity_proof,
                                    &entry.merkle_proof,
                                    &entry.merkle_root,
                                ],
                            )
                            .await
                    };

                    if let Err(e) = result {
                        tracing::error!("Failed to insert proof {entry:?}, error: {e}");
                    }
                }
                Err(e) => {
                    // Do not quietly continue if DB is down; log loudly and return.
                    tracing::error!("DB connection unavailable; not caching proofs. Error: {e}. Incoming proofs: {proofs:?}");
                }
            }
        });
    }

    pub async fn get_proofs_for_block(
        &self,
        chain_key: u64,
        header_number: u64,
    ) -> Result<Option<ProofsDbEntry>> {
        let client = self.pool.get().await?;
        let rows = client
            .query(
                r#"
            SELECT
                id,
                chain_key,
                header_number,
                tx_index,
                tx_hash,
                continuity_proof,
                merkle_proof,
                merkle_root,
                created_at,
                updated_at
            FROM proofs
            WHERE chain_key = $1
              AND header_number = $2
              AND tx_index IS NULL
            LIMIT 2
            "#,
                &[&to_storage_int(chain_key), &to_storage_int(header_number)],
            )
            .await?;

        if rows.is_empty() {
            return Ok(None);
        }

        if rows.len() > 1 {
            bail!(
                "Expected at most one proof, but found {} for chain_key={} header_number={} with tx_index IS NULL",
                rows.len(),
                chain_key,
                header_number
            );
        }

        let entry = ProofsDbEntry::try_from(&rows[0])?;

        Ok(Some(entry))
    }

    pub async fn get_proofs_for_tx(
        &self,
        chain_key: u64,
        header_number: u64,
        tx_index: u64,
    ) -> Result<Option<ProofsDbEntry>> {
        let client = self.pool.get().await?;
        let rows = client
            .query(
                r#"
            SELECT
                id,
                chain_key,
                header_number,
                tx_index,
                tx_hash,
                continuity_proof,
                merkle_proof,
                merkle_root,
                created_at,
                updated_at
            FROM proofs
            WHERE chain_key = $1
              AND header_number = $2
              AND tx_index = $3
            LIMIT 2
            "#,
                &[
                    &to_storage_int(chain_key),
                    &to_storage_int(header_number),
                    &to_storage_int(tx_index),
                ],
            )
            .await?;

        if rows.is_empty() {
            return Ok(None);
        }

        if rows.len() > 1 {
            bail!(
                "Expected at most one proof, but found {} for chain_key={} header_number={}, tx_index={}",
                rows.len(),
                chain_key,
                header_number,
                tx_index
            );
        }

        let entry = ProofsDbEntry::try_from(&rows[0])?;

        Ok(Some(entry))
    }

    pub async fn get_proofs_by_tx_hash(
        &self,
        chain_key: u64,
        tx_hash: H256,
    ) -> Result<Option<ProofsDbEntry>> {
        let client = self.pool.get().await?;
        let rows = client
            .query(
                r#"
            SELECT
                id,
                chain_key,
                header_number,
                tx_index,
                tx_hash,
                continuity_proof,
                merkle_proof,
                merkle_root,
                created_at,
                updated_at
            FROM proofs
            WHERE chain_key = $1
              AND tx_hash = $2
            LIMIT 2
            "#,
                &[&to_storage_int(chain_key), &to_storage_hash(tx_hash)],
            )
            .await?;

        if rows.is_empty() {
            return Ok(None);
        }

        if rows.len() > 1 {
            bail!(
                "Expected at most one proof, but found {} for chain_key={}, tx_hash={}",
                rows.len(),
                chain_key,
                tx_hash,
            );
        }

        let entry = ProofsDbEntry::try_from(&rows[0])?;

        Ok(Some(entry))
    }

    pub async fn reset_db(&self) -> Result<()> {
        debug!("Connecting to database to reset...");
        let client = self.pool.get().await?;
        client
            .query("DROP SCHEMA public CASCADE;", &[])
            .await
            .expect("Failed to drop schema");
        client
            .query("CREATE SCHEMA public;", &[])
            .await
            .expect("Failed to create schema");

        client.batch_execute(V1_DOWN_SQL).await?;
        client.batch_execute(V1_UP_SQL).await?;

        Ok(())
    }
}
