use attestor_primitives::AttestationCheckpoint;
use bigdecimal::BigDecimal;
use diesel::prelude::*;

/// Unified model for attestations, checkpoints, and regular continuity blocks
#[derive(Debug, Clone, Queryable, QueryableByName, Insertable)]
#[diesel(table_name = crate::db::schema::continuity_blocks)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct ContinuityBlockItem {
    #[diesel(skip_insertion)]
    pub id: i32,
    pub chain_key: i64,
    pub header_number: BigDecimal,
    pub digest: String,
    pub is_attestation: bool,
    pub is_checkpoint: bool,
}

impl ContinuityBlockItem {
    /// Create from attestation data
    pub fn from_attestation(chain_key: u64, header_number: u64, digest: String) -> Self {
        Self {
            id: 0, // Will be auto-generated by database
            chain_key: chain_key as i64,
            header_number: BigDecimal::from(header_number),
            digest,
            is_attestation: true,
            is_checkpoint: false,
        }
    }

    /// Create from checkpoint data
    pub fn from_checkpoint(chain_key: u64, checkpoint: &AttestationCheckpoint) -> Self {
        Self {
            id: 0, // Will be auto-generated by database
            chain_key: chain_key as i64,
            header_number: BigDecimal::from(checkpoint.block_number),
            digest: format!("0x{:x}", checkpoint.digest),
            is_attestation: false,
            is_checkpoint: true,
        }
    }

    /// Create from regular block data
    pub fn from_regular_block(chain_key: u64, header_number: u64, digest: String) -> Self {
        Self {
            id: 0, // Will be auto-generated by database
            chain_key: chain_key as i64,
            header_number: BigDecimal::from(header_number),
            digest,
            is_attestation: false,
            is_checkpoint: false,
        }
    }

    /// Check if this is an attestation
    pub fn is_attestation(&self) -> bool {
        self.is_attestation
    }

    /// Check if this is a checkpoint
    pub fn is_checkpoint(&self) -> bool {
        self.is_checkpoint
    }

    /// Check if this is a regular block
    pub fn is_regular(&self) -> bool {
        !self.is_attestation && !self.is_checkpoint
    }
}
