#!/bin/sh

# Function
# - compiles ./verify_merkle_proof.cairo
# - runs the previously compiled program ./verify_merkle_proof_compiled.json
#
# Argument(s)
# - path to the subfolder where the generated proof is located
#
# Example
# source verify_merkle_proof.sh <path to the program_input.json> <proof_mode>

if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]; then
  echo "expected arguments: input_path proof_mode(optional)"
  exit 10
fi

CAIRO_PROGRAM_SOURCE="../cairo/scripts/verify_merkle_proof"
INPUT_PATH="./$1"
PROOF_MODE=$2
CAIRO_LANG_DIR="../cairo/lang"

PROGRAM_INPUT_FILE="$INPUT_PATH/program_input.json"
AIR_PROVER_CONFIG="$CAIRO_LANG_DIR/cpu_air_prover_config.json"
AIR_PARAMS="$CAIRO_LANG_DIR/cpu_air_params.json"

if [ ! -d "$INPUT_PATH" ]; then
  echo "$INPUT_PATH does not exist. This folder is supposed to hold the 'program_input.json'."
  exit 20
fi

if [ ! -f "$PROGRAM_INPUT_FILE" ]; then
  echo "$PROGRAM_INPUT_FILE does not exist. This file holds the continuity chain json the integrity of which to be proven by the STARK. It can be generated by running generate_chain_input.sh"
  exit 21
fi

if [ "$PROOF_MODE" = "proof_mode" ]; then
  if [ ! -f "$AIR_PARAMS" ]; then
    echo "$AIR_PARAMS does not exist. This file needs to exist so the script can update parameters with accordance to execution trace."
    exit 22
  fi

  if [ ! -f "$AIR_PROVER_CONFIG" ]; then
    echo "$AIR_PROVER_CONFIG does not exist."
    exit 23
  fi
fi

SOURCE_FILE="$CAIRO_PROGRAM_SOURCE.cairo"
COMPILED_FILE="${CAIRO_PROGRAM_SOURCE}_compiled.json"

if [ ! -f "$SOURCE_FILE" ]; then
  echo "$SOURCE_FILE does not exist. It is expected to contain the attestation chain data."
  exit 25
fi

echo "source: $SOURCE_FILE"
echo "output: $COMPILED_FILE"
echo "cairo-compiling..."

message=$(cairo-compile "$SOURCE_FILE" --output "$COMPILED_FILE" --proof_mode 2>&1)
if ! cairo-compile "$SOURCE_FILE" --output "$COMPILED_FILE" --proof_mode 2>&1; then
  echo "compilation failed: $message"
  exit 30
fi

if [ ! -f "$COMPILED_FILE" ]; then
  echo "$COMPILED_FILE was not generated."
  exit 31
fi

PRIVATE_INPUT="$INPUT_PATH/private_input.json"
PUBLIC_INPUT="$INPUT_PATH/public_input.json"
TRACE_FILE="$INPUT_PATH/trace.json"
MEMORY_FILE="$INPUT_PATH/memory.json"
OUTPUT_FILE="$INPUT_PATH/output.txt"
echo "program: $COMPILED_FILE"
echo "program input: $PROGRAM_INPUT_FILE"
#echo "trace_file: $TRACE_FILE"
#echo "memory_file: $MEMORY_FILE"
echo "program output: $OUTPUT_FILE"

if [ "$PROOF_MODE" = "proof_mode" ]; then
  echo "air_private_input: $PRIVATE_INPUT"
  echo "air_public_input: $PUBLIC_INPUT"

  echo "cairo-running..."
  message=$(cairo-run \
    --program="$COMPILED_FILE" \
    --layout=recursive \
    --program_input="$PROGRAM_INPUT_FILE" \
    --air_public_input="$PUBLIC_INPUT" \
    --air_private_input="$PRIVATE_INPUT" \
    --trace_file="$TRACE_FILE" \
    --memory_file="$MEMORY_FILE" \
    --print_output \
    --proof_mode 2>&1)

else
  echo "cairo-running..."
  message=$(
    cairo-run \
      --program="$COMPILED_FILE" \
      --layout=recursive \
      --program_input="$PROGRAM_INPUT_FILE" \
      --trace_file="$TRACE_FILE" \
      --memory_file="$MEMORY_FILE" \
      --print_output 2>&1
  )
fi

# shellcheck disable=SC2181
if [ $? -ne 0 ]; then
  echo "cairo-run: $message"
  exit 40
else
  echo "$message" >"$OUTPUT_FILE"
fi

if [ "$PROOF_MODE" != "proof_mode" ]; then
  exit 0
fi
