#!/usr/bin/env node
// Extracts BridgeVault/BridgeHub ABIs from the Foundry build artifacts in
// usc-messaging/contracts/out/ and writes them as `as const` TS modules, so wagmi/viem get fully
// typed contract reads/writes/event args instead of hand-typed (and driftable) ABI literals.
//
// Usage:
//   node scripts/gen-abi.mjs          regenerate
//   node scripts/gen-abi.mjs --check  fail (nonzero exit) if regenerating would change anything —
//                                     run this in CI to catch ABI drift after a contracts change.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import prettier from "prettier";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CONTRACTS_OUT = join(
  __dirname,
  "..",
  "..",
  "usc-messaging",
  "contracts",
  "out",
);
const GENERATED_DIR = join(
  __dirname,
  "..",
  "src",
  "lib",
  "contracts",
  "generated",
);

const CONTRACTS = ["BridgeVault", "BridgeHub"];
const CHECK = process.argv.includes("--check");

function readAbi(name) {
  const path = join(CONTRACTS_OUT, `${name}.sol`, `${name}.json`);
  if (!existsSync(path)) {
    throw new Error(
      `${path} not found — run \`forge build\` in usc-messaging/contracts first`,
    );
  }
  const artifact = JSON.parse(readFileSync(path, "utf8"));
  return artifact.abi;
}

async function render(name, abi) {
  const raw =
    `// AUTO-GENERATED by scripts/gen-abi.mjs from usc-messaging/contracts/out/${name}.sol/${name}.json — do not edit by hand.\n` +
    `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
  // Run through Prettier so the committed output matches `yarn check-format`'s expectations —
  // otherwise every regeneration reformats these files even when the ABI itself hasn't changed.
  return prettier.format(raw, { parser: "typescript" });
}

let changed = false;
if (!existsSync(GENERATED_DIR)) mkdirSync(GENERATED_DIR, { recursive: true });

for (const name of CONTRACTS) {
  const abi = readAbi(name);
  const fileName = name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
  const outPath = join(GENERATED_DIR, `${fileName}.abi.ts`);
  const rendered = await render(name, abi);
  const existing = existsSync(outPath) ? readFileSync(outPath, "utf8") : null;

  if (existing !== rendered) {
    changed = true;
    if (CHECK) {
      console.error(
        `ABI drift: ${outPath} is out of date with the Foundry build artifact`,
      );
    } else {
      writeFileSync(outPath, rendered);
      console.log(`wrote ${outPath}`);
    }
  }
}

if (CHECK && changed) {
  console.error("Run `yarn gen-abi` and commit the result.");
  process.exit(1);
}
if (!changed) {
  console.log("ABIs already up to date.");
}
