use crate::prefixed::Prefixed;
use crate::proof::Proof;
use crate::{Error, ARITY};
use core::fmt::Debug;
use core::hash::Hash;

impl<H: HashT> PartialEq for Prefixed<H> {
    fn eq(&self, other: &Self) -> bool {
        self.hashes == other.hashes
    }
}

/// trait for a hash pluggable to Merkle tree at compile time
pub trait HashT {
    /// output returned by hash implementor
    type Output: Hash + Default + Copy + PartialEq + Debug + From<u8> + Send + Sync;
    /// hash implementation
    fn hash(input: &[u8]) -> Self::Output;
    /// default implementation for concatenating and hashing hash values contained in the nodes
    /// used by proof items for hashing with prefix
    fn concat_then_hash(hashes: &[Self::Output]) -> Self::Output {
        unsafe {
            Self::hash(core::slice::from_raw_parts(
                hashes.as_ref().as_ptr() as *const u8,
                core::mem::size_of_val(hashes),
            ))
        }
    }
}
/// trait that an item contained in a proof implements.
pub trait ProofItemT<H: HashT>: Clone + Default + Debug {
    /// consructor
    fn create(offset: usize, prefixed: Prefixed<H>) -> Self;
    /// hash the hashed input with its siblings
    fn hash_with_siblings(self, word_hash: H::Output) -> Option<H::Output>;
}

/// trait for verifying a proof generated by Proof
pub trait ProofValidator {
    /// verify the proof at given index
    fn validate(&self, input: &[u8]) -> bool;
}
/// trait for a basic Merkle Tree functionality
pub trait MerkleTreeTrait<H: HashT> {
    /// generate a proof for a leaf at index
    fn generate_proof(&self, index: usize) -> Proof<H>;
    /// replace a leaf at index with a new value
    fn replace(&mut self, index: usize, input: &[u8]);
    /// replace a hashed leaf at index with a new hashed value
    fn replace_leaf(&mut self, index: usize, leaf: H::Output);
    /// return a root
    fn root(&self) -> H::Output;
    /// return a slice of leaves
    fn leaves(&self) -> &[Prefixed<H>];
    /// a size (not necessarily a number of currently present leaves) of the leaf layer
    fn base_layer_size(&self) -> usize;
    /// returns tree's arity (determined at compile time)
    fn arity(&self) -> usize {
        ARITY as usize
    }
    /// returns tree's height (determined at compile time)
    fn height(&self) -> usize;
}
/// trait for append-only Merkle tree semantics
pub trait AppendOnly {
    /// appends a new leaf into the tree unless it's full
    fn try_append(&mut self, input: &[u8]) -> Result<(), Error>;
    /// number of leaves currently stored in the tree
    fn num_of_leaves(&self) -> usize;
}

/// trait for Merkle tree supporting leaf removal
pub trait CanRemove {
    /// removes a leaf at index
    fn remove(&mut self, index: usize);
    /// number of leaves currently stored in the trsee
    fn num_of_leaves(&self) -> usize;
}
