{
 "title": "attestor votes from rpc",
 "description": "attestor votes from rpc",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Attestor best block",
   "type": "stat",
   "description": "The best block that the attestor has seen",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "substrate_attestor_best_block", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Attestor votes sent",
   "type": "stat",
   "description": "The number of votes sent by the attestor",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "substrate_attestor_votes_sent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Attestor best voted for",
   "type": "stat",
   "description": "The best voted for block by the attestor",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "substrate_attestor_best_voted", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Received Votes from RPC",
   "type": "stat",
   "description": "The number of votes received from RPC",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "attestor_votes_from_rpc", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Imported votes count",
   "type": "stat",
   "description": "The number of votes imported from RPC",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "attestor_imported_votes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Invalid votes count",
   "type": "gauge",
   "description": "The number of invalid votes",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_attestor_invalid_votes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Attestor good votes processed",
   "type": "stat",
   "description": "The number of good votes processed by the attestor",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_attestor_successful_handled_votes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Attestor equivocation votes",
   "type": "stat",
   "description": "The number of equivocation votes",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_attestor_equivocation_votes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Attestor no authority",
   "type": "stat",
   "description": "The number of votes that have no authority found in the store",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_attestor_no_authority_found_in_store",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}