---
name: Attestor Chaos

"on":
  schedule:
    # At minute 30 past every 13th hour
    - cron: "30 */13 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

env:
  RUNNER_VM_NAME: "attestor-chaos-$GITHUB_RUN_ID-attempt-$GITHUB_RUN_ATTEMPT"
  LINODE_REGION: "nl-ams"
  # Shared CPU, Linode 8 GB, 4 vCPU, 96 $/mo
  LINODE_VM_SIZE: "g6-standard-4"

jobs:
  deploy-attestor:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - proxy: attestor-chaos

    name: deploy-attestor / ${{ matrix.proxy }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      # See https://github.com/actions/runner/issues/1879#issuecomment-1123196869
      - name: Create matrix.txt
        run: |
          echo "proxy=${{ matrix.proxy }} /  / type=" > matrix.txt

      - name: Evaluate env vars
        id: get-env
        run: |
          HASH_VALUE=$(echo "${{ hashFiles('matrix.txt') }}" | cut -c1-7)
          rm matrix.txt

          # WARNING: using env.RUNNER_VM_NAME directly in job outputs above
          # doesn't evaluate the $GITHUB_RUN_ID reference
          echo "runner_vm_name=${{ env.RUNNER_VM_NAME }}-$HASH_VALUE" >> "$GITHUB_OUTPUT"

          # note: keep this VM for 24hrs so it has the ability to become an active attestor
          KEEP_UNTIL=$(date --utc "+%Y-%m-%dT%H:%M:%S" -d "+24 hours")
          echo "KEEP_UNTIL=$KEEP_UNTIL" >> "$GITHUB_ENV"

      - name: Provision VM
        if: env.LC_GITHUB_REPO_ADMIN_TOKEN
        run: |
          .github/provision-linode-vm.sh
        env:
          LC_OWNER_REPO_SLUG: ${{ github.repository }}
          LC_GITHUB_REPO_ADMIN_TOKEN: ${{ secrets.GH_REPO_ADMIN_TOKEN }}
          LC_RUNNER_VM_NAME: ${{ steps.get-env.outputs.runner_vm_name }}
          LC_PROXY_ENABLED: ${{ matrix.proxy }}
          LC_WORKFLOW_ID: ${{ github.run_id }}
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
          KEEP_UNTIL: ${{ env.KEEP_UNTIL }}

      - name: Upload Linode logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linode-${{ matrix.proxy }}-logs
          path: retry*.json

  start-attestor:
    needs:
      - deploy-attestor
    runs-on: [self-hosted, "workflow-${{ github.run_id }}", "proxy-attestor-chaos"]
    steps:
      - uses: actions/checkout@v5

      - name: Devnet ENV
        id: devnet-env
        run: |
          # shellcheck disable=SC2129
          echo "stash_secret=${{ secrets.ATTESTOR_CHAOS_STASH_MNEMONIC }}" >> "$GITHUB_OUTPUT"
          echo "rpc_url=wss://rpc.ccnext-devnet.creditcoin.network" >> "$GITHUB_OUTPUT"
          echo "eth_rpc_url=wss://sepolia.infura.io/ws/v3/${{ secrets.ATTESTOR_CHAOS_INFURA_API_KEY }}" >> "$GITHUB_OUTPUT"
          echo "sepolia_chain_key=3" >> "$GITHUB_OUTPUT"
          RELEASE_TAG=$(.github/extract-release-tag.sh "devnet")
          echo "release_tag=$RELEASE_TAG" >> "$GITHUB_OUTPUT"
          echo "artifact_name=attestor-binaries-$RELEASE_TAG-$(uname -m)-unknown-linux-gnu.zip" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Testnet ENV
        id: testnet-env
        run: |
          # shellcheck disable=SC2129
          echo "stash_secret=${{ secrets.ATTESTOR_CHAOS_STASH_MNEMONIC }}" >> "$GITHUB_OUTPUT"
          echo "rpc_url=wss://rpc.usc-testnet.creditcoin.network" >> "$GITHUB_OUTPUT"
          echo "eth_rpc_url=wss://sepolia.infura.io/ws/v3/${{ secrets.ATTESTOR_CHAOS_INFURA_API_KEY }}" >> "$GITHUB_OUTPUT"
          echo "sepolia_chain_key=1" >> "$GITHUB_OUTPUT"
          RELEASE_TAG=$(.github/extract-release-tag.sh "testnet")
          echo "release_tag=$RELEASE_TAG" >> "$GITHUB_OUTPUT"
          echo "artifact_name=attestor-binaries-$RELEASE_TAG-$(uname -m)-unknown-linux-gnu.zip" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # TODO: change to Testnet once we have a new release vvv
      - name: Download attestor binaries for release ${{ steps.devnet-env.outputs.release_tag }}
        uses: i3h/download-release-asset@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: target/release/
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          tag: ${{ steps.devnet-env.outputs.release_tag }}
          file: ${{ steps.devnet-env.outputs.artifact_name }}
          # TODO: ^^^ change to Testnet once we have a new release

      - name: Extract binaries from archive
        working-directory: target/release/
        run: |
          unzip ./attestor-binaries-*-unknown-linux-gnu.zip
          chmod a+x ./attestor*

      - name: Start Attestation Zombienet
        run: |
          # adjust path to binary b/c running from the root dir of the repository
          sed -i 's|default_command: ".*"|default_command: "./target/release/attestor"|' attestor_zombienet/config.yaml

          mkdir -p /var/tmp/attestor-chaos

          # TODO: vvv change to Testnet once we have a new release
          ./target/release/attestor_zombienet \
                --verbose \
                --cc3-rpc-url ${{ steps.devnet-env.outputs.rpc_url }} \
                --cc3-key "${{ steps.devnet-env.outputs.stash_secret }}" \
                --eth-rpc-url ${{ steps.devnet-env.outputs.eth_rpc_url }} \
                --chain-key ${{ steps.devnet-env.outputs.sepolia_chain_key }} \
                --config-file attestor_zombienet/config.yaml \
                --logs-dir /var/tmp/attestor-chaos/ 2>&1 | tee -a /var/tmp/attestor-chaos/zombienet.log &

      - name: Check logs for errors
        if: always()
        run: |
          # wait 2 mins before checking for any errors on start
          sleep 120
          .github/check-logs-for-error.sh /var/tmp/attestor-chaos/

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: attestor-logs
          path: /var/tmp/attestor-chaos/
          include-hidden-files: true
