---
name: Attestor Chaos

"on":
  schedule:
    # At minute 30 past every 23rd hour
    - cron: "30 */23 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

env:
  RUNNER_VM_NAME: "attestor-chaos-$GITHUB_RUN_ID-attempt-$GITHUB_RUN_ATTEMPT"
  LINODE_REGION: "nl-ams"
  # Shared CPU, Linode 8 GB, 4 vCPU, 96 $/mo
  LINODE_VM_SIZE: "g6-standard-4"

jobs:
  setup:
    outputs:
      prev-runId: ${{ steps.prev-runId.outputs.result }}
      # TODO: change to Testnet once we have a new release vvv
      rpc_url: ${{ steps.devnet-env.outputs.rpc_url }}
      sepolia_chain_key: ${{ steps.devnet-env.outputs.sepolia_chain_key }}
      release_tag: ${{ steps.devnet-env.outputs.release_tag }}
      artifact_name: ${{ steps.devnet-env.outputs.artifact_name }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Devnet ENV
        id: devnet-env
        run: |
          # shellcheck disable=SC2129
          echo "rpc_url=wss://rpc.ccnext-devnet.creditcoin.network" >> "$GITHUB_OUTPUT"
          echo "sepolia_chain_key=3" >> "$GITHUB_OUTPUT"
          RELEASE_TAG=$(.github/extract-release-tag.sh "devnet")
          echo "release_tag=$RELEASE_TAG" >> "$GITHUB_OUTPUT"
          echo "artifact_name=attestor-binaries-$RELEASE_TAG-$(uname -m)-unknown-linux-gnu.zip" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Testnet ENV
        id: testnet-env
        run: |
          # shellcheck disable=SC2129
          echo "rpc_url=wss://rpc.usc-testnet.creditcoin.network" >> "$GITHUB_OUTPUT"
          echo "sepolia_chain_key=1" >> "$GITHUB_OUTPUT"
          RELEASE_TAG=$(.github/extract-release-tag.sh "testnet")
          echo "release_tag=$RELEASE_TAG" >> "$GITHUB_OUTPUT"
          echo "artifact_name=attestor-binaries-$RELEASE_TAG-$(uname -m)-unknown-linux-gnu.zip" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find previous runId
        id: prev-runId
        uses: actions/github-script@v7
        with:
          script: |
            core.info(`Current execution=${context.runId}. Getting latest executions ...`);

            try {
              const workflow = await github.rest.actions.getWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.runId,
              });

            const executions = await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: workflow.data.workflow_id,
            });

            const curr = executions.data.workflow_runs[0];
            // check ordering otherwise the rest will be messed up
            if (curr.id !== context.runId) {
                throw new Error(`Current runId not the first in API response`);
            }

            // the second item in this list must be the previous
            // workflow execution
            const prev = executions.data.workflow_runs[1];

            core.info(`CURR=${curr}, ${curr.id}, ${curr.created_at}`);
            core.info(`PREV=${prev}, ${prev.id}, ${prev.created_at}`);

              return prev.id;
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`);
            }

      - name: DEBUG
        run: |
          echo ${{ steps.prev-runId.outputs.result }}

  chill-previous:
    runs-on: ubuntu-24.04
    needs:
      - setup
      - start-attestor
    steps:
      - uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
      - run: npm install -g yarn

      - name: Install Solidity compiler
        run: |
          sudo .github/install-solidity-compiler.sh

      - name: Generate ABI from source code
        working-directory: ./precompiles/metadata
        run: |
          solc --version
          ./abi-creator.sh

      - name: Install openzeppelin dependencies
        working-directory: ./common/eth/contracts/
        run: |
          npm install

      - name: Compile Hardhat contract(s)
        working-directory: ./docs/smart-contract-development/with-hardhat
        run: |
          npm install
          npx hardhat compile

      - name: Build and install creditcoin-cli
        working-directory: ./cli
        run: |
          yarn install
          yarn build
          npm install -g .

      - name: Chill all previous attestors
        run: |
          # this makes sure we have a `creditcoin` entrypoint in the standard PATH
          which creditcoin

          echo "INFO: Attestors for the ATTESTOR CHAOS STASH account"
          creditcoin attestor show-attestors-for \
            --url "${{ needs.setup.outputs.rpc_url }}" \
            --chain "${{ needs.setup.outputs.sepolia_chain_key }}" \
            --substrate-address 5H8rQGjvt4PSXBqAifNamQMxpzNo9pK8DXD41CWPQXfa5Gh6
          echo "----- END -----"

          echo "Withdraw unbonded for STASH ...";
          creditcoin attestor withdraw-unbonded \
              --url "${{ needs.setup.outputs.rpc_url }}" || echo;

          # chill & unregister all previous attestors associated with this stash account
          for ADDR in $(creditcoin attestor show-attestors-for \
            --url "${{ needs.setup.outputs.rpc_url }}" \
            --chain "${{ needs.setup.outputs.sepolia_chain_key }}" \
            --substrate-address 5H8rQGjvt4PSXBqAifNamQMxpzNo9pK8DXD41CWPQXfa5Gh6 | \
            grep Address | cut -f2 -d' ' | \
            grep -v "${{ needs.start-attestor.outputs.attestor_address }}"
          ); do
            echo "INFO: Chilling $ADDR ...";
            creditcoin attestor chill \
                --url "${{ needs.setup.outputs.rpc_url }}" \
                --chain "${{ needs.setup.outputs.sepolia_chain_key }}" \
                --attestor "$ADDR" || echo;

            echo "Unregistering $ADDR ...";
            creditcoin attestor unregister \
                --url "${{ needs.setup.outputs.rpc_url }}" \
                --chain "${{ needs.setup.outputs.sepolia_chain_key }}" \
                --attestor "$ADDR" || echo;
          done

          echo "Withdraw unbonded for STASH ...";
          creditcoin attestor withdraw-unbonded \
              --url "${{ needs.setup.outputs.rpc_url }}" || echo;
        env:
          CC_SECRET: "${{ secrets.ATTESTOR_CHAOS_STASH_MNEMONIC }}"

  deploy-attestor:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - proxy: attestor-chaos

    name: deploy-attestor / ${{ matrix.proxy }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      # See https://github.com/actions/runner/issues/1879#issuecomment-1123196869
      - name: Create matrix.txt
        run: |
          echo "proxy=${{ matrix.proxy }} /  / type=" > matrix.txt

      - name: Evaluate env vars
        id: get-env
        run: |
          HASH_VALUE=$(echo "${{ hashFiles('matrix.txt') }}" | cut -c1-7)
          rm matrix.txt

          # WARNING: using env.RUNNER_VM_NAME directly in job outputs above
          # doesn't evaluate the $GITHUB_RUN_ID reference
          echo "runner_vm_name=${{ env.RUNNER_VM_NAME }}-$HASH_VALUE" >> "$GITHUB_OUTPUT"

          # note: keep this VM for 24hrs so it has the ability to become an active attestor
          KEEP_UNTIL=$(date --utc "+%Y-%m-%dT%H:%M:%S" -d "+24 hours")
          echo "KEEP_UNTIL=$KEEP_UNTIL" >> "$GITHUB_ENV"

      - name: Provision VM
        if: env.LC_GITHUB_REPO_ADMIN_TOKEN
        run: |
          .github/provision-linode-vm.sh
        env:
          LC_OWNER_REPO_SLUG: ${{ github.repository }}
          LC_GITHUB_REPO_ADMIN_TOKEN: ${{ secrets.GH_REPO_ADMIN_TOKEN }}
          LC_RUNNER_VM_NAME: ${{ steps.get-env.outputs.runner_vm_name }}
          LC_PROXY_ENABLED: ${{ matrix.proxy }}
          LC_WORKFLOW_ID: ${{ github.run_id }}
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
          KEEP_UNTIL: ${{ env.KEEP_UNTIL }}

      - name: Upload Linode logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linode-${{ matrix.proxy }}-logs
          path: retry*.json

  start-attestor:
    outputs:
      attestor_address: ${{ steps.check-logs.outputs.attestor_address }}
    needs:
      - setup
      - deploy-attestor
    runs-on: [self-hosted, "workflow-${{ github.run_id }}", "proxy-attestor-chaos"]
    steps:
      - uses: actions/checkout@v5

      - name: docker pull for release ${{ needs.setup.outputs.release_tag }}
        run: |
          echo "${{ secrets.DOCKER_PUSH_PASSWORD }}" | docker login -u="${{ secrets.DOCKER_PUSH_USERNAME }}" --password-stdin

          docker pull ${{ github.repository }}:${{ needs.setup.outputs.release_tag }}
          docker images

          docker logout

      - name: Start Attestation Zombienet
        run: |
          # adjust path to binary b/c running inside a container
          sed -i 's|default_command: ".*"|default_command: "/bin/attestor"|' attestor_zombienet/config.yaml
          sed -i 's|num_attestors: .*|num_attestors: 1|' attestor_zombienet/config.yaml

          mkdir -p /var/tmp/attestor-chaos
          chmod a+rwx /var/tmp/attestor-chaos

          # IMPORTANT: prevent the runner from killing "orphaned" processes
          # when the CI job completes! This will be killed later when the VM is recycled!
          unset RUNNER_TRACKING_ID

          # WARNING: outputs containing secrets are redacted and not sent to downstream jobs
          # therefore we need to use the secrets directly in-place!
          docker run --name attestor_container -i \
            --volume ./attestor_zombienet/config.yaml:/var/tmp/zombienet.yaml \
            --volume /var/tmp/attestor-chaos/:/var/tmp/attestor-chaos/ \
            --entrypoint /bin/attestor_zombienet \
            ${{ github.repository }}:${{ needs.setup.outputs.release_tag }} \
                --verbose \
                --cc3-rpc-url ${{ needs.setup.outputs.rpc_url }} \
                --cc3-key "${{ secrets.ATTESTOR_CHAOS_STASH_MNEMONIC }}" \
                --eth-rpc-url wss://sepolia.infura.io/ws/v3/${{ secrets.ATTESTOR_CHAOS_INFURA_API_KEY }} \
                --chain-key ${{ needs.setup.outputs.sepolia_chain_key }} \
                --config-file /var/tmp/zombienet.yaml \
                --logs-dir /var/tmp/attestor-chaos/ 2>&1 | tee -a /var/tmp/attestor-chaos/zombienet.log &

      - name: Check logs for errors
        id: check-logs
        if: always()
        run: |
          # wait 5 mins before checking for any errors on start
          sleep 300
          .github/check-logs-for-error.sh /var/tmp/attestor-chaos/

          # collect attestor address(es) so we can avoid chilling them on this execution
          grep "Registering attestor with address" /var/tmp/attestor-chaos/zombienet.log  | cut -d "(" -f2 | cut -d")" -f1 > /var/tmp/attestor-addresses.txt
          echo "INFO: Attestor addresses registered in this execution"
          cat /var/tmp/attestor-addresses.txt
          echo "----- END -----"

          # WARNING: figure out how to filter out multiple addresses in case we start
          # more than 1 in the future
          echo "attestor_address=$(cat /var/tmp/attestor-addresses.txt)" >> "$GITHUB_OUTPUT"

      - name: Schedule random attestor restart/disconnect
        run: |
          # IMPORTANT: prevent the runner from killing "orphaned" processes
          # when the CI job completes! This will be killed later when the VM is recycled!
          unset RUNNER_TRACKING_ID

          .github/random-container-pause.sh attestor_container &

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: attestor-logs
          path: /var/tmp/attestor-chaos/
          include-hidden-files: true

      - name: Upload registered addresses
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: attestor-addresses
          path: /var/tmp/attestor-addresses.txt
