---
name: Creditcoin USC Audit Automation Check

"on":
  schedule:
    - cron: "0 */12 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: read-all

jobs:
  setup:
    outputs:
      release_tag: ${{ steps.devnet-env.outputs.release_tag }}
      artifact_name: ${{ steps.devnet-env.outputs.artifact_name }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Devnet ENV
        id: devnet-env
        run: |
          # shellcheck disable=SC2129
          RELEASE_TAG=$(.github/extract-release-tag.sh "devnet")
          echo "release_tag=$RELEASE_TAG" >> "$GITHUB_OUTPUT"
          echo "artifact_name=usc_audit_automation-$RELEASE_TAG-$(uname -m)-unknown-linux-gnu.zip" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  usc-audit:
    runs-on: ubuntu-24.04
    needs: setup

    strategy:
      matrix:
        network: [Devnet, Testnet]

    steps:
      - name: Download creditcoin3-node for release ${{ needs.setup.outputs.release_tag }}
        uses: i3h/download-release-asset@v1
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          tag: ${{ needs.setup.outputs.release_tag }}
          file: ${{ needs.setup.outputs.artifact_name }}
          path: target/release/
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

      - name: Unzip & Restore executable permissions
        working-directory: target/release
        run: |
          unzip *.zip

          chmod a+x ./usc_audit_automation

          ls -l

      - name: Create Config File
        shell: bash
        env:
          AUDIT_CONFIG_TOML: >-
            ${{
              (matrix.network == 'Devnet' && secrets.USC_DEVNET_AUDIT_AUTOMATION_CONFIG_TOML) ||
              (matrix.network == 'Testnet' && secrets.USC_TESTNET_AUDIT_AUTOMATION_CONFIG_TOML)
            }}
        run: |
          printf "%b" "$AUDIT_CONFIG_TOML" > config.toml

      - name: Run USC Audit Automation
        shell: bash
        run: ./target/release/usc_audit_automation --config-file config.toml
