---
name: BENCHMARKS

# Controls when the action will run.
on:
  pull_request:
    branches: [testnet]
  workflow_dispatch:

env:
  RUNNER_VM_NAME: "${{ github.event.repository.name }}-$GITHUB_RUN_ID-attempt-$GITHUB_RUN_ATTEMPT"
  LINODE_REGION: "nl-ams"

jobs:
  check-if-needed:
    # To avoid endless loop in CI skip this job on the commit which
    # auto-updates the weights and is generated further below.
    if: ${{ github.triggering_actor != 'gluwa-bot' }}
    runs-on: ubuntu-24.04
    outputs:
      needs-bench: ${{ steps.version-check.outputs.needs_bench }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Check versions
        id: version-check
        run: |
          ./.github/check-spec-increase.sh "remotes/origin/$GITHUB_BASE_REF" "HEAD"

  build-benchmarks:
    runs-on:
      [self-hosted, "${{ needs.deploy-github-runner.outputs.runner_vm_name }}"]
    needs:
      - deploy-github-runner
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          # don't persist b/c next job authenticates itself
          persist-credentials: false

      - name: Inspect benchmark CI config
        run: |
          # WARNING: Command below may differ depending on which workflow config file
          # your job is defined in !!! Don't copy&paste it blindly !!!
          PALLETS_IN_CI_CONFIG=$(grep " .github/bench.sh -p" .github/workflows/benchmarks.yml | grep -v PALLETS_IN_CI_CONFIG | tr -s ' ' | cut -d' ' -f4 | sort | xargs)

          PALLETS_IN_SOURCE=$(./.github/check-parity-bw-extrinsics-benchmarks-weights.sh --show-pallets)
          if [ "$PALLETS_IN_CI_CONFIG" != "$PALLETS_IN_SOURCE" ]; then
              echo "FAIL: Pallet mismatch between source code and benchmark CI config"
              echo "INFO: in source: '$PALLETS_IN_SOURCE'"
              echo "INFO: CI config: '$PALLETS_IN_CI_CONFIG'"
              exit 1
          fi

      - name: Install protobuf
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: gluwa/toolchain@dev
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2

      - name: Build benchmarks
        uses: gluwa/cargo@dev
        with:
          command: build
          args: --release --features runtime-benchmarks

      - name: Upload benchmark binary
        uses: actions/upload-artifact@v4
        with:
          name: creditcoin3-node
          path: target/release/creditcoin3-node

  deploy-github-runner:
    runs-on: ubuntu-24.04
    needs: check-if-needed
    if: needs.check-if-needed.outputs.needs-bench == 1
    outputs:
      runner_vm_name: ${{ steps.get-env.outputs.runner_vm_name }}

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Evaluate env vars
        id: get-env
        run: |
          # WARNING: using env.RUNNER_VM_NAME directly in job outputs above
          # doesn't evaluate the $GITHUB_RUN_ID reference
          echo "runner_vm_name=${{ env.RUNNER_VM_NAME }}" >> "$GITHUB_OUTPUT"

      - name: Provision VM
        if: env.LC_GITHUB_REPO_ADMIN_TOKEN
        run: |
          .github/provision-linode-vm.sh
        env:
          LC_OWNER_REPO_SLUG: ${{ github.repository }}
          LC_GITHUB_REPO_ADMIN_TOKEN: ${{ secrets.GH_REPO_ADMIN_TOKEN }}
          LC_RUNNER_EPHEMERAL: false
          LC_RUNNER_VM_NAME: ${{ steps.get-env.outputs.runner_vm_name }}
          LC_WORKFLOW_ID: ${{ github.run_id }}
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
          # Shared CPU, Linode 16 GB, 6 vCPU, 96 $/mo
          LINODE_VM_SIZE: "g6-standard-6"

  hardware-benchmarks:
    # see https://gist.github.com/jonico/a94d03cac7a858e0613926d9f1bc7f2b
    runs-on:
      [self-hosted, "${{ needs.deploy-github-runner.outputs.runner_vm_name }}"]
    # checkov:skip=CKV2_GHA_1:We need this for weights auto-update
    permissions: write-all
    needs:
      - deploy-github-runner
      - build-benchmarks
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.CREDITCOIN_GITHUB_API_TOKEN }}
          lfs: true

      - name: Set env
        run: |
          echo "HOME=/home/actions" >> "$GITHUB_ENV"

      - name: Download benchmark binary
        uses: actions/download-artifact@v4
        with:
          name: creditcoin3-node
          path: target/release

      - name: Restore executable permissions
        run: |
          chmod a+x ./target/release/creditcoin3-node

      - name: Check if runner machine meets chain's requirements
        continue-on-error: true
        run: |
          ./.github/check-hardware.sh

      - name: Regenerate weights
        shell: bash
        continue-on-error: false
        run: |
          .github/bench.sh -p attestation_poc -b -s 2 -r 2
          .github/bench.sh -p prover -b
          .github/bench.sh -p randomness -b
          .github/bench.sh -p supported_chains -b

      - name: git diff
        run: |
          git diff

      - name: Commit changes to current branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: gluwa-bot
          author_email: creditcoin@gluwa.com
          message: "Auto-update pallet weights"

      - name: Prepare commit for PR against dev
        id: prepare-commit
        run: |
          LAST_COMMIT=$(git rev-parse HEAD)
          BRANCH_NAME=auto-update-weights-for-dev-${{ github.sha }}

          git checkout -b "$BRANCH_NAME" origin/dev
          git cherry-pick "$LAST_COMMIT"
          git push origin "$BRANCH_NAME"

          REPO_NAME=$(echo "${{ github.repository }}" | cut -f2 -d"/")
          echo "repo_name=$REPO_NAME" >> "$GITHUB_OUTPUT"

      - name: Open PR against dev
        id: open_pr
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.CREDITCOIN_GITHUB_API_TOKEN }}
          from-branch: auto-update-weights-for-dev-${{ github.sha }}
          to-branch: dev
          repository-owner: ${{ github.repository_owner }}
          repository: ${{ steps.prepare-commit.outputs.repo_name }}

      - name: PR number against dev
        run: echo ${{ steps.open_pr.outputs.pull_number }}

  remove-github-runner:
    runs-on: ubuntu-24.04
    needs:
      - deploy-github-runner
      - hardware-benchmarks
    if: ${{ always() && needs.deploy-github-runner.result != 'skipped' }}

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Remove VM
        continue-on-error: true
        run: |
          .github/remove-linode-vm.sh
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
          LC_RUNNER_VM_NAME: ${{ needs.deploy-github-runner.outputs.runner_vm_name }}
