---
name: build-creditcoin3-node-for-ci
# Build creditcoin3-node with flags suitable for CI jobs.
# Many of the other workflows are scheduled after this one!

"on":
  pull_request:
    branches: [main, testnet, poc_external_attestation_network]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  deploy-runner-build-creditcoin-for-testing:
    uses: ./.github/workflows/deploy-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      LINODE_REGION: "nl-ams"
      LINODE_VM_SIZE: "g6-standard-4"
      proxy: "build-creditcoin-node-for-testing-ci"
    secrets: inherit

  build-creditcoin-node-for-testing-ci:
    needs:
      - deploy-runner-build-creditcoin-for-testing
    uses: ./.github/workflows/build-native.yml
    with:
      build-options: "--release --features=fast-runtime"
      build-subkey: true
      version-string: testing-ci
      cache-key-name: build-creditcoin-node
      runs-on: "['self-hosted', 'workflow-${{ github.run_id }}', 'proxy-build-creditcoin-node-for-testing-ci']"
    secrets: inherit

  rm-gh-runner-build-creditcoin-node-for-testing:
    needs:
      - build-creditcoin-node-for-testing-ci
    if: ${{ always() }}
    uses: ./.github/workflows/remove-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      proxy: "build-creditcoin-node-for-testing-ci"
    secrets: inherit
