name: Build USC Audit Automation Binary

on:
    workflow_call:
        inputs:
            version-string:
                required: true
                type: string
            runs-on:
                required: true
                type: string

permissions: read-all

jobs:
    build-usc-audit:
        runs-on: ${{ fromJSON(inputs.runs-on) }}

        steps:
            - uses: actions/checkout@v6

            - name: Configure rustc version
              run: |
                  RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
                  echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: ${{ env.RUSTC_VERSION }}

            - name: Build USC Audit Automation
              run: |
                  cargo build --release --package usc_audit_automation

            - name: Rename binary for versioned release
              run: |
                  cp target/release/usc_audit_automation usc_audit_automation-${{ inputs.version-string }}

            - name: Upload USC Audit Automation binary
              uses: actions/upload-artifact@v5
              with:
                  name: usc_audit_automation
                  path: usc_audit_automation-${{ inputs.version-string }}
                  if-no-files-found: error
