name: cc3-indexer
on:
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./cc3-indexer
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install
        run: yarn install

      - name: Codegen
        run: yarn codegen

      - name: Build
        run: yarn build

      - name: Run compose
        run: docker compose up postgres -d

      - name: Run tests with Subquery Node
        run: ./run-tests.sh

      - name: Produce HTML coverage report
        if: always()
        run: |
          yarn run c8 report --reporter=html

          # remove this b/c these special characters break actions/upload-artifact.
          # IMPORTANT: coverage report will be slightly broken !
          rm -f coverage/cc3-indexer/dist/cc3-indexer/external\ node-commonjs\ \"assert\".html

      - name: Upload HTML coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: cc3-indexer/coverage/

      - name: Delete compose
        run: docker compose down

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: subql-node-test-logs
          path: /var/tmp/subql-node-test-*.log
