---
name: chainspec

"on":
  pull_request:
    branches: [main, testnet, poc_external_attestation_network]
    paths:
      - "runtime/**"
      - "chainspecs/**"
      - "cli/src/test/**ChainspecSetup.ts"
      - "cli/src/test/blockchain-tests/**"
      - ".github/workflows/chainspec.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-runner-build-creditcoin-for:
    strategy:
      fail-fast: false
      matrix:
        include:
          - proxy: build-creditcoin-node-for-devnet
          - proxy: build-creditcoin-node-for-testnet
    uses: ./.github/workflows/deploy-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      LINODE_REGION: "nl-ams"
      LINODE_VM_SIZE: "g6-standard-4"
      proxy: ${{ matrix.proxy }}
    secrets: inherit

  build-creditcoin-node-for-devnet:
    needs:
      - deploy-runner-build-creditcoin-for
    uses: ./.github/workflows/build-native.yml
    with:
      build-options: "--release --features=fast-runtime --features=devnet"
      version-string: devnet
      cache-key-name: build-creditcoin-node
      runs-on: "['self-hosted', 'workflow-${{ github.run_id }}', 'proxy-build-creditcoin-node-for-devnet']"
    secrets: inherit

  build-creditcoin-node-for-testnet:
    needs:
      - deploy-runner-build-creditcoin-for
    uses: ./.github/workflows/build-native.yml
    with:
      build-options: "--release"
      version-string: testnet
      cache-key-name: build-creditcoin-node
      runs-on: "['self-hosted', 'workflow-${{ github.run_id }}', 'proxy-build-creditcoin-node-for-testnet']"
    secrets: inherit

  rm-gh-runner-build-creditcoin-node:
    needs:
      - build-creditcoin-node-for-devnet
      - build-creditcoin-node-for-testnet
    if: ${{ always() }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - proxy: build-creditcoin-node-for-devnet
          - proxy: build-creditcoin-node-for-testnet
    uses: ./.github/workflows/remove-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      proxy: ${{ matrix.proxy }}
    secrets: inherit

  integration-test-chainspec:
    needs:
      - build-creditcoin-node-for-devnet
      - build-creditcoin-node-for-testnet
    strategy:
      fail-fast: false
      matrix:
        chainspec: [devnet, testnet]
    name: integration-test-chainspec-${{ matrix.chainspec }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Download creditcoin-node binary
        uses: actions/download-artifact@v8
        with:
          name: binary-for-${{ matrix.chainspec }}
          path: target/release

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - run: npm install -g yarn

      - name: Start Node 1
        run: |
          chmod a+x ./target/release/creditcoin3-node
          ./target/release/creditcoin3-node \
            --chain ${{ matrix.chainspec }} \
            --validator --alice  --pruning archive \
            --node-key d182d503b7dd97e7c055f33438c7717145840fd66b2a055284ee8d768241a463 \
            --base-path ./alice-data-${{ matrix.chainspec }} &

      - name: Wait for node(s)s to start
        timeout-minutes: 5
        run: |
          ./.github/wait-for-creditcoin.sh 'http://127.0.0.1:9944'

      - name: Install Solidity compiler
        run: |
          sudo .github/install-solidity-compiler.sh

      - name: Generate precompiles ABI from source code
        working-directory: ./precompiles/metadata
        run: |
          solc --version
          ./abi-creator.sh

      - name: Install creditcoin-cli dependencies
        working-directory: ./cli
        run: |
          yarn install

      - name: Run blockchain tests
        working-directory: ./cli
        run: |
          # TODO: maybe we can make a chainspec-tests directory which symlinks to selected test files
          yarn jest --config src/test/blockchain-tests.config.ts --silent --verbose --runInBand --forceExit src/test/blockchain-tests/danger-will-brick-the-blockchain.test.ts
        env:
          BLOCKCHAIN_TESTS_GLOBAL_SETUP: "./${{ matrix.chainspec }}ChainspecSetup.ts"

      - name: Kill nodes
        if: always()
        continue-on-error: true
        run: |
          # if all went well kill the node. Otherwise GitHub Actions would exit on the
          # previous step killing everything and we don't have to worry about
          # dangling processes
          killall -9 creditcoin3-node
