---
name: Check CC3 Devnet Snapshot

"on":
  schedule:
    # at 6am, 3rd of every month
    - cron: "0 6 3 * *"
  workflow_dispatch:

permissions: read-all

jobs:
  check-snapshot:
    # b/c of azure/login
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/check-snapshot.yml
    with:
      target-chain: "devnet"
      runs-on: "['ubuntu-24.04']"
    secrets: inherit
