---
name: Check Testnet Snapshot

"on":
  schedule:
    # at 08:30 on every 14th day-of-month
    - cron: "30 8 */14 * *"
  workflow_dispatch:

permissions: read-all

jobs:
  check-snapshot:
    # b/c of azure/login
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/check-snapshot.yml
    with:
      target-chain: "testnet"
      runs-on: "['ubuntu-24.04']"
    secrets: inherit
