---
name: Check Prover

"on":
  schedule:
    - cron: "0 */12 * * 1-5"
  workflow_dispatch:

permissions: read-all

jobs:
  check-for:
    strategy:
      fail-fast: false
      matrix:
        include:
          # CC3 Mainnet, Ethereum Mainnet, No Archive
          - creditcoinUrl: "wss://rpc.cc3-mainnet.creditcoin.network/ws"
            proverUrl: "https://proofbuilder.cc3-mainnet-usc.creditcoin.network"
            indexerUrl: "https://usc-graphql.cc3-mainnet.creditcoin.network"
            evmV1Decoder: "0x9D094C9f22B10FCf842c2fC6A0981630A4F94B5C"
            chainKey: 1

    name: CK ${{ matrix.chainKey }} / ${{ matrix.proverUrl }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: cli/yarn.lock
      - run: npm install -g yarn

      - name: Install Solidity compiler
        run: |
          sudo .github/install-solidity-compiler.sh

      - name: Generate precompiles ABI from source code
        working-directory: ./precompiles/metadata
        run: |
          solc --version
          ./abi-creator.sh

      - name: Install & build
        working-directory: ./cli
        run: |
          yarn install
          yarn build

      - name: Discover testing ENV
        id: test-env
        run: |
          NAME=$(echo "${{ matrix.creditcoinUrl }}" | sed "s/wss//" | sed "s/ws//" | tr -d "/" | tr -d ":" | sed "s/rpc.//" | sed "s/.creditcoin.network//")
          echo "chain-name=$NAME" >> "$GITHUB_OUTPUT"

      - name: Execute prover-check.ts around block 200000
        working-directory: ./cli
        env:
          LAST_SOURCE_BLOCK: '200001'
          GO_BACK_BLOCKS: '3'
          STEP_THROUGH_BLOCKS: '1'
        run: |
          node dist/scripts/prover-check.js \
            ${{ matrix.creditcoinUrl }} ${{ matrix.chainKey }} ${{ matrix.proverUrl }} \
            /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }} "" ${{ matrix.evmV1Decoder }}

      - name: Execute prover-check.ts around block 1150000
        working-directory: ./cli
        env:
          LAST_SOURCE_BLOCK: '1150001'
          GO_BACK_BLOCKS: '3'
          STEP_THROUGH_BLOCKS: '1'
        run: |
          node dist/scripts/prover-check.js \
            ${{ matrix.creditcoinUrl }} ${{ matrix.chainKey }} ${{ matrix.proverUrl }} \
            /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }} "" ${{ matrix.evmV1Decoder }}

      - name: Execute prover-check.ts around block 1920000
        working-directory: ./cli
        env:
          LAST_SOURCE_BLOCK: '1920001'
          GO_BACK_BLOCKS: '3'
          STEP_THROUGH_BLOCKS: '1'
        run: |
          node dist/scripts/prover-check.js \
            ${{ matrix.creditcoinUrl }} ${{ matrix.chainKey }} ${{ matrix.proverUrl }} \
            /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }} "" ${{ matrix.evmV1Decoder }}

      - name: Execute prover-check.ts around block 2463000
        working-directory: ./cli
        env:
          LAST_SOURCE_BLOCK: '2463001'
          GO_BACK_BLOCKS: '3'
          STEP_THROUGH_BLOCKS: '1'
        run: |
          node dist/scripts/prover-check.js \
            ${{ matrix.creditcoinUrl }} ${{ matrix.chainKey }} ${{ matrix.proverUrl }} \
            /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }} "" ${{ matrix.evmV1Decoder }}

      - name: Execute prover-check.ts around block 2675000
        working-directory: ./cli
        env:
          LAST_SOURCE_BLOCK: '2675001'
          GO_BACK_BLOCKS: '3'
          STEP_THROUGH_BLOCKS: '1'
        run: |
          node dist/scripts/prover-check.js \
            ${{ matrix.creditcoinUrl }} ${{ matrix.chainKey }} ${{ matrix.proverUrl }} \
            /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }} "" ${{ matrix.evmV1Decoder }}

      - name: Execute prover-check.ts around block 4370000
        working-directory: ./cli
        env:
          LAST_SOURCE_BLOCK: '4370001'
          GO_BACK_BLOCKS: '3'
          STEP_THROUGH_BLOCKS: '1'
        run: |
          node dist/scripts/prover-check.js \
            ${{ matrix.creditcoinUrl }} ${{ matrix.chainKey }} ${{ matrix.proverUrl }} \
            /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }} "" ${{ matrix.evmV1Decoder }}

      - name: Execute prover-check.ts around block 7280000
        working-directory: ./cli
        env:
          LAST_SOURCE_BLOCK: '7280001'
          GO_BACK_BLOCKS: '3'
          STEP_THROUGH_BLOCKS: '1'
        run: |
          node dist/scripts/prover-check.js \
            ${{ matrix.creditcoinUrl }} ${{ matrix.chainKey }} ${{ matrix.proverUrl }} \
            /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }} "" ${{ matrix.evmV1Decoder }}

      - name: Execute prover-check.ts around block 9069000
        working-directory: ./cli
        env:
          LAST_SOURCE_BLOCK: '9069001'
          GO_BACK_BLOCKS: '3'
          STEP_THROUGH_BLOCKS: '1'
        run: |
          node dist/scripts/prover-check.js \
            ${{ matrix.creditcoinUrl }} ${{ matrix.chainKey }} ${{ matrix.proverUrl }} \
            /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }} "" ${{ matrix.evmV1Decoder }}

      - name: Execute prover-check.ts around block 9200000
        working-directory: ./cli
        env:
          LAST_SOURCE_BLOCK: '9200001'
          GO_BACK_BLOCKS: '3'
          STEP_THROUGH_BLOCKS: '1'
        run: |
          node dist/scripts/prover-check.js \
            ${{ matrix.creditcoinUrl }} ${{ matrix.chainKey }} ${{ matrix.proverUrl }} \
            /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }} "" ${{ matrix.evmV1Decoder }}

      - name: Execute prover-check.ts around block 11052984
        working-directory: ./cli
        env:
          LAST_SOURCE_BLOCK: '11052985'
          GO_BACK_BLOCKS: '3'
          STEP_THROUGH_BLOCKS: '1'
        run: |
          node dist/scripts/prover-check.js \
            ${{ matrix.creditcoinUrl }} ${{ matrix.chainKey }} ${{ matrix.proverUrl }} \
            /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }} "" ${{ matrix.evmV1Decoder }}

      - name: Execute prover-check.ts around block 12244000
        working-directory: ./cli
        env:
          LAST_SOURCE_BLOCK: '12244001'
          GO_BACK_BLOCKS: '3'
          STEP_THROUGH_BLOCKS: '1'
        run: |
          node dist/scripts/prover-check.js \
            ${{ matrix.creditcoinUrl }} ${{ matrix.chainKey }} ${{ matrix.proverUrl }} \
            /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }} "" ${{ matrix.evmV1Decoder }}

      - name: Execute prover-check.ts around block 12965000
        working-directory: ./cli
        env:
          LAST_SOURCE_BLOCK: '12965001'
          GO_BACK_BLOCKS: '3'
          STEP_THROUGH_BLOCKS: '1'
        run: |
          node dist/scripts/prover-check.js \
            ${{ matrix.creditcoinUrl }} ${{ matrix.chainKey }} ${{ matrix.proverUrl }} \
            /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }} "" ${{ matrix.evmV1Decoder }}

      - name: Execute prover-check.ts around block 13773000
        working-directory: ./cli
        env:
          LAST_SOURCE_BLOCK: '13773001'
          GO_BACK_BLOCKS: '3'
          STEP_THROUGH_BLOCKS: '1'
        run: |
          node dist/scripts/prover-check.js \
            ${{ matrix.creditcoinUrl }} ${{ matrix.chainKey }} ${{ matrix.proverUrl }} \
            /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }} "" ${{ matrix.evmV1Decoder }}

      - name: Execute prover-check.ts around block 15050000
        working-directory: ./cli
        env:
          LAST_SOURCE_BLOCK: '15050001'
          GO_BACK_BLOCKS: '3'
          STEP_THROUGH_BLOCKS: '1'
        run: |
          node dist/scripts/prover-check.js \
            ${{ matrix.creditcoinUrl }} ${{ matrix.chainKey }} ${{ matrix.proverUrl }} \
            /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }} "" ${{ matrix.evmV1Decoder }}

      - name: Execute prover-check.ts around block 15537394
        working-directory: ./cli
        env:
          LAST_SOURCE_BLOCK: '15537395'
          GO_BACK_BLOCKS: '3'
          STEP_THROUGH_BLOCKS: '1'
        run: |
          node dist/scripts/prover-check.js \
            ${{ matrix.creditcoinUrl }} ${{ matrix.chainKey }} ${{ matrix.proverUrl }} \
            /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }} "" ${{ matrix.evmV1Decoder }}

      - name: Execute prover-check.ts around block 17034870
        working-directory: ./cli
        env:
          LAST_SOURCE_BLOCK: '17034871'
          GO_BACK_BLOCKS: '3'
          STEP_THROUGH_BLOCKS: '1'
        run: |
          node dist/scripts/prover-check.js \
            ${{ matrix.creditcoinUrl }} ${{ matrix.chainKey }} ${{ matrix.proverUrl }} \
            /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }} "" ${{ matrix.evmV1Decoder }}

      - name: Execute prover-check.ts around block 19426587
        working-directory: ./cli
        env:
          LAST_SOURCE_BLOCK: '19426588'
          GO_BACK_BLOCKS: '3'
          STEP_THROUGH_BLOCKS: '1'
        run: |
          node dist/scripts/prover-check.js \
            ${{ matrix.creditcoinUrl }} ${{ matrix.chainKey }} ${{ matrix.proverUrl }} \
            /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }} "" ${{ matrix.evmV1Decoder }}

      - name: Execute prover-check.ts around block 22431084
        working-directory: ./cli
        env:
          LAST_SOURCE_BLOCK: '22431085'
          GO_BACK_BLOCKS: '3'
          STEP_THROUGH_BLOCKS: '1'
        run: |
          node dist/scripts/prover-check.js \
            ${{ matrix.creditcoinUrl }} ${{ matrix.chainKey }} ${{ matrix.proverUrl }} \
            /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }} "" ${{ matrix.evmV1Decoder }}

      - name: Execute prover-check.ts around block 23935694
        working-directory: ./cli
        env:
          LAST_SOURCE_BLOCK: '23935694'
          GO_BACK_BLOCKS: '3'
          STEP_THROUGH_BLOCKS: '1'
        run: |
          node dist/scripts/prover-check.js \
            ${{ matrix.creditcoinUrl }} ${{ matrix.chainKey }} ${{ matrix.proverUrl }} \
            /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }} "" ${{ matrix.evmV1Decoder }}

      - name: Upload proofs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: proofs-for-${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }}
          path: /var/tmp/${{ steps.test-env.outputs.chain-name }}-ck-${{ matrix.chainKey }}

      - name: Report result to Slack
        if: always()
        uses: act10ns/slack@v2
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ job.status }}
          inputs: ${{ toJson(matrix) }}
          channel: "#noti-creditcoin-snapshots"
          message: "Checking CK(${{ matrix.chainKey }})@${{ matrix.proverUrl}} complete! cc <@U028EMRHS3S>"
