---
name: Check Testnet Snapshot

on:
  schedule:
    # at 08:30 on every 14th day-of-month
    - cron: "30 8 */14 * *"
  workflow_dispatch:

permissions: read-all

jobs:
  deploy-runner:
    uses: ./.github/workflows/deploy-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      LINODE_REGION: "us-ord"
      # Shared CPU, Linode 32 GB, 8 vCPU, disk: 640 GB, 0.288 $/hr
      LINODE_VM_SIZE: "g6-standard-8"
      proxy_type: "testnet"
    secrets: inherit

  check-snapshot:
    needs:
      - deploy-runner
    uses: ./.github/workflows/check-snapshot.yml
    with:
      target-chain: "testnet"
      runs-on: "['self-hosted', 'workflow-${{ github.run_id }}', 'type-testnet']"
    secrets: inherit

  remove-runner:
    needs:
      - deploy-runner
      - check-snapshot
    if: ${{ always() }}
    uses: ./.github/workflows/remove-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      proxy_type: "testnet"
    secrets: inherit
