---
name: Linode Cleaner

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # every hour

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  linode-cleaner:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Remove VMs
        continue-on-error: true
        run: |
          .github/remove-linode-vm.sh
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
