---
name: proof-gen-api-server

"on":
  pull_request:
    paths:
      - 'proof-gen-api-server/**'
      - '.github/workflows/proof-gen-api-server.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  e2e-test:
    needs:
      - deploy-runner-proof-gen-api-server-e2e-test
    runs-on:
      [
        self-hosted,
        "workflow-${{ github.run_id }}",
        "proxy-proof-gen-api-server-e2e-test",
      ]
    steps:
      - uses: actions/checkout@v6

      - name: Install Anvil
        run: |
          # first install it
          curl -L https://foundry.paradigm.xyz | bash
          ~/.foundry/bin/foundryup

          ANVIL_BIN=$(readlink -f ~/.foundry/bin/anvil)
          echo "ANVIL_BIN=$ANVIL_BIN" >> "$GITHUB_ENV"

          CAST_BIN=$(readlink -f ~/.foundry/bin/cast)
          echo "CAST_BIN=$CAST_BIN" >> "$GITHUB_ENV"

      - name: Install protobuf
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          targets: wasm32-unknown-unknown
          components: rust-src

      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: |
          cargo test --release --package proof-gen-api-server --features e2e-tests -- --nocapture
        env:
          ANVIL_BIN: ${{ env.ANVIL_BIN }}
          CAST_BIN: ${{ env.CAST_BIN }}

  deploy-runner-proof-gen-api-server-e2e-test:
    uses: ./.github/workflows/deploy-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      LINODE_REGION: "nl-ams"
      LINODE_VM_SIZE: "g6-standard-4"
      proxy: "proof-gen-api-server-e2e-test"
    secrets: inherit

  rm-gh-runner-proof-gen-api-server-e2e-test:
    needs:
      - e2e-test
    if: ${{ always() }}
    uses: ./.github/workflows/remove-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      proxy: "proof-gen-api-server-e2e-test"
    secrets: inherit
