---
name: Build Release Artifacts

on:
  push:
    tags:
      - "*"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

env:
  RUNNER_VM_NAME: "${{ github.event.repository.name }}-$GITHUB_RUN_ID-attempt-$GITHUB_RUN_ATTEMPT"
  LINODE_REGION: "nl-ams"
  # Shared CPU, Linode 8 GB, 4 vCPU, 96 $/mo
  LINODE_VM_SIZE: "g6-standard-4"

jobs:
  sanity-check:
    runs-on: ubuntu-24.04
    outputs:
      TAG_NAME: ${{ steps.identify-tag.outputs.TAG_NAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Figure out tag name
        id: identify-tag
        shell: bash
        run: |
          TAG_NAME=$(git describe --tag)
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_OUTPUT"

      - name: Sanity check tag name suffix
        run: |
          echo "${{ env.TAG_NAME }}" | grep -E "mainnet|testnet|devnet"
          # TODO: reenable when we start releasing from the dev branch
          # .github/check-tag-suffix-vs-origin-branch.sh

      - name: Check tag name vs. Cargo.toml version
        run: |
          ./.github/check-version-vs-git-tag.sh

  setup:
    runs-on: ubuntu-24.04
    needs: sanity-check
    outputs:
      build_options: ${{ steps.set-build-options.outputs.build_options}}
    steps:
      - name: Set build options
        id: set-build-options
        shell: bash
        run: |
          echo "build_options=${{ contains( needs.sanity-check.outputs.TAG_NAME, 'devnet') && '--features devnet --features fast-runtime' || '' }}" >> "$GITHUB_OUTPUT"

      - name: View the build options
        shell: bash
        run: |
          echo "build_options = ${{ steps.set-build-options.outputs.build_options}}"

  deploy-github-runner:
    timeout-minutes: 15
    needs:
      - sanity-check
      - setup
    strategy:
      fail-fast: false
      matrix:
        include:
          # runners for other jobs (repurpose existing labels)
          - build: docker
          - build: native
          - build: wasm

    name: deploy-github-runner / ${{ matrix.build }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      # See https://github.com/actions/runner/issues/1879#issuecomment-1123196869
      - name: Create matrix.txt
        run: |
          echo "${{ matrix.build }}" > matrix.txt

      - name: Evaluate env vars
        id: get-env
        run: |
          HASH_VALUE=$(echo "${{ hashFiles('matrix.txt') }}" | cut -c1-7)
          rm matrix.txt

          # WARNING: using env.RUNNER_VM_NAME directly in job outputs above
          # doesn't evaluate the $GITHUB_RUN_ID reference
          echo "runner_vm_name=${{ env.RUNNER_VM_NAME }}-$HASH_VALUE" >> "$GITHUB_OUTPUT"

      - name: Provision VM
        if: env.LC_GITHUB_REPO_ADMIN_TOKEN
        run: |
          .github/provision-linode-vm.sh
        env:
          LC_OWNER_REPO_SLUG: ${{ github.repository }}
          LC_GITHUB_REPO_ADMIN_TOKEN: ${{ secrets.GH_REPO_ADMIN_TOKEN }}
          LC_RUNNER_VM_NAME: ${{ steps.get-env.outputs.runner_vm_name }}
          LC_PROXY_TYPE: ${{ matrix.build }}
          LC_WORKFLOW_ID: ${{ github.run_id }}
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}

  build-native-runtime:
    needs:
      - sanity-check
      - setup
      - deploy-github-runner
    runs-on: [self-hosted, "workflow-${{ github.run_id }}", "type-native"]
    steps:
      - uses: actions/checkout@v4

      - name: Install protobuf
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure rustc version
        shell: bash
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          targets: wasm32-unknown-unknown
          components: rust-src

      - uses: Swatinem/rust-cache@v2

      - name: Figure out platform
        shell: bash
        run: |
          PLATFORM=$(rustup target list --installed | grep "$(uname -m)")
          echo "PLATFORM=$PLATFORM" >> "$GITHUB_ENV"

      - name: DEBUG
        shell: bash
        run: |
          echo "Tag & Platform is '${{ needs.sanity-check.outputs.TAG_NAME }}-${{ env.PLATFORM }}'"

      - name: Build
        continue-on-error: true
        uses: gluwa/cargo@dev
        with:
          command: build
          args: --release ${{ needs.setup.outputs.build_options}}

      - name: Compress
        continue-on-error: true
        uses: thedoctor0/zip-release@0.7.6
        with:
          command: "sudo apt-get install zip"
          type: "zip"
          directory: "target/release/"
          path: "creditcoin3-node*"
          filename: "../../creditcoin-${{ needs.sanity-check.outputs.TAG_NAME  }}-${{ env.PLATFORM }}.zip"
          exclusions: "creditcoin3-node.d"

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: binary-for-linux
          path: "creditcoin-${{ needs.sanity-check.outputs.TAG_NAME  }}-*.zip"
          if-no-files-found: warn

  build-wasm-runtime:
    needs:
      - sanity-check
      - setup
      - deploy-github-runner
    runs-on: [self-hosted, "workflow-${{ github.run_id }}", "type-wasm"]
    steps:
      - uses: actions/checkout@v4

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Workaround for paritytech/srtool uid/gid mismatch
        run: |
          sudo chown -R 1001:1001 ${{ github.workspace }}

      - name: Build WASM runtime
        id: srtool_build
        uses: chevdor/srtool-actions@v0.9.2
        env:
          BUILD_OPTS: "--release ${{ needs.setup.outputs.build_options }}"
        with:
          chain: "creditcoin"
          runtime_dir: runtime
          package: creditcoin3-runtime
          tag: ${{ env.RUSTC_VERSION }}
          workdir: ${{ github.workspace }}

      - name: DEBUG
        run: |
          # revert workaround for paritytech/srtool uid/gid mismatch
          sudo chown -R "$USER:$USER" ${{ github.workspace }}

          echo '${{ steps.srtool_build.outputs.json }}' | jq . > creditcoin-srtool-digest.json
          cat creditcoin-srtool-digest.json
          echo "Runtime location: ${{ steps.srtool_build.outputs.wasm }}"

      - name: Rename file
        run: |
          mv ${{ steps.srtool_build.outputs.wasm }} creditcoin-${{ needs.sanity-check.outputs.TAG_NAME  }}-runtime.wasm

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: binary-for-wasm
          path: "*.wasm"
          if-no-files-found: error

  docker-build:
    needs:
      - sanity-check
      - setup
      - deploy-github-runner
    runs-on: [self-hosted, "workflow-${{ github.run_id }}", "type-docker"]
    steps:
      - uses: actions/checkout@v4

      - name: Figure out tag name
        shell: bash
        run: |
          TAG_NAME=$(git describe --tag)
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"

      - name: Build ${{ github.repository }} docker image
        run: |
          docker build -t ${{ github.repository }}:${{needs.sanity-check.outputs.TAG_NAME }} --build-arg="BUILD_ARGS=${{ needs.setup.outputs.build_options }}" .

          echo "${{ secrets.DOCKER_PUSH_PASSWORD }}" | docker login -u="${{ secrets.DOCKER_PUSH_USERNAME }}" --password-stdin
          docker push ${{ github.repository }}:${{ needs.sanity-check.outputs.TAG_NAME }}

          # only -mainnet images are tagged as :latest
          # shellcheck disable=SC2046,SC2143
          if [ $(echo "${{ needs.sanity-check.outputs.TAG_NAME }}" | grep "mainnet") ]; then
              docker tag ${{ github.repository }}:${{ needs.sanity-check.outputs.TAG_NAME }} ${{ github.repository }}:latest
              docker push ${{ github.repository }}:latest
          fi

          docker logout
          docker images

      - name: Build ${{ github.repository }}:indexer-for-${{ needs.sanity-check.outputs.TAG_NAME }} docker image
        working-directory: ./cc3-indexer
        run: |
          tar --create --dereference --exclude-from=.dockerignore . | docker build -t ${{ github.repository }}:indexer-for-${{ github.sha }} -

          echo "${{ secrets.DOCKER_PUSH_PASSWORD }}" | docker login -u="${{ secrets.DOCKER_PUSH_USERNAME }}" --password-stdin
          docker push ${{ github.repository }}:indexer-for-${{ needs.sanity-check.outputs.TAG_NAME }}
          # NOTE: not tagging indexer as `:latest` b/c it is not the primary image in this repository!

          docker logout
          docker images

  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    needs:
      - sanity-check
      - build-native-runtime
      - build-wasm-runtime
    steps:
      - uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          path: artifact
          pattern: binary-for-*
          merge-multiple: true

      - name: DEBUG
        shell: bash
        run: |
          ls -lR

      - name: Make the release
        uses: softprops/action-gh-release@v2
        with:
          files: "artifact/creditcoin-*${{ needs.sanity-check.outputs.TAG_NAME }}*"
          fail_on_unmatched_files: true
          name: ${{ needs.sanity-check.outputs.TAG_NAME  }}

  rm-gh-runner-docker:
    runs-on: ubuntu-24.04
    needs:
      - docker-build
    if: ${{ always() }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - build: docker

    steps:
      - uses: actions/checkout@v4

      # See https://github.com/actions/runner/issues/1879#issuecomment-1123196869
      - name: Create matrix.txt
        run: |
          echo "${{ matrix.build }}" > matrix.txt

      - name: Evaluate env vars
        id: get-env
        run: |
          HASH_VALUE=$(echo "${{ hashFiles('matrix.txt') }}" | cut -c1-7)
          rm matrix.txt

          echo "runner_vm_name=${{ env.RUNNER_VM_NAME }}-$HASH_VALUE" >> "$GITHUB_OUTPUT"

      - name: Remove VM
        continue-on-error: true
        run: |
          .github/remove-linode-vm.sh
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
          LC_RUNNER_VM_NAME: ${{ steps.get-env.outputs.runner_vm_name }}

  rm-gh-runner-native:
    runs-on: ubuntu-24.04
    needs:
      - build-native-runtime
    if: ${{ always() }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - build: native

    steps:
      - uses: actions/checkout@v4

      # See https://github.com/actions/runner/issues/1879#issuecomment-1123196869
      - name: Create matrix.txt
        run: |
          echo "${{ matrix.build }}" > matrix.txt

      - name: Evaluate env vars
        id: get-env
        run: |
          HASH_VALUE=$(echo "${{ hashFiles('matrix.txt') }}" | cut -c1-7)
          rm matrix.txt

          echo "runner_vm_name=${{ env.RUNNER_VM_NAME }}-$HASH_VALUE" >> "$GITHUB_OUTPUT"

      - name: Remove VM
        continue-on-error: true
        run: |
          .github/remove-linode-vm.sh
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
          LC_RUNNER_VM_NAME: ${{ steps.get-env.outputs.runner_vm_name }}

  rm-gh-runner-wasm:
    runs-on: ubuntu-24.04
    needs:
      - build-wasm-runtime
    if: ${{ always() }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - build: wasm

    steps:
      - uses: actions/checkout@v4

      # See https://github.com/actions/runner/issues/1879#issuecomment-1123196869
      - name: Create matrix.txt
        run: |
          echo "${{ matrix.build }}" > matrix.txt

      - name: Evaluate env vars
        id: get-env
        run: |
          HASH_VALUE=$(echo "${{ hashFiles('matrix.txt') }}" | cut -c1-7)
          rm matrix.txt

          echo "runner_vm_name=${{ env.RUNNER_VM_NAME }}-$HASH_VALUE" >> "$GITHUB_OUTPUT"

      - name: Remove VM
        continue-on-error: true
        run: |
          .github/remove-linode-vm.sh
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
          LC_RUNNER_VM_NAME: ${{ steps.get-env.outputs.runner_vm_name }}
