---
name: Build Release Artifacts

"on":
  push:
    tags:
      - "*"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

env:
  RUNNER_VM_NAME: "${{ github.event.repository.name }}-$GITHUB_RUN_ID-attempt-$GITHUB_RUN_ATTEMPT"
  LINODE_REGION: "nl-ams"
  # Shared CPU, Linode 8 GB, 4 vCPU, 96 $/mo
  LINODE_VM_SIZE: "g6-standard-4"

jobs:
  sanity-check:
    runs-on: ubuntu-24.04
    outputs:
      TAG_NAME: ${{ steps.identify-tag.outputs.TAG_NAME }}
    steps:
      - name: Report to Slack
        uses: act10ns/slack@v2
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ job.status }}
          channel: "#protocol-internal"
          message: "Release pipeline started! cc <@U028EMRHS3S>"

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Figure out tag name
        id: identify-tag
        shell: bash
        run: |
          TAG_NAME=$(git describe --tag)
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_OUTPUT"

      - name: Sanity check tag name suffix
        run: |
          echo "${{ env.TAG_NAME }}" | grep -E "mainnet|testnet|devnet"
          # TODO: reenable when we start releasing from the dev branch
          # .github/check-tag-suffix-vs-origin-branch.sh

      - name: Check tag name vs. Cargo.toml version
        run: |
          ./.github/check-version-vs-git-tag.sh

      - name: Install Solidity compiler
        run: |
          sudo .github/install-solidity-compiler.sh

      - name: Generate precompiles ABI from source code
        working-directory: ./precompiles/metadata
        run: |
          solc --version
          ./abi-creator.sh

      - name: Install openzeppelin dependencies
        working-directory: ./common/eth/contracts/
        run: |
          npm install

      - name: Compile Hardhat contract(s)
        working-directory: ./docs/smart-contract-development/with-hardhat
        run: |
          npm install
          npx hardhat compile

      - name: Check if tag name is a valid NPM version
        working-directory: ./cli
        run: |
          yarn install
          yarn build
          node dist/scripts/npm-semver-check.js "${{ env.TAG_NAME }}"

  setup:
    runs-on: ubuntu-24.04
    needs: sanity-check
    outputs:
      build_options: ${{ steps.set-build-options.outputs.build_options}}
      previous_release: ${{ steps.devnet-env.outputs.previous_release || steps.testnet-env.outputs.previous_release || steps.mainnet-env.outputs.previous_release }}

    steps:
      - uses: actions/checkout@v5

      - name: Set-Up
        run: |
          sudo apt-get update
          sudo apt install -y jq

      - name: Set build options
        id: set-build-options
        shell: bash
        run: |
          echo "build_options=${{ contains( needs.sanity-check.outputs.TAG_NAME, 'devnet') && '--features fast-runtime' || '' }}" >> "$GITHUB_OUTPUT"

      - name: View the build options
        shell: bash
        run: |
          echo "build_options = ${{ steps.set-build-options.outputs.build_options }}"

      - name: Devnet ENV
        id: devnet-env
        if: contains( needs.sanity-check.outputs.TAG_NAME, 'devnet')
        run: |
          # shellcheck disable=SC2129
          PREV_RELEASE=$(.github/extract-release-tag.sh "devnet")
          echo "previous_release=$PREV_RELEASE" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Testnet ENV
        id: testnet-env
        if: contains( needs.sanity-check.outputs.TAG_NAME, 'testnet')
        run: |
          # shellcheck disable=SC2129
          PREV_RELEASE=$(.github/extract-release-tag.sh "testnet")
          echo "previous_release=$PREV_RELEASE" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Mainnet ENV
        id: mainnet-env
        if: contains( needs.sanity-check.outputs.TAG_NAME, 'mainnet')
        run: |
          # shellcheck disable=SC2129
          PREV_RELEASE=$(.github/extract-release-tag.sh "mainnet")
          echo "previous_release=$PREV_RELEASE" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

  generate-changelog:
    runs-on: ubuntu-24.04
    needs: setup
    steps:
      - uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          always-auth: true
          scope: "@gluwa"
      - run: npm install -g yarn

      - name: Install
        run: yarn install

      - name: Generate Changelog
        id: generate-changelog
        run: |
          yarn conventional-changelog -p conventionalcommits -r 1 -u -o /var/tmp/changelog.md

          echo "===== DEBUG ====="
          cat /var/tmp/changelog.md
          echo "===== END ====="

      - name: Download smart-contract artifact(s) for release ${{ needs.setup.outputs.previous_release }}
        uses: i3h/download-release-asset@v1
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          tag: ${{ needs.setup.outputs.previous_release }}
          file: /(.*)\.sol/
          path: common/eth/contracts/sol/
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compare current Prover.sol with previously released artifact(s)
        working-directory: ./common/eth/contracts/sol/
        run: |
          # shellcheck disable=SC2129
          sudo apt-get install colordiff
          echo "========== DEBUG DEBUG DEBUG =========="
          git status --short --untracked-files=no
          git diff -R | colordiff
          echo "======================================="

          echo "**Changes to Prover.sol:**" >> /var/tmp/changelog.md
          echo "" >> /var/tmp/changelog.md
          echo "\`\`\`diff" >> /var/tmp/changelog.md

          git diff -R >> /var/tmp/changelog.md

          echo "\`\`\`" >> /var/tmp/changelog.md

      - name: Upload changelog
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: /var/tmp/changelog.md
          if-no-files-found: error

  deploy-github-runner:
    timeout-minutes: 15
    needs:
      - sanity-check
      - setup
    strategy:
      fail-fast: false
      matrix:
        include:
          # runners for other jobs (repurpose existing labels)
          - build: docker
          - build: native
          - build: wasm

    name: deploy-github-runner / ${{ matrix.build }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      # See https://github.com/actions/runner/issues/1879#issuecomment-1123196869
      - name: Create matrix.txt
        run: |
          echo "${{ matrix.build }}" > matrix.txt

      - name: Evaluate env vars
        id: get-env
        run: |
          HASH_VALUE=$(echo "${{ hashFiles('matrix.txt') }}" | cut -c1-7)
          rm matrix.txt

          # WARNING: using env.RUNNER_VM_NAME directly in job outputs above
          # doesn't evaluate the $GITHUB_RUN_ID reference
          echo "runner_vm_name=${{ env.RUNNER_VM_NAME }}-$HASH_VALUE" >> "$GITHUB_OUTPUT"

      - name: Provision VM
        if: env.LC_GITHUB_REPO_ADMIN_TOKEN
        run: |
          .github/provision-linode-vm.sh
        env:
          LC_OWNER_REPO_SLUG: ${{ github.repository }}
          LC_GITHUB_REPO_ADMIN_TOKEN: ${{ secrets.GH_REPO_ADMIN_TOKEN }}
          LC_RUNNER_VM_NAME: ${{ steps.get-env.outputs.runner_vm_name }}
          LC_PROXY_TYPE: ${{ matrix.build }}
          LC_WORKFLOW_ID: ${{ github.run_id }}
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}

  build-npm-package:
    needs:
      - sanity-check
      - setup
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          always-auth: true
          scope: "@gluwa"

      - name: Build @gluwa/creditcoin-public-prover package
        working-directory: common/eth/contracts/
        run: |
          # WARNING: always use the same tag name as the release
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ needs.sanity-check.outputs.TAG_NAME }}\"/" package*.json
          git diff
          npm install -g npm@latest
          npm install
          npm pack

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: binary-for-npm-creditcoin-public-prover
          path: "common/eth/contracts/gluwa-creditcoin-public-prover-${{ needs.sanity-check.outputs.TAG_NAME }}.tgz"
          compression-level: 0
          if-no-files-found: error

      - name: Publish @gluwa/creditcoin-public-prover package
        working-directory: common/eth/contracts/
        run: |
          npm publish --access public --verbose

      - name: Upload smart contract(s)
        uses: actions/upload-artifact@v4
        with:
          name: smart-contracts
          path: |
            common/eth/contracts/sol/*.sol
            common/eth/contracts/prover.json
            common/eth/contracts/.bytecode.hash
          if-no-files-found: warn
          include-hidden-files: true

  build-native-runtime:
    needs:
      - sanity-check
      - setup
      - deploy-github-runner
    uses: ./.github/workflows/build-native.yml
    with:
      build-options: "--release ${{ needs.setup.outputs.build_options}}"
      version-string: "${{ needs.sanity-check.outputs.TAG_NAME }}-x86_64-unknown-linux-gnu"
      runs-on: "['self-hosted', 'workflow-${{ github.run_id }}', 'type-native']"
    secrets: inherit

  build-wasm-runtime:
    needs:
      - sanity-check
      - setup
      - deploy-github-runner
    uses: ./.github/workflows/build-wasm.yml
    with:
      build-options: "${{ needs.setup.outputs.build_options }}"
      version-string: ${{ needs.sanity-check.outputs.TAG_NAME }}
      runs-on: "['self-hosted', 'workflow-${{ github.run_id }}', 'type-wasm']"

  docker-build:
    needs:
      - sanity-check
      - setup
      - deploy-github-runner
    uses: ./.github/workflows/build-docker.yml
    with:
      build-options: "BUILD_ARGS=${{ needs.setup.outputs.build_options }}"
      version-string: ${{ needs.sanity-check.outputs.TAG_NAME }}
      runs-on: "['self-hosted', 'workflow-${{ github.run_id }}', 'type-docker']"
    secrets: inherit

  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    needs:
      - sanity-check
      - generate-changelog
      - build-native-runtime
      - build-wasm-runtime
      - build-npm-package
      - docker-build
    steps:
      - uses: actions/checkout@v5

      - name: Download binaries
        uses: actions/download-artifact@v5
        with:
          path: artifact
          pattern: binary-for-*
          merge-multiple: true

      - name: Download changelog
        uses: actions/download-artifact@v5
        with:
          pattern: changelog

      - name: Download smart contract(s)
        uses: actions/download-artifact@v5
        with:
          path: artifact
          pattern: smart-contracts
          merge-multiple: true

      - name: Rename files to improve visibility
        shell: bash
        run: |
          mv artifact/prover.json artifact/Prover-ABI.json
          mv artifact/.bytecode.hash artifact/Prover-bytecode-hash.txt

      - name: Compress native binaries
        shell: bash
        working-directory: artifact/
        run: |
          # -m removes the uncompressed file b/c we don't want to be uploading it
          zip -m "creditcoin-${{ needs.sanity-check.outputs.TAG_NAME }}-$(uname -m)-unknown-linux-gnu.zip" creditcoin3-node

          # -m removes the uncompressed files b/c we don't want to be uploading them
          zip -m "attestor-binaries-${{ needs.sanity-check.outputs.TAG_NAME }}-$(uname -m)-unknown-linux-gnu.zip" attestor*

          ls -lR

      - name: Make the release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifact/attestor-binaries-${{ needs.sanity-check.outputs.TAG_NAME }}*
            artifact/creditcoin-${{ needs.sanity-check.outputs.TAG_NAME }}*
            artifact/gluwa-creditcoin-public-prover-${{ needs.sanity-check.outputs.TAG_NAME }}.tgz
            artifact/sol/*.sol
            artifact/Prover-ABI.json
            artifact/Prover-bytecode-hash.txt
          fail_on_unmatched_files: true
          name: ${{ needs.sanity-check.outputs.TAG_NAME  }}
          body_path: changelog.md

      - name: Report result to Slack
        if: always()
        uses: act10ns/slack@v2
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ job.status }}
          channel: "#protocol-internal"
          message: "Release pipeline finished! cc <@U028EMRHS3S>"

  rm-gh-runner-docker:
    runs-on: ubuntu-24.04
    needs:
      - docker-build
    if: ${{ always() }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - build: docker

    steps:
      - uses: actions/checkout@v5

      # See https://github.com/actions/runner/issues/1879#issuecomment-1123196869
      - name: Create matrix.txt
        run: |
          echo "${{ matrix.build }}" > matrix.txt

      - name: Evaluate env vars
        id: get-env
        run: |
          HASH_VALUE=$(echo "${{ hashFiles('matrix.txt') }}" | cut -c1-7)
          rm matrix.txt

          echo "runner_vm_name=${{ env.RUNNER_VM_NAME }}-$HASH_VALUE" >> "$GITHUB_OUTPUT"

      - name: Remove VM
        continue-on-error: true
        run: |
          .github/remove-linode-vm.sh
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
          LC_RUNNER_VM_NAME: ${{ steps.get-env.outputs.runner_vm_name }}

  rm-gh-runner-native:
    runs-on: ubuntu-24.04
    needs:
      - build-native-runtime
    if: ${{ always() }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - build: native

    steps:
      - uses: actions/checkout@v5

      # See https://github.com/actions/runner/issues/1879#issuecomment-1123196869
      - name: Create matrix.txt
        run: |
          echo "${{ matrix.build }}" > matrix.txt

      - name: Evaluate env vars
        id: get-env
        run: |
          HASH_VALUE=$(echo "${{ hashFiles('matrix.txt') }}" | cut -c1-7)
          rm matrix.txt

          echo "runner_vm_name=${{ env.RUNNER_VM_NAME }}-$HASH_VALUE" >> "$GITHUB_OUTPUT"

      - name: Remove VM
        continue-on-error: true
        run: |
          .github/remove-linode-vm.sh
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
          LC_RUNNER_VM_NAME: ${{ steps.get-env.outputs.runner_vm_name }}

  rm-gh-runner-wasm:
    runs-on: ubuntu-24.04
    needs:
      - build-wasm-runtime
    if: ${{ always() }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - build: wasm

    steps:
      - uses: actions/checkout@v5

      # See https://github.com/actions/runner/issues/1879#issuecomment-1123196869
      - name: Create matrix.txt
        run: |
          echo "${{ matrix.build }}" > matrix.txt

      - name: Evaluate env vars
        id: get-env
        run: |
          HASH_VALUE=$(echo "${{ hashFiles('matrix.txt') }}" | cut -c1-7)
          rm matrix.txt

          echo "runner_vm_name=${{ env.RUNNER_VM_NAME }}-$HASH_VALUE" >> "$GITHUB_OUTPUT"

      - name: Remove VM
        continue-on-error: true
        run: |
          .github/remove-linode-vm.sh
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
          LC_RUNNER_VM_NAME: ${{ steps.get-env.outputs.runner_vm_name }}
