---
name: Build Release Artifacts

"on":
  push:
    tags:
      - "*"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  sanity-check:
    runs-on: ubuntu-24.04
    outputs:
      TAG_NAME: ${{ steps.identify-tag.outputs.TAG_NAME }}
    steps:
      - name: Report to Slack
        uses: act10ns/slack@v2
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ job.status }}
          channel: "#protocol-internal"
          message: "Release pipeline started! cc <@U028EMRHS3S>"

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Figure out tag name
        id: identify-tag
        shell: bash
        run: |
          TAG_NAME=$(git describe --tag)
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_OUTPUT"

      - name: Sanity check tag name suffix
        run: |
          echo "${{ env.TAG_NAME }}" | grep -E "mainnet|testnet|devnet"
          # TODO: reenable when we start releasing from the dev branch
          # .github/check-tag-suffix-vs-origin-branch.sh

      - name: Check tag name vs. Cargo.toml version
        run: |
          ./.github/check-version-vs-git-tag.sh

      - name: Install Solidity compiler
        run: |
          sudo .github/install-solidity-compiler.sh

      - name: Generate precompiles ABI from source code
        working-directory: ./precompiles/metadata
        run: |
          solc --version
          ./abi-creator.sh

      - name: Check if tag name is a valid NPM version
        working-directory: ./cli
        run: |
          yarn install
          yarn build
          node dist/scripts/npm-semver-check.js "${{ env.TAG_NAME }}"

  setup:
    runs-on: ubuntu-24.04
    needs: sanity-check
    outputs:
      build_options: ${{ steps.set-build-options.outputs.build_options}}
      previous_release: ${{ steps.devnet-env.outputs.previous_release || steps.testnet-env.outputs.previous_release || steps.mainnet-env.outputs.previous_release }}

    steps:
      - uses: actions/checkout@v6

      - name: Set-Up
        run: |
          sudo apt-get update
          sudo apt install -y jq

      - name: Set build options
        id: set-build-options
        shell: bash
        run: |
          echo "build_options=${{ contains( needs.sanity-check.outputs.TAG_NAME, 'devnet') && '--features devnet --features fast-runtime' || '' }}" >> "$GITHUB_OUTPUT"

      - name: View the build options
        shell: bash
        run: |
          echo "build_options = ${{ steps.set-build-options.outputs.build_options }}"

      - name: Devnet ENV
        id: devnet-env
        if: contains( needs.sanity-check.outputs.TAG_NAME, 'devnet')
        run: |
          # shellcheck disable=SC2129
          PREV_RELEASE=$(.github/extract-release-tag.sh "devnet")
          echo "previous_release=$PREV_RELEASE" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Testnet ENV
        id: testnet-env
        if: contains( needs.sanity-check.outputs.TAG_NAME, 'testnet')
        run: |
          # shellcheck disable=SC2129
          PREV_RELEASE=$(.github/extract-release-tag.sh "testnet")
          echo "previous_release=$PREV_RELEASE" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Mainnet ENV
        id: mainnet-env
        if: contains( needs.sanity-check.outputs.TAG_NAME, 'mainnet')
        run: |
          # shellcheck disable=SC2129
          PREV_RELEASE=$(.github/extract-release-tag.sh "mainnet")
          echo "previous_release=$PREV_RELEASE" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

  generate-changelog:
    needs: setup
    uses: ./.github/workflows/generate-changelog.yml
    with:
      previous-release: "${{ needs.setup.outputs.previous_release }}"
    secrets: inherit

  deploy-github-runner:
    needs:
      - sanity-check
      - setup
    strategy:
      fail-fast: false
      matrix:
        include:
          # runners for other jobs (repurpose existing labels)
          - build: docker
          - build: native
          - build: wasm
    uses: ./.github/workflows/deploy-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      LINODE_REGION: "nl-ams"
      LINODE_VM_SIZE: "g6-standard-4"
      proxy_type: ${{ matrix.build }}
    secrets: inherit

  build-native-runtime:
    needs:
      - sanity-check
      - setup
      - deploy-github-runner
    uses: ./.github/workflows/build-native.yml
    with:
      build-options: "--release ${{ needs.setup.outputs.build_options}}"
      version-string: "${{ needs.sanity-check.outputs.TAG_NAME }}-x86_64-unknown-linux-gnu"
      runs-on: "['self-hosted', 'workflow-${{ github.run_id }}', 'type-native']"
    secrets: inherit

  build-wasm-runtime:
    needs:
      - sanity-check
      - setup
      - deploy-github-runner
    uses: ./.github/workflows/build-wasm.yml
    with:
      build-options: "${{ needs.setup.outputs.build_options }}"
      version-string: ${{ needs.sanity-check.outputs.TAG_NAME }}
      runs-on: "['self-hosted', 'workflow-${{ github.run_id }}', 'type-wasm']"

  docker-build:
    needs:
      - sanity-check
      - setup
      - deploy-github-runner
    uses: ./.github/workflows/build-docker.yml
    with:
      build-options: "BUILD_ARGS=${{ needs.setup.outputs.build_options }}"
      version-string: ${{ needs.sanity-check.outputs.TAG_NAME }}
      runs-on: "['self-hosted', 'workflow-${{ github.run_id }}', 'type-docker']"
    secrets: inherit

  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    needs:
      - sanity-check
      - generate-changelog
      - build-native-runtime
      - build-wasm-runtime
      - docker-build
    steps:
      - uses: actions/checkout@v6

      - name: Download binaries
        uses: actions/download-artifact@v7
        with:
          path: artifact
          pattern: binary-for-*
          merge-multiple: true

      - name: Download changelog
        uses: actions/download-artifact@v7
        with:
          pattern: changelog

      - name: Compress native binaries
        shell: bash
        working-directory: artifact/
        run: |
          # NOTE: -m removes the uncompressed file(s) b/c we don't want to be uploading them
          zip -m "creditcoin-${{ needs.sanity-check.outputs.TAG_NAME }}-$(uname -m)-unknown-linux-gnu.zip" creditcoin3-node
          zip -m "attestor-binaries-${{ needs.sanity-check.outputs.TAG_NAME }}-$(uname -m)-unknown-linux-gnu.zip" attestor*
          zip -m "proof-gen-api-server-${{ needs.sanity-check.outputs.TAG_NAME }}-$(uname -m)-unknown-linux-gnu.zip" proof-gen-api-server

          ls -lR

      - name: Install Solidity compiler
        run: |
          sudo .github/install-solidity-compiler.sh

      - name: Generate precompiles ABI from source code
        working-directory: ./precompiles/metadata
        run: |
          solc --version
          ./abi-creator.sh

      - name: Make the release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifact/attestor-binaries-${{ needs.sanity-check.outputs.TAG_NAME }}*
            artifact/creditcoin-${{ needs.sanity-check.outputs.TAG_NAME }}*
            artifact/proof-gen-api-server-${{ needs.sanity-check.outputs.TAG_NAME }}*
            precompiles/metadata/abi/*.json
          fail_on_unmatched_files: true
          name: ${{ needs.sanity-check.outputs.TAG_NAME  }}
          body_path: changelog.md

      - name: Report result to Slack
        if: always()
        uses: act10ns/slack@v2
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ job.status }}
          channel: "#protocol-internal"
          message: "Release pipeline finished! cc <@U028EMRHS3S>"

  rm-gh-runner-docker:
    needs:
      - docker-build
    uses: ./.github/workflows/remove-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      proxy_type: "docker"
    secrets: inherit

  rm-gh-runner-native:
    needs:
      - build-native-runtime
    uses: ./.github/workflows/remove-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      proxy_type: "native"
    secrets: inherit

  rm-gh-runner-wasm:
    needs:
      - build-wasm-runtime
    uses: ./.github/workflows/remove-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      proxy_type: "wasm"
    secrets: inherit
