---
name: rust

"on":
  pull_request:
    branches: [main, testnet, poc_external_attestation_network]
    paths:
      - "**.rs"
      - "**.toml"
      - "**Cargo**"
      - ".github/workflows/rust.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  cargo-audit:
    if: github.base_ref == 'dev'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Install protobuf
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo audit
        run: |
          cargo install cargo-audit --features=fix --locked

      - name: Run cargo audit
        run: |
          cargo audit || true
          CC_MATCH=$(cargo audit --color never | grep -E "^.── creditcoin3-node" || true)

          # fail for anything which is a 1st level dependency of Creditcoin
          if [ -n "$CC_MATCH" ]; then
              echo "FAIL: Direct dependencies of Creditcoin found in audit report"
              echo "INFO: Inspect the output above for more information"
              exit 1
          else
              echo "INFO: No direct dependencies of Creditcoin found in audit report"
              exit 0
          fi

  cargo-fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          components: rustfmt
      - uses: Swatinem/rust-cache@v2

      - name: Check formatting
        uses: gluwa/cargo@dev
        with:
          command: fmt
          args: -- --check

      - name: Check TOML formatting
        run: |
          cargo install taplo-cli --locked
          taplo format --check

  cargo-check:
    needs:
      - deploy-runner-check
    runs-on: [self-hosted, "workflow-${{ github.run_id }}", "proxy-check"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6

      - name: Install protobuf
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2

      - name: Check Build
        run: |
          SKIP_WASM_BUILD=1 cargo check --release

      - name: Check Build for Benchmarking
        run: |
          SKIP_WASM_BUILD=1 cargo check --features=runtime-benchmarks --release

      # keep this always as the last step
      - name: Schedule self-hosted shutdown
        if: always()
        run: |
          # unreliable
          sudo nohup shutdown +10 1>/dev/null 2>/dev/null & disown

  cargo-clippy:
    needs:
      - deploy-runner-clippy
    runs-on: [self-hosted, "workflow-${{ github.run_id }}", "proxy-clippy"]
    steps:
      - uses: actions/checkout@v6

      - name: Install protobuf
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          targets: wasm32-unknown-unknown
          components: clippy, rust-src
      - uses: Swatinem/rust-cache@v2

      - name: Print clippy's version
        uses: gluwa/cargo@dev
        with:
          command: clippy
          args: --version

      - name: Run Clippy
        uses: gluwa/cargo@dev
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

      # keep this always as the last step
      - name: Schedule self-hosted shutdown
        if: always()
        run: |
          # unreliable
          sudo nohup shutdown +10 1>/dev/null 2>/dev/null & disown

  cargo-machete:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}

      - uses: Swatinem/rust-cache@v2

      - name: Execute cargo machete
        uses: bnjbvr/cargo-machete@main

  cargo-test:
    needs:
      - deploy-runner-unit-test-creditcoin
    runs-on:
      [
        self-hosted,
        "workflow-${{ github.run_id }}",
        "proxy-unit-test-creditcoin",
      ]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GLUWA_BOT_TOKEN }}

      - name: Install protobuf
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          components: llvm-tools-preview, rust-src
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2.69.7
        with:
          tool: cargo-llvm-cov@0.6.24

      - name: Run tests
        run: |
          cargo llvm-cov \
              --release \
              --workspace --html --show-missing-lines --hide-instantiations \
              --ignore-filename-regex "(benchmarking.rs|mock.rs|tests(.*).rs|weights.rs)"

      - name: Run simulations
        id: simulation
        env:
          PROPTEST_CASES: 10000
        run: |
          cargo test \
            --release \
            --features simulation \
            -p stream_attestation \
            simulate

      - name: Commit regression files
        uses: EndBug/add-and-commit@v10
        if: always()
        with:
          push: true
          add: common/streams/attestation/proptest-regressions/simulation/mod.txt
          author_name: gluwa-bot
          author_email: creditcoin@gluwa.com
          message: "test(simulation): found new bug"
          github_token: ${{ secrets.GLUWA_BOT_TOKEN }}

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: target/llvm-cov/html/

      # keep this always as the last step
      - name: Schedule self-hosted shutdown
        if: always()
        run: |
          # unreliable
          sudo nohup shutdown +10 1>/dev/null 2>/dev/null & disown

  deploy-runner-clippy:
    uses: ./.github/workflows/deploy-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      LINODE_REGION: "nl-ams"
      LINODE_VM_SIZE: "g6-standard-4"
      proxy: "clippy"
    secrets: inherit

  deploy-runner-check:
    uses: ./.github/workflows/deploy-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      LINODE_REGION: "nl-ams"
      LINODE_VM_SIZE: "g6-standard-4"
      proxy: "check"
    secrets: inherit

  deploy-runner-unit-test-creditcoin:
    uses: ./.github/workflows/deploy-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      LINODE_REGION: "nl-ams"
      LINODE_VM_SIZE: "g6-standard-4"
      proxy: "unit-test-creditcoin"
    secrets: inherit

  rm-gh-runner-clippy:
    needs:
      - cargo-clippy
    if: ${{ always() }}
    uses: ./.github/workflows/remove-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      proxy: "clippy"
    secrets: inherit

  rm-gh-runner-check:
    needs:
      - cargo-check
    if: ${{ always() }}
    uses: ./.github/workflows/remove-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      proxy: "check"
    secrets: inherit

  rm-gh-runner-unit-test-creditcoin:
    needs:
      - cargo-test
    if: ${{ always() }}
    uses: ./.github/workflows/remove-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      proxy: "unit-test-creditcoin"
    secrets: inherit
