---
name: shell-check

# Controls when the action will run.
"on":
  pull_request:
    paths:
      - '**.sh'
      - '.github/workflows/shell-check.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  shell-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        env:
          SHELLCHECK_OPTS: -e SC2002 # allow useless cat commands
