---
name: Try Runtime

"on":
  pull_request:
    branches: [usc-dev, main]
    paths:
      - "**/migrations/**"
      - "**/migrations.rs"
      - "runtime/src/lib.rs"
      - ".github/workflows/try-runtime.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  try-runtime:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Install protobuf
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          targets: wasm32-unknown-unknown
          components: rust-src

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: build-creditcoin-node

      - name: Bump version to force try-runtime to attempt to apply migrations
        id: bump-version
        run: |
          .github/bump-version.sh

          git status
          git diff

      - name: Build runtime with try-runtime
        run: |
          cargo build --release -p creditcoin3-runtime --features try-runtime

      - name: Install try-runtime-cli
        run: |
          cargo install --git https://github.com/paritytech/try-runtime-cli --locked

      - name: Execute try-runtime against CC3 Devnet
        if: github.base_ref == 'usc-dev'
        timeout-minutes: 30
        run: |
          try-runtime \
            --runtime ./target/release/wbuild/creditcoin3-runtime/creditcoin3_runtime.wasm \
            on-runtime-upgrade \
            --blocktime 15000 \
            live --uri wss://rpc.cc3-devnet.creditcoin.network

      - name: Execute try-runtime against CC3 Mainnet
        timeout-minutes: 60
        run: |
          try-runtime \
            --runtime ./target/release/wbuild/creditcoin3-runtime/creditcoin3_runtime.wasm \
            on-runtime-upgrade \
            --blocktime 15000 \
            live --uri wss://rpc.cc3-mainnet.creditcoin.network
