---
name: Build WASM Runtime

"on":
  push:
    branches: [main, testnet, dev, poc_external_attestation_network]
  pull_request:
    branches: [testnet, dev, poc_external_attestation_network]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

env:
  RUNNER_VM_NAME: "${{ github.event.repository.name }}-$GITHUB_RUN_ID-attempt-$GITHUB_RUN_ATTEMPT"
  LINODE_REGION: "nl-ams"
  # Shared CPU, Linode 8 GB, 4 vCPU, 96 $/mo
  LINODE_VM_SIZE: "g6-standard-4"

jobs:
  deploy-github-runner:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: wasm

    name: deploy-github-runner / ${{ matrix.build }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      # See https://github.com/actions/runner/issues/1879#issuecomment-1123196869
      - name: Create matrix.txt
        run: |
          echo "${{ matrix.build }}" > matrix.txt

      - name: Evaluate env vars
        id: get-env
        run: |
          HASH_VALUE=$(echo "${{ hashFiles('matrix.txt') }}" | cut -c1-7)
          rm matrix.txt

          # WARNING: using env.RUNNER_VM_NAME directly in job outputs above
          # doesn't evaluate the $GITHUB_RUN_ID reference
          echo "runner_vm_name=${{ env.RUNNER_VM_NAME }}-$HASH_VALUE" >> "$GITHUB_OUTPUT"

      - name: Provision VM
        if: env.LC_GITHUB_REPO_ADMIN_TOKEN
        run: |
          .github/provision-linode-vm.sh
        env:
          LC_OWNER_REPO_SLUG: ${{ github.repository }}
          LC_GITHUB_REPO_ADMIN_TOKEN: ${{ secrets.GH_REPO_ADMIN_TOKEN }}
          LC_RUNNER_VM_NAME: ${{ steps.get-env.outputs.runner_vm_name }}
          LC_PROXY_TYPE: ${{ matrix.build }}
          LC_WORKFLOW_ID: ${{ github.run_id }}
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}

  rm-gh-runner-wasm:
    runs-on: ubuntu-24.04
    needs:
      - build
    if: ${{ always() }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: wasm

    steps:
      - uses: actions/checkout@v5

      # See https://github.com/actions/runner/issues/1879#issuecomment-1123196869
      - name: Create matrix.txt
        run: |
          echo "${{ matrix.build }}" > matrix.txt

      - name: Evaluate env vars
        id: get-env
        run: |
          HASH_VALUE=$(echo "${{ hashFiles('matrix.txt') }}" | cut -c1-7)
          rm matrix.txt

          echo "runner_vm_name=${{ env.RUNNER_VM_NAME }}-$HASH_VALUE" >> "$GITHUB_OUTPUT"

      - name: Remove VM
        continue-on-error: true
        run: |
          .github/remove-linode-vm.sh
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
          LC_RUNNER_VM_NAME: ${{ steps.get-env.outputs.runner_vm_name }}

  build:
    needs:
      - deploy-github-runner
    uses: ./.github/workflows/build-wasm.yml
    with:
      build-options: "--features fast-runtime"
      version-string: ${{ github.sha }}
      runs-on: "['self-hosted', 'workflow-${{ github.run_id }}', 'type-wasm']"

  # try installing subwasm b/c we use this version in multiple places
  # and need to know whether it builds with current rustc
  dry-run-install-subwasm:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}

      - name: Install Subwasm
        uses: gluwa/cargo@dev
        with:
          command: install
          args: --locked --git https://github.com/chevdor/subwasm --tag v0.21.3

  upgrade-devnet:
    runs-on: ubuntu-24.04
    needs: build
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true

      - uses: actions/download-artifact@v6
        with:
          name: binary-for-wasm
          path: wasm

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}

      - name: Install Subwasm
        uses: gluwa/cargo@dev
        with:
          command: install
          args: --locked --git https://github.com/chevdor/subwasm --tag v0.21.3

      - name: Install JS Dependencies
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - working-directory: cli
        run: |
          npm install -g yarn
          npm install -g node-gyp
          yarn install
          yarn build

      - name: Upgrade WASM
        working-directory: cli
        env:
          DEVNET_URL: wss://rpc.cc3-devnet.creditcoin.network/ws
          SUDO_SEED: ${{ secrets.DEVNET_SUDO_SEED }}
        run: |
          node dist/scripts/runtimeUpgrade.js "$DEVNET_URL" ../wasm/creditcoin-${{ github.sha }}-runtime.wasm "$SUDO_SEED" 0
