---
name: Build WASM Runtime

"on":
  push:
    branches: [dev]
  pull_request:
    branches: [main, testnet, poc_external_attestation_network]
    paths:
      - '**.rs'
      - '**.toml'
      - '**Cargo**'
      - '.github/workflows/wasm.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  deploy-github-runner:
    uses: ./.github/workflows/deploy-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      LINODE_REGION: "nl-ams"
      LINODE_VM_SIZE: "g6-standard-4"
      proxy_type: "wasm"
    secrets: inherit

  rm-gh-runner-wasm:
    needs:
      - build
    if: ${{ always() }}
    uses: ./.github/workflows/remove-runner.yml
    with:
      RUNNER_VM_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}-attempt-${{ github.run_attempt }}"
      proxy_type: "wasm"
    secrets: inherit

  build:
    needs:
      - deploy-github-runner
    uses: ./.github/workflows/build-wasm.yml
    with:
      build-options: "--features fast-runtime"
      version-string: ${{ github.sha }}
      runs-on: "['self-hosted', 'workflow-${{ github.run_id }}', 'type-wasm']"

  # try installing subwasm b/c we use this version in multiple places
  # and need to know whether it builds with current rustc
  dry-run-install-subwasm:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}

      - name: Install Subwasm
        uses: gluwa/cargo@dev
        with:
          command: install
          args: --locked --git https://github.com/chevdor/subwasm --tag v0.21.3

  upgrade-devnet:
    runs-on: ubuntu-24.04
    needs: build
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true

      - uses: actions/download-artifact@v6
        with:
          name: binary-for-wasm
          path: wasm

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}

      - name: Install Subwasm
        uses: gluwa/cargo@dev
        with:
          command: install
          args: --locked --git https://github.com/chevdor/subwasm --tag v0.21.3

      - name: Install JS Dependencies
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - working-directory: cli
        run: |
          npm install -g yarn
          npm install -g node-gyp
          yarn install
          yarn build

      - name: Upgrade WASM
        working-directory: cli
        env:
          DEVNET_URL: wss://rpc.cc3-devnet.creditcoin.network/ws
          SUDO_SEED: ${{ secrets.DEVNET_SUDO_SEED }}
        run: |
          node dist/scripts/runtimeUpgrade.js "$DEVNET_URL" ../wasm/creditcoin-${{ github.sha }}-runtime.wasm "$SUDO_SEED" 0
